"""ORM models (import side effect: registers tables on Base.metadata)."""

from app.models.audit import AuditEntry, EmailMessage, Notification
from app.models.contractors import Contractor, ProjectEngagement
from app.models.hse import (
    AiAnswerRecord,
    AiInsightCache,
    AiLog,
    Attachment,
    CaExtension,
    CorrectiveAction,
    DashboardPreference,
    ExternalNotification,
    HseMeeting,
    HseSettings,
    Incident,
    InjuryCase,
    Inspection,
    InspectionPlan,
    Investigation,
    JobMark,
    MonthlyReport,
    Observation,
    PeriodLock,
    ReferenceItem,
    WorkforceImportBatch,
    WorkforceReturn,
)
from app.models.org import Project, ProjectSettings, Site, Zone
from app.models.users import RoleAssignment, TokenKind, User, UserSession, UserToken

__all__ = [
    "AiAnswerRecord",
    "AiInsightCache",
    "AiLog",
    "Attachment",
    "AuditEntry",
    "CaExtension",
    "Contractor",
    "CorrectiveAction",
    "DashboardPreference",
    "EmailMessage",
    "ExternalNotification",
    "HseMeeting",
    "HseSettings",
    "Incident",
    "InjuryCase",
    "Inspection",
    "InspectionPlan",
    "Investigation",
    "JobMark",
    "MonthlyReport",
    "Notification",
    "Observation",
    "PeriodLock",
    "Project",
    "ProjectEngagement",
    "ProjectSettings",
    "ReferenceItem",
    "RoleAssignment",
    "Site",
    "TokenKind",
    "User",
    "UserSession",
    "UserToken",
    "WorkforceImportBatch",
    "WorkforceReturn",
    "Zone",
]
