import { AlertTriangle, Archive, Ban, OctagonAlert, CheckCircle2, CircleDashed, Clock, FileCheck2, Hourglass, Info, Loader, Lock, PackageCheck, PauseCircle, PlayCircle, Search, ShieldCheck, Undo2, XCircle } from "lucide-react";
import type { ComponentType, SVGProps } from "react";
import { Badge, type BadgeProps } from "@/components/ui/badge";

type Tone = NonNullable<BadgeProps["tone"]>;
const MAP: Record<string, { tone: Tone; Icon: ComponentType<SVGProps<SVGSVGElement>> }> = {
  active: { tone: "success", Icon: CheckCircle2 },
  approved: { tone: "success", Icon: CheckCircle2 },
  success: { tone: "success", Icon: CheckCircle2 },
  planning: { tone: "info", Icon: CircleDashed },
  draft: { tone: "info", Icon: CircleDashed },
  invited: { tone: "info", Icon: Clock },
  pending_approval: { tone: "info", Icon: Clock },
  on_hold: { tone: "warning", Icon: PauseCircle },
  temporarily_closed: { tone: "warning", Icon: PauseCircle },
  suspended: { tone: "warning", Icon: PauseCircle },
  locked: { tone: "warning", Icon: Lock },
  denied: { tone: "warning", Icon: Ban },
  closed: { tone: "neutral", Icon: Archive },
  archived: { tone: "neutral", Icon: Archive },
  inactive: { tone: "neutral", Icon: Archive },
  demobilised: { tone: "neutral", Icon: Archive },
  deactivated: { tone: "neutral", Icon: XCircle },
  blacklisted: { tone: "danger", Icon: Ban },
  failed: { tone: "danger", Icon: XCircle },
  // Phase 1
  submitted: { tone: "info", Icon: Clock },
  verified: { tone: "success", Icon: ShieldCheck },
  reported: { tone: "info", Icon: Clock },
  under_investigation: { tone: "info", Icon: Search },
  pending_review: { tone: "warning", Icon: Hourglass },
  actions_pending: { tone: "warning", Icon: Hourglass },
  voided: { tone: "neutral", Icon: XCircle },
  open: { tone: "warning", Icon: CircleDashed },
  action_raised: { tone: "info", Icon: Clock },
  planned: { tone: "info", Icon: Clock },
  completed: { tone: "success", Icon: CheckCircle2 },
  missed: { tone: "danger", Icon: AlertTriangle },
  cancelled: { tone: "neutral", Icon: XCircle },
  in_progress: { tone: "info", Icon: Loader },
  pending_verification: { tone: "warning", Icon: Hourglass },
  generating: { tone: "info", Icon: Loader },
  reviewed: { tone: "info", Icon: ShieldCheck },
  published: { tone: "success", Icon: CheckCircle2 },
  validated: { tone: "info", Icon: ShieldCheck },
  committed: { tone: "success", Icon: CheckCircle2 },
  discarded: { tone: "neutral", Icon: XCircle },
  expired: { tone: "danger", Icon: AlertTriangle },
  provisional: { tone: "warning", Icon: Hourglass },
  confirmed: { tone: "success", Icon: CheckCircle2 },
  due: { tone: "warning", Icon: Clock },
  done: { tone: "success", Icon: CheckCircle2 },
  overdue: { tone: "danger", Icon: AlertTriangle },
  requested: { tone: "info", Icon: Clock },
  rejected: { tone: "danger", Icon: XCircle },
  ok: { tone: "success", Icon: CheckCircle2 },
  warning: { tone: "warning", Icon: AlertTriangle },
  error: { tone: "danger", Icon: XCircle },
  on_time: { tone: "success", Icon: CheckCircle2 },
  late: { tone: "warning", Icon: Clock },
  pending: { tone: "info", Icon: Hourglass },
  unplanned: { tone: "neutral", Icon: CircleDashed },
  // Month lock: a locked month is the normal, final state (not a warning).
  month_open: { tone: "info", Icon: CircleDashed },
  month_locked: { tone: "neutral", Icon: Lock },
  // Risk / finding severity: red only for high/critical; low is not an alarm.
  risk_high: { tone: "danger", Icon: AlertTriangle },
  risk_medium: { tone: "warning", Icon: AlertTriangle },
  risk_low: { tone: "neutral", Icon: Info },
  hipo: { tone: "warning", Icon: AlertTriangle },
  // Phase 2 — access permits and credentials
  pending_induction: { tone: "info", Icon: Hourglass },
  mobilised: { tone: "success", Icon: CheckCircle2 },
  valid: { tone: "success", Icon: CheckCircle2 },
  superseded: { tone: "neutral", Icon: Archive },
  revoked: { tone: "danger", Icon: Ban },
  banned: { tone: "danger", Icon: Ban },
  anonymised: { tone: "neutral", Icon: Archive },
  endorsed: { tone: "info", Icon: ShieldCheck },
  lodged: { tone: "info", Icon: Clock },
  issued: { tone: "success", Icon: CheckCircle2 },
  refused: { tone: "danger", Icon: XCircle },
  withdrawn: { tone: "neutral", Icon: XCircle },
  held: { tone: "neutral", Icon: PackageCheck },
  return_due: { tone: "warning", Icon: Undo2 },
  return_overdue: { tone: "danger", Icon: AlertTriangle },
  returned: { tone: "success", Icon: PackageCheck },
  lost: { tone: "danger", Icon: AlertTriangle },
  raised: { tone: "warning", Icon: Hourglass },
  system: { tone: "warning", Icon: Lock },
  recorded: { tone: "warning", Icon: Clock },
  disputed: { tone: "info", Icon: Search },
  upheld: { tone: "danger", Icon: AlertTriangle },
  submitted_to_ops: { tone: "info", Icon: Clock },
  requested_from_ais: { tone: "info", Icon: Clock },
  replaced: { tone: "neutral", Icon: Archive },
  approved_with_conditions: { tone: "success", Icon: CheckCircle2 },
  off_site: { tone: "neutral", Icon: Archive },
  included: { tone: "success", Icon: CheckCircle2 },
  excluded: { tone: "danger", Icon: Ban },
  removed: { tone: "neutral", Icon: XCircle },
  met: { tone: "success", Icon: CheckCircle2 },
  not_met: { tone: "danger", Icon: XCircle },
  expiring: { tone: "warning", Icon: Clock },
  // Hook results that are not checked yet: amber information, never an error.
  warn: { tone: "warning", Icon: Info },
  // Phase 2 design: a gate entry granted with a note is still an entry — amber (spec) but with a tick.
  granted_note: { tone: "warning", Icon: CheckCircle2 },
  not_evaluated: { tone: "neutral", Icon: CircleDashed },
  rotated: { tone: "neutral", Icon: Archive },
  cleared: { tone: "success", Icon: ShieldCheck },
  not_cleared: { tone: "danger", Icon: XCircle },
  not_required: { tone: "neutral", Icon: CircleDashed },
  // Phase 3 — permits to work, gas, isolation, SIMOPS, audits
  review_due: { tone: "warning", Icon: Clock },
  in_service: { tone: "success", Icon: CheckCircle2 },
  quarantined: { tone: "danger", Icon: Ban },
  retired: { tone: "neutral", Icon: Archive },
  isolated: { tone: "info", Icon: Lock },
  deisolation_requested: { tone: "warning", Icon: Hourglass },
  deisolated: { tone: "neutral", Icon: Archive },
  coordinated: { tone: "success", Icon: ShieldCheck },
  resolved_by_change: { tone: "neutral", Icon: CheckCircle2 },
  signed: { tone: "success", Icon: CheckCircle2 },
  initiated: { tone: "info", Icon: Clock },
  accepted: { tone: "success", Icon: CheckCircle2 },
  lapsed: { tone: "neutral", Icon: XCircle },
  listed: { tone: "success", Icon: CheckCircle2 },
  compliant: { tone: "success", Icon: CheckCircle2 },
  non_compliant: { tone: "danger", Icon: XCircle },
  due_soon: { tone: "warning", Icon: Clock },
  missing: { tone: "danger", Icon: AlertTriangle },
  available: { tone: "neutral", Icon: CircleDashed },
  applied: { tone: "info", Icon: Lock },
  cut: { tone: "danger", Icon: AlertTriangle },
  granted: { tone: "success", Icon: CheckCircle2 },
  prohibited: { tone: "danger", Icon: Ban },
  conditional: { tone: "warning", Icon: AlertTriangle },
  allowed: { tone: "success", Icon: CheckCircle2 },
  locked_audit: { tone: "neutral", Icon: Lock },
  // Phase 3 design: only an Active permit is green (work in progress); approved / issued are not yet work.
  ptw_approved: { tone: "info", Icon: ShieldCheck },
  ptw_issued: { tone: "info", Icon: FileCheck2 },
  ptw_active: { tone: "success", Icon: PlayCircle },
  // Phase 4 — certification. Out of service / quarantined are hard stops (red); unverified is amber.
  awaiting_certificate: { tone: "info", Icon: Hourglass },
  out_of_service: { tone: "danger", Icon: Ban },
  historic: { tone: "neutral", Icon: Archive },
  on_site: { tone: "success", Icon: CheckCircle2 },
  rectified: { tone: "info", Icon: Hourglass },
  lifted: { tone: "neutral", Icon: Undo2 },
  verif_not_verified: { tone: "warning", Icon: Hourglass },
  verif_verified: { tone: "success", Icon: ShieldCheck },
  verif_failed: { tone: "danger", Icon: XCircle },
  verif_unable_to_verify: { tone: "danger", Icon: AlertTriangle },
  tag_green: { tone: "success", Icon: CheckCircle2 },
  tag_yellow: { tone: "warning", Icon: AlertTriangle },
  tag_red: { tone: "danger", Icon: Ban },
  tag_expired: { tone: "danger", Icon: AlertTriangle },
  tag_inspection_required: { tone: "danger", Icon: Search },
  tag_none: { tone: "neutral", Icon: CircleDashed },
  scaffold_under_erection: { tone: "info", Icon: Loader },
  scaffold_in_use: { tone: "success", Icon: CheckCircle2 },
  scaffold_closed_red: { tone: "danger", Icon: Ban },
  scaffold_under_alteration: { tone: "warning", Icon: Loader },
  scaffold_dismantled: { tone: "neutral", Icon: Archive },
  defect_A: { tone: "danger", Icon: OctagonAlert },
  defect_B: { tone: "warning", Icon: AlertTriangle },
  defect_C: { tone: "neutral", Icon: Info },
  hook_warn: { tone: "info", Icon: Info },
  hook_transition: { tone: "warning", Icon: Hourglass },
  hook_block: { tone: "danger", Icon: Lock },
  check_in_service: { tone: "success", Icon: CheckCircle2 },
  check_restricted: { tone: "warning", Icon: AlertTriangle },
  check_not_usable: { tone: "danger", Icon: Ban },
  check_revoked_token: { tone: "danger", Icon: Ban },
  check_unknown: { tone: "neutral", Icon: CircleDashed },
  line_pass: { tone: "success", Icon: CheckCircle2 },
  line_pass_with_conditions: { tone: "warning", Icon: AlertTriangle },
  line_fail: { tone: "danger", Icon: XCircle },
  // Phase 5 — training. A gap is a hard stop (red); exempt is a recorded decision (neutral).
  scheduled: { tone: "info", Icon: Clock },
  delivered: { tone: "info", Icon: PackageCheck },
  nominated: { tone: "info", Icon: CircleDashed },
  attended: { tone: "success", Icon: CheckCircle2 },
  partial: { tone: "warning", Icon: AlertTriangle },
  absent: { tone: "danger", Icon: XCircle },
  passed: { tone: "success", Icon: CheckCircle2 },
  incomplete: { tone: "warning", Icon: Hourglass },
  gap: { tone: "danger", Icon: AlertTriangle },
  exempt: { tone: "neutral", Icon: ShieldCheck },
  not_booked: { tone: "danger", Icon: AlertTriangle },
  booked_in_time: { tone: "success", Icon: CheckCircle2 },
  booked_late: { tone: "warning", Icon: Clock },
  in_force: { tone: "success", Icon: CheckCircle2 },
  not_in_force: { tone: "neutral", Icon: CircleDashed },
  mandatory: { tone: "danger", Icon: Lock },
  recommended: { tone: "info", Icon: Info },
};

/** Status shown with colour + icon + text (never colour alone). */
export function StatusBadge({ status, label }: { status: string; label: string }) {
  const { tone, Icon } = MAP[status] ?? { tone: "neutral" as Tone, Icon: CircleDashed };
  return (
    <Badge tone={tone} data-status={status}>
      <Icon aria-hidden />
      {label}
    </Badge>
  );
}
