"""phase6f incident followup

Revision ID: 0014
Revises: 0013
Create Date: 2026-10-09 22:35:03.955724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0014'
down_revision: Union[str, Sequence[str], None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fu_rules',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Enum('gosi', 'mhrsd', 'civil_defense', 'gaca', 'airport_operator', 'client', 'police', 'ncec', name='externalbody', native_enum=False, length=40), nullable=False),
    sa.Column('stage', sa.Enum('verbal', 'written', 'interim', 'final', name='fustage', native_enum=False, length=40), nullable=False),
    sa.Column('source', sa.Enum('statutory', 'client', name='furulesource', native_enum=False, length=40), nullable=False),
    sa.Column('triggers', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('trigger_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deadline_hours', sa.Integer(), nullable=True),
    sa.Column('deadline_basis', sa.Enum('trigger', 'investigation_due', name='fudeadlinebasis', native_enum=False, length=40), nullable=False),
    sa.Column('form_code', sa.String(length=20), nullable=True),
    sa.Column('filer', sa.Enum('main_contractor', 'employer_engagement', 'airport_operator', name='fufiler', native_enum=False, length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_fu_rules_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_fu_rules_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_fu_rules_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fu_rules')),
    sa.UniqueConstraint('project_id', 'rule_code', name=op.f('uq_fu_rules_project_id'))
    )
    op.create_index(op.f('ix_fu_rules_project_id'), 'fu_rules', ['project_id'], unique=False)
    op.create_table('project_followup_settings',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('followup_rules_from', sa.Date(), nullable=True),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body_directory', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signatory_role_en', sa.String(length=120), nullable=True),
    sa.Column('signatory_role_ar', sa.String(length=120), nullable=True),
    sa.Column('client_identity_clause', sa.String(length=1000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_followup_settings_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_project_followup_settings_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_followup_settings'))
    )
    op.create_table('fu_incident_clocks',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_times', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('derived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_fu_incident_clocks_incident_id_incidents')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_fu_incident_clocks_project_id_projects')),
    sa.PrimaryKeyConstraint('incident_id', name=op.f('pk_fu_incident_clocks'))
    )
    op.create_index(op.f('ix_fu_incident_clocks_project_id'), 'fu_incident_clocks', ['project_id'], unique=False)
    op.create_table('fu_lessons',
    sa.Column('lesson_no', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('incident', 'external', name='fulessonsource', native_enum=False, length=40), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('source_project_id', sa.Uuid(), nullable=True),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('system_created', sa.Boolean(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('title_en', sa.String(length=150), nullable=True),
    sa.Column('title_ar', sa.String(length=150), nullable=True),
    sa.Column('what_happened_en', sa.Text(), nullable=True),
    sa.Column('what_happened_ar', sa.Text(), nullable=True),
    sa.Column('why_en', sa.Text(), nullable=True),
    sa.Column('why_ar', sa.Text(), nullable=True),
    sa.Column('root_cause_codes', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('key_lessons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applicability', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity_potential', sa.Integer(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('distribution_project_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('removed_engagements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('publish_due_on', sa.Date(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.Uuid(), nullable=True),
    sa.Column('return_comment', sa.String(length=500), nullable=True),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'published', 'archived', name='fulessonstatus', native_enum=False, length=40), nullable=False),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_fu_lessons_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_fu_lessons_author_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_fu_lessons_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_fu_lessons_incident_id_incidents')),
    sa.ForeignKeyConstraint(['source_project_id'], ['projects.id'], name=op.f('fk_fu_lessons_source_project_id_projects')),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['fu_lessons.id'], name=op.f('fk_fu_lessons_superseded_by_id_fu_lessons')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_fu_lessons_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fu_lessons')),
    sa.UniqueConstraint('lesson_no', name=op.f('uq_fu_lessons_lesson_no')),
    sa.UniqueConstraint('year', 'seq', name=op.f('uq_fu_lessons_year'))
    )
    op.create_index(op.f('ix_fu_lessons_incident_id'), 'fu_lessons', ['incident_id'], unique=False)
    op.create_table('fu_requirements',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=16), nullable=False),
    sa.Column('case_key', sa.String(length=8), nullable=False),
    sa.Column('body', sa.Enum('gosi', 'mhrsd', 'civil_defense', 'gaca', 'airport_operator', 'client', 'police', 'ncec', name='externalbody', native_enum=False, length=40), nullable=False),
    sa.Column('stage', sa.Enum('verbal', 'written', 'interim', 'final', name='fustage', native_enum=False, length=40), nullable=False),
    sa.Column('source', sa.Enum('statutory', 'client', name='furulesource', native_enum=False, length=40), nullable=False),
    sa.Column('form_code', sa.String(length=20), nullable=True),
    sa.Column('filer', sa.Enum('main_contractor', 'employer_engagement', 'airport_operator', name='fufiler', native_enum=False, length=40), nullable=False),
    sa.Column('trigger_met_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_hours', sa.Integer(), nullable=True),
    sa.Column('filer_engagement_id', sa.Uuid(), nullable=True),
    sa.Column('responsible_engagement_id', sa.Uuid(), nullable=True),
    sa.Column('case_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('not_required_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_note', sa.String(length=200), nullable=True),
    sa.Column('waiver_reason_code', sa.Enum('not_covered_by_gosi', 'body_confirmed_not_required', 'reported_by_other_party', 'incident_reclassified', name='fuwaiverreason', native_enum=False, length=40), nullable=True),
    sa.Column('waiver_text', sa.String(length=500), nullable=True),
    sa.Column('waiver_reference', sa.String(length=60), nullable=True),
    sa.Column('waiver_file_id', sa.Uuid(), nullable=True),
    sa.Column('waived_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('waived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_fu_requirements_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['filer_engagement_id'], ['project_engagements.id'], name=op.f('fk_fu_requirements_filer_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_fu_requirements_incident_id_incidents')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_fu_requirements_project_id_projects')),
    sa.ForeignKeyConstraint(['responsible_engagement_id'], ['project_engagements.id'], name=op.f('fk_fu_requirements_responsible_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_fu_requirements_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['waived_by_user_id'], ['users.id'], name=op.f('fk_fu_requirements_waived_by_user_id_users')),
    sa.ForeignKeyConstraint(['waiver_file_id'], ['attachments.id'], name=op.f('fk_fu_requirements_waiver_file_id_attachments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fu_requirements')),
    sa.UniqueConstraint('incident_id', 'rule_code', 'case_key', name=op.f('uq_fu_requirements_incident_id'))
    )
    op.create_index('ix_fu_requirement_project_due', 'fu_requirements', ['project_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_fu_requirements_incident_id'), 'fu_requirements', ['incident_id'], unique=False)
    op.create_table('fu_distribution_items',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('ack_due_on', sa.Date(), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response', sa.Enum('will_brief', 'not_applicable', name='fuackresponse', native_enum=False, length=40), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('on_behalf_note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'acknowledged', 'not_applicable', 'withdrawn', name='fudistributionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], name=op.f('fk_fu_distribution_items_acknowledged_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_fu_distribution_items_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_fu_distribution_items_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['lesson_id'], ['fu_lessons.id'], name=op.f('fk_fu_distribution_items_lesson_id_fu_lessons')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_fu_distribution_items_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_fu_distribution_items_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fu_distribution_items')),
    sa.UniqueConstraint('lesson_id', 'project_id', 'engagement_id', name=op.f('uq_fu_distribution_items_lesson_id'))
    )
    op.create_index(op.f('ix_fu_distribution_items_lesson_id'), 'fu_distribution_items', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_fu_distribution_items_project_id'), 'fu_distribution_items', ['project_id'], unique=False)
    op.create_table('fu_effectiveness_checks',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_result', sa.Enum('effective', 'partly_effective', 'not_effective', name='fueffectresult', native_enum=False, length=40), nullable=True),
    sa.Column('result', sa.Enum('effective', 'partly_effective', 'not_effective', name='fueffectresult', native_enum=False, length=40), nullable=True),
    sa.Column('rationale', sa.String(length=1000), nullable=True),
    sa.Column('follow_up_ca_id', sa.Uuid(), nullable=True),
    sa.Column('follow_up_lesson_id', sa.Uuid(), nullable=True),
    sa.Column('completed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', name='fucheckstatus', native_enum=False, length=40), nullable=False),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], name=op.f('fk_fu_effectiveness_checks_completed_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_fu_effectiveness_checks_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['follow_up_ca_id'], ['corrective_actions.id'], name=op.f('fk_fu_effectiveness_checks_follow_up_ca_id_corrective_actions')),
    sa.ForeignKeyConstraint(['follow_up_lesson_id'], ['fu_lessons.id'], name=op.f('fk_fu_effectiveness_checks_follow_up_lesson_id_fu_lessons')),
    sa.ForeignKeyConstraint(['lesson_id'], ['fu_lessons.id'], name=op.f('fk_fu_effectiveness_checks_lesson_id_fu_lessons')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_fu_effectiveness_checks_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_fu_effectiveness_checks_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fu_effectiveness_checks')),
    sa.UniqueConstraint('lesson_id', name=op.f('uq_fu_effectiveness_checks_lesson_id'))
    )
    op.create_index(op.f('ix_fu_effectiveness_checks_project_id'), 'fu_effectiveness_checks', ['project_id'], unique=False)
    op.create_table('fu_lesson_links',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('topic', 'campaign', 'template_change', name='fulinkkind', native_enum=False, length=40), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('item_code', sa.String(length=20), nullable=True),
    sa.Column('proposed_text_en', sa.String(length=1000), nullable=True),
    sa.Column('proposed_text_ar', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('open', 'adopted', 'rejected', name='fuchangestatus', native_enum=False, length=40), nullable=True),
    sa.Column('adopted_version', sa.Integer(), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_fu_lesson_links_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_fu_lesson_links_decided_by_user_id_users')),
    sa.ForeignKeyConstraint(['lesson_id'], ['fu_lessons.id'], name=op.f('fk_fu_lesson_links_lesson_id_fu_lessons')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_fu_lesson_links_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_fu_lesson_links_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fu_lesson_links'))
    )
    op.create_index(op.f('ix_fu_lesson_links_lesson_id'), 'fu_lesson_links', ['lesson_id'], unique=False)
    op.create_table('fu_packs',
    sa.Column('pack_no', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('form_code', sa.String(length=20), nullable=False),
    sa.Column('field_set', sa.Enum('none', 'identity', 'identity_medical', name='fufieldset', native_enum=False, length=40), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative_en', sa.Text(), nullable=True),
    sa.Column('narrative_ar', sa.Text(), nullable=True),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('identity_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'submitted', 'superseded', name='fupackstatus', native_enum=False, length=40), nullable=False),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_fu_packs_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_fu_packs_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['file_id'], ['attachments.id'], name=op.f('fk_fu_packs_file_id_attachments')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_fu_packs_project_id_projects')),
    sa.ForeignKeyConstraint(['requirement_id'], ['fu_requirements.id'], name=op.f('fk_fu_packs_requirement_id_fu_requirements')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_fu_packs_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fu_packs')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_fu_packs_project_id'))
    )
    op.create_index(op.f('ix_fu_packs_project_id'), 'fu_packs', ['project_id'], unique=False)
    op.create_index(op.f('ix_fu_packs_requirement_id'), 'fu_packs', ['requirement_id'], unique=False)
    op.create_table('fu_submissions',
    sa.Column('submission_no', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('pack_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('portal', 'email', 'hand_delivered', 'courier', 'phone_radio', 'meeting', name='fuchannel', native_enum=False, length=40), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contacted_desk_en', sa.String(length=120), nullable=True),
    sa.Column('contacted_desk_ar', sa.String(length=120), nullable=True),
    sa.Column('reference_no', sa.String(length=60), nullable=True),
    sa.Column('call_note', sa.String(length=200), nullable=True),
    sa.Column('evidence_file_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('stamped_copy_file_id', sa.Uuid(), nullable=True),
    sa.Column('external_document_id', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ack_reference', sa.String(length=60), nullable=True),
    sa.Column('ack_file_id', sa.Uuid(), nullable=True),
    sa.Column('on_time', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('recorded', 'acknowledged', 'voided', name='fusubmissionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ack_file_id'], ['attachments.id'], name=op.f('fk_fu_submissions_ack_file_id_attachments')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_fu_submissions_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['external_document_id'], ['attachments.id'], name=op.f('fk_fu_submissions_external_document_id_attachments')),
    sa.ForeignKeyConstraint(['pack_id'], ['fu_packs.id'], name=op.f('fk_fu_submissions_pack_id_fu_packs')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_fu_submissions_project_id_projects')),
    sa.ForeignKeyConstraint(['requirement_id'], ['fu_requirements.id'], name=op.f('fk_fu_submissions_requirement_id_fu_requirements')),
    sa.ForeignKeyConstraint(['stamped_copy_file_id'], ['attachments.id'], name=op.f('fk_fu_submissions_stamped_copy_file_id_attachments')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_fu_submissions_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fu_submissions')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_fu_submissions_project_id'))
    )
    op.create_index(op.f('ix_fu_submissions_project_id'), 'fu_submissions', ['project_id'], unique=False)
    op.create_index(op.f('ix_fu_submissions_requirement_id'), 'fu_submissions', ['requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fu_submissions_requirement_id'), table_name='fu_submissions')
    op.drop_index(op.f('ix_fu_submissions_project_id'), table_name='fu_submissions')
    op.drop_table('fu_submissions')
    op.drop_index(op.f('ix_fu_packs_requirement_id'), table_name='fu_packs')
    op.drop_index(op.f('ix_fu_packs_project_id'), table_name='fu_packs')
    op.drop_table('fu_packs')
    op.drop_index(op.f('ix_fu_lesson_links_lesson_id'), table_name='fu_lesson_links')
    op.drop_table('fu_lesson_links')
    op.drop_index(op.f('ix_fu_effectiveness_checks_project_id'), table_name='fu_effectiveness_checks')
    op.drop_table('fu_effectiveness_checks')
    op.drop_index(op.f('ix_fu_distribution_items_project_id'), table_name='fu_distribution_items')
    op.drop_index(op.f('ix_fu_distribution_items_lesson_id'), table_name='fu_distribution_items')
    op.drop_table('fu_distribution_items')
    op.drop_index(op.f('ix_fu_requirements_incident_id'), table_name='fu_requirements')
    op.drop_index('ix_fu_requirement_project_due', table_name='fu_requirements')
    op.drop_table('fu_requirements')
    op.drop_index(op.f('ix_fu_lessons_incident_id'), table_name='fu_lessons')
    op.drop_table('fu_lessons')
    op.drop_index(op.f('ix_fu_incident_clocks_project_id'), table_name='fu_incident_clocks')
    op.drop_table('fu_incident_clocks')
    op.drop_table('project_followup_settings')
    op.drop_index(op.f('ix_fu_rules_project_id'), table_name='fu_rules')
    op.drop_table('fu_rules')
    # ### end Alembic commands ###
