"""phase3 ptw

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-08 00:56:36.860365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_detectors',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('detector_no', sa.String(length=30), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('make_model', sa.String(length=80), nullable=False),
    sa.Column('serial', sa.String(length=40), nullable=False),
    sa.Column('sensors', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('lel_reference_gas', sa.Enum('methane', 'pentane', 'propane', 'hydrogen', name='lelreferencegas', native_enum=False, length=40), nullable=True),
    sa.Column('calibrated_on', sa.Date(), nullable=False),
    sa.Column('calibration_cert_ref', sa.String(length=40), nullable=False),
    sa.Column('certificate_due_on', sa.Date(), nullable=True),
    sa.Column('calibration_due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('in_service', 'quarantined', 'retired', name='detectorstatus', native_enum=False, length=40), nullable=False),
    sa.Column('quarantine_reason', sa.Enum('bump_test_failed', 'calibration_overdue', name='quarantinereason', native_enum=False, length=40), nullable=True),
    sa.Column('quarantined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_reason', sa.String(length=300), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_gas_detectors_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_gas_detectors_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_gas_detectors_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_gas_detectors_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gas_detectors')),
    sa.UniqueConstraint('detector_no', name=op.f('uq_gas_detectors_detector_no')),
    sa.UniqueConstraint('project_id', 'serial', name=op.f('uq_gas_detectors_project_id'))
    )
    op.create_index(op.f('ix_gas_detectors_project_id'), 'gas_detectors', ['project_id'], unique=False)
    op.create_table('permit_type_configs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('general', 'hot_work', 'confined_space', 'work_at_height', 'excavation', 'electrical_isolation', 'lifting', 'radiography', 'airside_works', name='permittype', native_enum=False, length=40), nullable=False),
    sa.Column('extra_pre_issue', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('extra_closure', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('extra_hazards', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('extra_crew_hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extra_equipment_hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_permit_type_configs_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_permit_type_configs_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('project_id', 'type', name=op.f('pk_permit_type_configs'))
    )
    op.create_table('project_ptw_settings',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('ptw_shift_max_hours', sa.Integer(), nullable=False),
    sa.Column('issue_to_start_max_minutes', sa.Integer(), nullable=False),
    sa.Column('max_active_permits_per_receiver', sa.Integer(), nullable=False),
    sa.Column('type_max_duration_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gas_pre_start_validity_minutes', sa.Integer(), nullable=False),
    sa.Column('gas_retest_interval_minutes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gas_break_retest_minutes', sa.Integer(), nullable=False),
    sa.Column('gas_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detector_calibration_interval_days', sa.Integer(), nullable=False),
    sa.Column('fire_watch_post_minutes', sa.Integer(), nullable=False),
    sa.Column('hw_combustible_clearance_m', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('hw_extinguisher_max_m', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('airside_hotwork_separation_m', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('wah_permit_threshold_m', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('wah_rescue_max_minutes', sa.Integer(), nullable=False),
    sa.Column('cse_rescue_max_minutes', sa.Integer(), nullable=False),
    sa.Column('cse_heat_control_temp_c', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('ex_permit_depth_m', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('ex_protective_system_depth_m', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('ex_pe_design_depth_m', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('ex_spoil_setback_m', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('ex_egress_max_m', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('ex_hand_dig_distance_m', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('critical_lift_capacity_pct', sa.Integer(), nullable=False),
    sa.Column('critical_lift_weight_t', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('lift_wind_limit_ms', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('man_basket_wind_limit_ms', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('rg_barrier_limit_usv_h', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('drop_zone_radius_m', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('vertical_separation_m', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('midday_ban_period', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('midday_ban_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('midday_ban_prewarn_minutes', sa.Integer(), nullable=False),
    sa.Column('jsa_review_months', sa.Integer(), nullable=False),
    sa.Column('long_term_isolation_days', sa.Integer(), nullable=False),
    sa.Column('appointment_max_months', sa.Integer(), nullable=False),
    sa.Column('ptw_audit_min_per_week', sa.Integer(), nullable=False),
    sa.Column('ptw_audit_warning_pct', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('ptw_critical_findings_warning', sa.Integer(), nullable=False),
    sa.Column('ptw_closure_warning_pct', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('step_up_reauth_minutes', sa.Integer(), nullable=False),
    sa.Column('ptw_retention_years', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_ptw_settings_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_project_ptw_settings_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_ptw_settings'))
    )
    op.create_table('simops_rules',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=10), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('type_a', sa.Enum('any', 'general', 'hot_work', 'confined_space', 'work_at_height', 'excavation', 'electrical_isolation', 'lifting', 'radiography', 'airside_works', 'flammables_in_use', 'gas_test_required', 'lifting_or_excavating_plant', 'combustion_engine_plant', 'energized_electrical', 'crane', 'other_contractor_movement_area', name='simopstypeselector', native_enum=False, length=40), nullable=False),
    sa.Column('type_b', sa.Enum('any', 'general', 'hot_work', 'confined_space', 'work_at_height', 'excavation', 'electrical_isolation', 'lifting', 'radiography', 'airside_works', 'flammables_in_use', 'gas_test_required', 'lifting_or_excavating_plant', 'combustion_engine_plant', 'energized_electrical', 'crane', 'other_contractor_movement_area', name='simopstypeselector', native_enum=False, length=40), nullable=False),
    sa.Column('condition', sa.Enum('within_barrier', 'within_threshold', 'within_combustible_clearance', 'within_exclusion_radius', 'within_slew_radius', 'above_within_drop_zone', 'hot_work_above_within_clearance', 'within_surcharge_zone', 'same_zone', 'slew_overlap', name='simopscondition', native_enum=False, length=40), nullable=False),
    sa.Column('threshold_m', sa.Numeric(precision=7, scale=1), nullable=True),
    sa.Column('result', sa.Enum('prohibited', 'conditional', 'allowed', name='simopsresult', native_enum=False, length=40), nullable=False),
    sa.Column('required_controls_en', sa.String(length=1000), nullable=True),
    sa.Column('required_controls_ar', sa.String(length=1000), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_simops_rules_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_simops_rules_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_simops_rules_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simops_rules')),
    sa.UniqueConstraint('project_id', 'rule_code', name=op.f('uq_simops_rules_project_id'))
    )
    op.create_index(op.f('ix_simops_rules_project_id'), 'simops_rules', ['project_id'], unique=False)
    op.create_table('gas_bump_tests',
    sa.Column('detector_id', sa.Uuid(), nullable=False),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.Enum('pass', 'fail', name='bumptestresult', native_enum=False, length=40), nullable=False),
    sa.Column('sensors_responded', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('tested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('tested_by_worker_id', sa.Uuid(), nullable=True),
    sa.Column('gas_cylinder_lot', sa.String(length=40), nullable=False),
    sa.Column('gas_cylinder_expiry', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['detector_id'], ['gas_detectors.id'], name=op.f('fk_gas_bump_tests_detector_id_gas_detectors')),
    sa.ForeignKeyConstraint(['tested_by_user_id'], ['users.id'], name=op.f('fk_gas_bump_tests_tested_by_user_id_users')),
    sa.ForeignKeyConstraint(['tested_by_worker_id'], ['workers.id'], name=op.f('fk_gas_bump_tests_tested_by_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gas_bump_tests'))
    )
    op.create_index('ix_bump_detector_time', 'gas_bump_tests', ['detector_id', 'tested_at'], unique=False)
    op.create_table('permits',
    sa.Column('permit_no', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('zone_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('location_desc', sa.String(length=200), nullable=False),
    sa.Column('grid_x_m', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('grid_y_m', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('level_code', sa.String(length=10), nullable=True),
    sa.Column('elevation_m', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('work_types', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('primary_type', sa.Enum('general', 'hot_work', 'confined_space', 'work_at_height', 'excavation', 'electrical_isolation', 'lifting', 'radiography', 'airside_works', name='permittype', native_enum=False, length=40), nullable=False),
    sa.Column('high_risk', sa.Boolean(), nullable=False),
    sa.Column('critical_lift', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('scope_en', sa.String(length=1000), nullable=False),
    sa.Column('scope_ar', sa.String(length=1000), nullable=True),
    sa.Column('exposure', sa.Enum('outdoor_direct_sun', 'outdoor_shaded', 'indoor', name='exposure', native_enum=False, length=40), nullable=False),
    sa.Column('flammables_in_use', sa.Boolean(), nullable=False),
    sa.Column('combustion_engine_plant', sa.Boolean(), nullable=False),
    sa.Column('valid_from_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('windows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('receiver_user_id', sa.Uuid(), nullable=False),
    sa.Column('area_authority_user_id', sa.Uuid(), nullable=True),
    sa.Column('issuer_user_id', sa.Uuid(), nullable=True),
    sa.Column('hse_reviewer_user_id', sa.Uuid(), nullable=True),
    sa.Column('supervisor_worker_id', sa.Uuid(), nullable=True),
    sa.Column('jsa_id', sa.UUID(), nullable=True),
    sa.Column('linked_wap_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('linked_obs_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('isolation_cert_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('conditions_en', sa.String(length=1000), nullable=True),
    sa.Column('conditions_ar', sa.String(length=1000), nullable=True),
    sa.Column('copied_conditions', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('emergency_info', sa.String(length=300), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checklists', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('area_review', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hse_review', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'requested', 'reviewed', 'approved', 'issued', 'active', 'suspended', 'closed', 'cancelled', 'expired', name='permitstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.Enum('shift_end', 'midday_ban', 'shift_lapsed', 'gas_test_failed', 'gas_retest_overdue', 'gas_alarm', 'wap_suspended', 'ops_suspension', 'notam_not_in_effect', 'obs_not_active', 'simops_conflict', 'key_role_ineligible', 'hook_not_met', 'wind_limit', 'weather', 'audit_critical', 'stop_work', 'emergency', 'contractor_suspended', 'contractor_blacklisted', 'isolation_breach', 'rejected', 'not_required', 'duplicate', 'other', name='statusreason', native_enum=False, length=40), nullable=True),
    sa.Column('status_detail', sa.String(length=500), nullable=True),
    sa.Column('returned_comment', sa.String(length=500), nullable=True),
    sa.Column('current_shift_id', sa.UUID(), nullable=True),
    sa.Column('first_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receiver_acceptance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('closure_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('post_expiry_check', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fod_check', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_return', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('copied_from_id', sa.UUID(), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_authority_user_id'], ['users.id'], name=op.f('fk_permits_area_authority_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_permits_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_permits_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['hse_reviewer_user_id'], ['users.id'], name=op.f('fk_permits_hse_reviewer_user_id_users')),
    sa.ForeignKeyConstraint(['issuer_user_id'], ['users.id'], name=op.f('fk_permits_issuer_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_permits_project_id_projects')),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], name=op.f('fk_permits_receiver_user_id_users')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_permits_site_id_sites')),
    sa.ForeignKeyConstraint(['supervisor_worker_id'], ['workers.id'], name=op.f('fk_permits_supervisor_worker_id_workers')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_permits_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permits')),
    sa.UniqueConstraint('permit_no', name=op.f('uq_permits_permit_no')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_permits_project_id'))
    )
    op.create_index('ix_permit_project_status', 'permits', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_permits_engagement_id'), 'permits', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_permits_receiver_user_id'), 'permits', ['receiver_user_id'], unique=False)
    op.create_table('ptw_appointments',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('appointment_no', sa.String(length=40), nullable=False),
    sa.Column('function', sa.Enum('issuer', 'area_authority', 'isolation_authority', 'gas_tester', 'authorised_person', name='appointmentfunction', native_enum=False, length=40), nullable=False),
    sa.Column('discipline', sa.Enum('electrical_lv', 'electrical_hv', 'mechanical_process', 'lifting_appointed_person', 'lift_supervisor', 'excavation_competent_person', 'fall_protection_competent_person', 'radiation_protection_officer', 'cse_rescue_lead', name='appointmentdiscipline', native_enum=False, length=40), nullable=True),
    sa.Column('holder_user_id', sa.Uuid(), nullable=True),
    sa.Column('holder_worker_id', sa.Uuid(), nullable=True),
    sa.Column('permit_types', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('site_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('zone_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('basis', sa.String(length=300), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('appointed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'revoked', 'expired', name='appointmentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointed_by_user_id'], ['users.id'], name=op.f('fk_ptw_appointments_appointed_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_ptw_appointments_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['holder_user_id'], ['users.id'], name=op.f('fk_ptw_appointments_holder_user_id_users')),
    sa.ForeignKeyConstraint(['holder_worker_id'], ['workers.id'], name=op.f('fk_ptw_appointments_holder_worker_id_workers')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ptw_appointments_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_ptw_appointments_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ptw_appointments')),
    sa.UniqueConstraint('appointment_no', name=op.f('uq_ptw_appointments_appointment_no')),
    sa.UniqueConstraint('project_id', 'seq', name=op.f('uq_ptw_appointments_project_id'))
    )
    op.create_index(op.f('ix_ptw_appointments_holder_user_id'), 'ptw_appointments', ['holder_user_id'], unique=False)
    op.create_index(op.f('ix_ptw_appointments_holder_worker_id'), 'ptw_appointments', ['holder_worker_id'], unique=False)
    op.create_index(op.f('ix_ptw_appointments_project_id'), 'ptw_appointments', ['project_id'], unique=False)
    op.create_table('ptw_locks',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('lock_no', sa.String(length=20), nullable=False),
    sa.Column('lock_type', sa.Enum('isolation_lock', 'personal_lock', 'lockbox', name='locktype', native_enum=False, length=40), nullable=False),
    sa.Column('holder_worker_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('available', 'applied', 'lost', 'cut', 'retired', name='lockstatus', native_enum=False, length=40), nullable=False),
    sa.Column('applied_on', sa.String(length=80), nullable=True),
    sa.Column('lost_detail', sa.String(length=300), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_ptw_locks_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['holder_worker_id'], ['workers.id'], name=op.f('fk_ptw_locks_holder_worker_id_workers')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ptw_locks_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_ptw_locks_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ptw_locks')),
    sa.UniqueConstraint('project_id', 'lock_no', name=op.f('uq_ptw_locks_project_id'))
    )
    op.create_index(op.f('ix_ptw_locks_project_id'), 'ptw_locks', ['project_id'], unique=False)
    op.create_table('zone_adjacencies',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('zone_a_id', sa.Uuid(), nullable=False),
    sa.Column('zone_b_id', sa.Uuid(), nullable=False),
    sa.Column('distance_m', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('vertical_relation', sa.Enum('none', 'a_above_b', 'b_above_a', 'overlapping', name='verticalrelation', native_enum=False, length=40), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_zone_adjacencies_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_zone_adjacencies_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_zone_adjacencies_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['zone_a_id'], ['zones.id'], name=op.f('fk_zone_adjacencies_zone_a_id_zones')),
    sa.ForeignKeyConstraint(['zone_b_id'], ['zones.id'], name=op.f('fk_zone_adjacencies_zone_b_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zone_adjacencies')),
    sa.UniqueConstraint('zone_a_id', 'zone_b_id', name=op.f('uq_zone_adjacencies_zone_a_id'))
    )
    op.create_index(op.f('ix_zone_adjacencies_project_id'), 'zone_adjacencies', ['project_id'], unique=False)
    op.create_table('zone_ptw_profiles',
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('permit_required_all_work', sa.Boolean(), nullable=False),
    sa.Column('gas_test_zone', sa.Boolean(), nullable=False),
    sa.Column('hazardous_area_class', sa.Enum('none', 'zone_0', 'zone_1', 'zone_2', name='hazardousareaclass', native_enum=False, length=40), nullable=False),
    sa.Column('hazardous_area_note', sa.String(length=200), nullable=True),
    sa.Column('default_exposure', sa.Enum('outdoor_direct_sun', 'outdoor_shaded', 'indoor', name='exposure', native_enum=False, length=40), nullable=False),
    sa.Column('fire_protection_present', sa.Boolean(), nullable=False),
    sa.Column('level_datum_note', sa.String(length=100), nullable=True),
    sa.Column('default_area_authority_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_zone_ptw_profiles_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_zone_ptw_profiles_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_zone_ptw_profiles_zone_id_zones')),
    sa.PrimaryKeyConstraint('zone_id', name=op.f('pk_zone_ptw_profiles'))
    )
    op.create_index(op.f('ix_zone_ptw_profiles_project_id'), 'zone_ptw_profiles', ['project_id'], unique=False)
    op.create_table('gas_tests',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('permit_id', sa.Uuid(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('test_no', sa.String(length=60), nullable=False),
    sa.Column('test_type', sa.Enum('pre_issue', 'pre_entry', 'periodic', 'post_break', 'revalidation', 'post_alarm', name='gastesttype', native_enum=False, length=40), nullable=False),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tester_appointment_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('tester_signature_attachment_id', sa.UUID(), nullable=True),
    sa.Column('detector_id', sa.Uuid(), nullable=False),
    sa.Column('readings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('internal_temp_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('applicable_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.Enum('pass', 'fail', name='gastestresult', native_enum=False, length=40), nullable=False),
    sa.Column('fail_codes', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('valid_for_start_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('superseded_reason', sa.String(length=300), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['detector_id'], ['gas_detectors.id'], name=op.f('fk_gas_tests_detector_id_gas_detectors')),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], name=op.f('fk_gas_tests_permit_id_permits')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_gas_tests_project_id_projects')),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_gas_tests_recorded_by_user_id_users')),
    sa.ForeignKeyConstraint(['tester_appointment_id'], ['ptw_appointments.id'], name=op.f('fk_gas_tests_tester_appointment_id_ptw_appointments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gas_tests')),
    sa.UniqueConstraint('test_no', name=op.f('uq_gas_tests_test_no'))
    )
    op.create_index('ix_gas_test_permit_time', 'gas_tests', ['permit_id', 'tested_at'], unique=False)
    op.create_index(op.f('ix_gas_tests_project_id'), 'gas_tests', ['project_id'], unique=False)
    op.create_table('isolation_certificates',
    sa.Column('iso_no', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('equipment_desc', sa.String(length=200), nullable=False),
    sa.Column('energy_types', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('hv', sa.Boolean(), nullable=False),
    sa.Column('isolation_authority_user_id', sa.Uuid(), nullable=False),
    sa.Column('lockbox_id', sa.Uuid(), nullable=False),
    sa.Column('switching_programme_ref', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('planned', 'isolated', 'verified', 'deisolation_requested', 'deisolated', 'cancelled', name='isolationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('isolated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deisolation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deisolation_authorised_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('deisolation_authorised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deisolated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviews', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_isolation_certificates_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['deisolation_authorised_by_user_id'], ['users.id'], name=op.f('fk_isolation_certificates_deisolation_authorised_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_isolation_certificates_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['isolation_authority_user_id'], ['users.id'], name=op.f('fk_isolation_certificates_isolation_authority_user_id_users')),
    sa.ForeignKeyConstraint(['lockbox_id'], ['ptw_locks.id'], name=op.f('fk_isolation_certificates_lockbox_id_ptw_locks')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_isolation_certificates_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_isolation_certificates_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_isolation_certificates')),
    sa.UniqueConstraint('iso_no', name=op.f('uq_isolation_certificates_iso_no')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_isolation_certificates_project_id'))
    )
    op.create_index(op.f('ix_isolation_certificates_project_id'), 'isolation_certificates', ['project_id'], unique=False)
    op.create_table('jsas',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('jsa_no', sa.String(length=40), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('permit_id', sa.Uuid(), nullable=True),
    sa.Column('work_types', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('title_en', sa.String(length=150), nullable=False),
    sa.Column('title_ar', sa.String(length=150), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('residual_acceptances', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('crew_briefings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_due_on', sa.Date(), nullable=True),
    sa.Column('returned_comment', sa.String(length=500), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'superseded', 'review_due', name='jsastatus', native_enum=False, length=40), nullable=False),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_jsas_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_jsas_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_jsas_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], name=op.f('fk_jsas_permit_id_permits')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_jsas_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_jsas_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jsas'))
    )
    op.create_index('ix_jsa_project_template', 'jsas', ['project_id', 'is_template'], unique=False)
    op.create_index(op.f('ix_jsas_jsa_no'), 'jsas', ['jsa_no'], unique=False)
    op.create_index(op.f('ix_jsas_permit_id'), 'jsas', ['permit_id'], unique=False)
    op.create_table('permit_crew',
    sa.Column('permit_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('crew_role', sa.Enum('worker', 'supervisor', 'hot_work_operative', 'fire_watch', 'entrant', 'standby_person', 'rescue_lead', 'rescue_member', 'gas_tester', 'crane_operator', 'rigger', 'signaller', 'lift_supervisor', 'electrician', 'competent_person', 'radiographer', 'rpo', 'driver', 'banksman', 'escort', name='ptwcrewrole', native_enum=False, length=40), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('escort_worker_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('listed', 'excluded', 'removed', name='crewlinestatus', native_enum=False, length=40), nullable=False),
    sa.Column('excluded_reason', sa.String(length=60), nullable=True),
    sa.Column('eligible', sa.Boolean(), nullable=True),
    sa.Column('eligibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['ptw_appointments.id'], name=op.f('fk_permit_crew_appointment_id_ptw_appointments')),
    sa.ForeignKeyConstraint(['escort_worker_id'], ['workers.id'], name=op.f('fk_permit_crew_escort_worker_id_workers')),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], name=op.f('fk_permit_crew_permit_id_permits')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_permit_crew_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permit_crew'))
    )
    op.create_index(op.f('ix_permit_crew_permit_id'), 'permit_crew', ['permit_id'], unique=False)
    op.create_index('ix_permit_crew_worker', 'permit_crew', ['worker_id'], unique=False)
    op.create_table('permit_documents',
    sa.Column('permit_id', sa.Uuid(), nullable=False),
    sa.Column('doc_type', sa.Enum('method_statement', 'risk_assessment', 'lift_plan', 'critical_lift_plan', 'rescue_plan', 'excavation_plan', 'pe_design', 'utility_drawing', 'switching_programme', 'radiation_protection_plan', 'nrrc_licence', 'fire_impairment_notice', 'other', name='documenttype', native_enum=False, length=40), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('revision', sa.String(length=6), nullable=False),
    sa.Column('attachment_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_text', sa.String(length=120), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('added_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], name=op.f('fk_permit_documents_added_by_user_id_users')),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], name=op.f('fk_permit_documents_permit_id_permits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permit_documents'))
    )
    op.create_index(op.f('ix_permit_documents_permit_id'), 'permit_documents', ['permit_id'], unique=False)
    op.create_table('permit_equipment',
    sa.Column('permit_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('tower_crane', 'mobile_crane', 'crawler_crane', 'lifting_accessory', 'spreader_beam', 'mewp', 'man_basket', 'mast_climber', 'bmu', 'scaffold', 'welding_set', 'gas_cylinder_set', 'ventilation_fan', 'tripod_winch', 'voltage_tester', 'radiography_projector', 'survey_meter', 'other', name='equipmentcategory', native_enum=False, length=40), nullable=True),
    sa.Column('tag', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('max_working_height_m', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('use', sa.Enum('lifting_appliance', 'lifting_accessory', 'access_equipment', 'welding_set', 'gas_detector', 'ventilation', 'rescue_equipment', 'excavating_plant', 'radiography_source', 'other', name='equipmentuse', native_enum=False, length=40), nullable=False),
    sa.Column('hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], name=op.f('fk_permit_equipment_permit_id_permits')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_permit_equipment_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permit_equipment'))
    )
    op.create_index(op.f('ix_permit_equipment_permit_id'), 'permit_equipment', ['permit_id'], unique=False)
    op.create_table('permit_exemptions',
    sa.Column('permit_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('midday_ban', 'energized_work', 'fire_impairment', 'lift_capacity_over_90', name='exemptionkind', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('requested', 'granted', 'refused', 'withdrawn', name='exemptionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('midday_reason', sa.Enum('emergency_repair', 'exempt_activity_mhrsd', 'shaded_and_cooled_workplace', name='middayexemptionreason', native_enum=False, length=40), nullable=True),
    sa.Column('reason_text', sa.String(length=500), nullable=False),
    sa.Column('heat_controls_text', sa.String(length=1000), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_permit_exemptions_decided_by_user_id_users')),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], name=op.f('fk_permit_exemptions_permit_id_permits')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_permit_exemptions_project_id_projects')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_permit_exemptions_requested_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permit_exemptions'))
    )
    op.create_index(op.f('ix_permit_exemptions_permit_id'), 'permit_exemptions', ['permit_id'], unique=False)
    op.create_table('permit_records',
    sa.Column('permit_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], name=op.f('fk_permit_records_permit_id_permits')),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_permit_records_recorded_by_user_id_users')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_permit_records_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permit_records'))
    )
    op.create_index('ix_permit_record_kind', 'permit_records', ['permit_id', 'kind'], unique=False)
    op.create_table('permit_shifts',
    sa.Column('permit_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('shift_no', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receiver_user_id', sa.Uuid(), nullable=False),
    sa.Column('issuer_user_id', sa.Uuid(), nullable=False),
    sa.Column('gas_test_id', sa.UUID(), nullable=True),
    sa.Column('ambient_temp_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('crew_present', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('briefed', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('pauses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_type', sa.Enum('handover', 'shift_end', 'suspended', 'lapsed', 'closed', 'expired', name='shiftendtype', native_enum=False, length=40), nullable=True),
    sa.Column('gas_required', sa.Boolean(), nullable=False),
    sa.Column('gas_compliant', sa.Boolean(), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_user_id'], ['users.id'], name=op.f('fk_permit_shifts_issuer_user_id_users')),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], name=op.f('fk_permit_shifts_permit_id_permits')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_permit_shifts_project_id_projects')),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], name=op.f('fk_permit_shifts_receiver_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permit_shifts')),
    sa.UniqueConstraint('permit_id', 'shift_no', name=op.f('uq_permit_shifts_permit_id'))
    )
    op.create_index('ix_permit_shift_started', 'permit_shifts', ['started_at'], unique=False)
    op.create_index(op.f('ix_permit_shifts_permit_id'), 'permit_shifts', ['permit_id'], unique=False)
    op.create_table('permit_signatures',
    sa.Column('permit_id', sa.Uuid(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.Enum('request', 'review', 'hse_review', 'approve', 'issue', 'accept', 'revalidate', 'resume', 'close', 'cancel', 'handover_accept', 'residual_acceptance', 'simops_coordination', 'gas_test', name='signaturepurpose', native_enum=False, length=40), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('role_label', sa.String(length=40), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('permit_hash', sa.String(length=64), nullable=False),
    sa.Column('co_signed_on_device_of_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['co_signed_on_device_of_user_id'], ['users.id'], name=op.f('fk_permit_signatures_co_signed_on_device_of_user_id_users')),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], name=op.f('fk_permit_signatures_permit_id_permits')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_permit_signatures_user_id_users')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_permit_signatures_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permit_signatures'))
    )
    op.create_index(op.f('ix_permit_signatures_entity_id'), 'permit_signatures', ['entity_id'], unique=False)
    op.create_index(op.f('ix_permit_signatures_permit_id'), 'permit_signatures', ['permit_id'], unique=False)
    op.create_table('permit_suspensions',
    sa.Column('permit_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Enum('shift_end', 'midday_ban', 'shift_lapsed', 'gas_test_failed', 'gas_retest_overdue', 'gas_alarm', 'wap_suspended', 'ops_suspension', 'notam_not_in_effect', 'obs_not_active', 'simops_conflict', 'key_role_ineligible', 'hook_not_met', 'wind_limit', 'weather', 'audit_critical', 'stop_work', 'emergency', 'contractor_suspended', 'contractor_blacklisted', 'isolation_breach', 'rejected', 'not_required', 'duplicate', 'other', name='statusreason', native_enum=False, length=40), nullable=False),
    sa.Column('routine', sa.Boolean(), nullable=False),
    sa.Column('raised_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('auto_source_ref', sa.String(length=60), nullable=True),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resumed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resume_gas_test_id', sa.UUID(), nullable=True),
    sa.Column('cause_cleared_text', sa.String(length=500), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], name=op.f('fk_permit_suspensions_permit_id_permits')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_permit_suspensions_project_id_projects')),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], name=op.f('fk_permit_suspensions_raised_by_user_id_users')),
    sa.ForeignKeyConstraint(['resumed_by_user_id'], ['users.id'], name=op.f('fk_permit_suspensions_resumed_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permit_suspensions'))
    )
    op.create_index('ix_permit_susp_project_time', 'permit_suspensions', ['project_id', 'suspended_at'], unique=False)
    op.create_index(op.f('ix_permit_suspensions_permit_id'), 'permit_suspensions', ['permit_id'], unique=False)
    op.create_table('ptw_audits',
    sa.Column('audit_no', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('audit_type', sa.Enum('field', 'document_review', 'unpermitted_work', name='ptwaudittype', native_enum=False, length=40), nullable=False),
    sa.Column('permit_id', sa.Uuid(), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('auditor_user_id', sa.Uuid(), nullable=False),
    sa.Column('audited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applicable_count', sa.Integer(), nullable=False),
    sa.Column('compliant_count', sa.Integer(), nullable=False),
    sa.Column('score_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('stop_work_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unpermitted_work_desc', sa.String(length=1000), nullable=True),
    sa.Column('permit_suspended', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'completed', 'locked', name='ptwauditstatus', native_enum=False, length=40), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edit_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auditor_user_id'], ['users.id'], name=op.f('fk_ptw_audits_auditor_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_ptw_audits_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_ptw_audits_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], name=op.f('fk_ptw_audits_permit_id_permits')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ptw_audits_project_id_projects')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_ptw_audits_site_id_sites')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_ptw_audits_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_ptw_audits_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ptw_audits')),
    sa.UniqueConstraint('audit_no', name=op.f('uq_ptw_audits_audit_no')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_ptw_audits_project_id'))
    )
    op.create_index('ix_ptw_audit_project_time', 'ptw_audits', ['project_id', 'audited_at'], unique=False)
    op.create_index(op.f('ix_ptw_audits_permit_id'), 'ptw_audits', ['permit_id'], unique=False)
    op.create_table('simops_conflicts',
    sa.Column('conflict_no', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('permit_a_id', sa.Uuid(), nullable=False),
    sa.Column('permit_b_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=10), nullable=False),
    sa.Column('distance_m', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('distance_basis', sa.Enum('grid', 'same_zone', 'adjacency', name='distancebasis', native_enum=False, length=40), nullable=False),
    sa.Column('vertical_note', sa.String(length=120), nullable=True),
    sa.Column('overlap_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overlap_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Enum('prohibited', 'conditional', 'allowed', name='simopsresult', native_enum=False, length=40), nullable=False),
    sa.Column('required_controls_en', sa.String(length=1000), nullable=True),
    sa.Column('required_controls_ar', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('open', 'coordinated', 'resolved_by_change', 'closed', name='simopsconflictstatus', native_enum=False, length=40), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('coordinated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permit_a_id'], ['permits.id'], name=op.f('fk_simops_conflicts_permit_a_id_permits')),
    sa.ForeignKeyConstraint(['permit_b_id'], ['permits.id'], name=op.f('fk_simops_conflicts_permit_b_id_permits')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_simops_conflicts_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simops_conflicts')),
    sa.UniqueConstraint('conflict_no', name=op.f('uq_simops_conflicts_conflict_no')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_simops_conflicts_project_id'))
    )
    op.create_index('ix_simops_pair', 'simops_conflicts', ['permit_a_id', 'permit_b_id', 'rule_code'], unique=False)
    op.create_table('isolation_points',
    sa.Column('certificate_id', sa.Uuid(), nullable=False),
    sa.Column('point_no', sa.Integer(), nullable=False),
    sa.Column('energy_type', sa.Enum('electrical', 'mechanical', 'hydraulic', 'pneumatic', 'process_fluid', 'thermal', 'gravity', 'stored_spring', 'chemical', 'radiation', name='energytype', native_enum=False, length=40), nullable=False),
    sa.Column('device_tag', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('method', sa.Enum('breaker_racked_out', 'fuse_removed', 'isolator_open_locked', 'cable_disconnected', 'earth_applied', 'valve_closed_locked', 'spade_blind', 'double_block_bleed', 'disconnect_removed_spool', 'mechanical_pin_block', 'bleed_vent_drain', 'other', name='isolationmethod', native_enum=False, length=40), nullable=False),
    sa.Column('isolation_lock_id', sa.Uuid(), nullable=True),
    sa.Column('tag_no', sa.String(length=20), nullable=True),
    sa.Column('applied_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('verified_by_worker_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_method', sa.Enum('try_out_start_attempt', 'test_for_dead', 'pressure_gauge_zero', 'visual_air_gap', 'other', name='verificationmethod', native_enum=False, length=40), nullable=True),
    sa.Column('removed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_user_id'], ['users.id'], name=op.f('fk_isolation_points_applied_by_user_id_users')),
    sa.ForeignKeyConstraint(['certificate_id'], ['isolation_certificates.id'], name=op.f('fk_isolation_points_certificate_id_isolation_certificates')),
    sa.ForeignKeyConstraint(['isolation_lock_id'], ['ptw_locks.id'], name=op.f('fk_isolation_points_isolation_lock_id_ptw_locks')),
    sa.ForeignKeyConstraint(['removed_by_user_id'], ['users.id'], name=op.f('fk_isolation_points_removed_by_user_id_users')),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_isolation_points_verified_by_user_id_users')),
    sa.ForeignKeyConstraint(['verified_by_worker_id'], ['workers.id'], name=op.f('fk_isolation_points_verified_by_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_isolation_points')),
    sa.UniqueConstraint('certificate_id', 'point_no', name=op.f('uq_isolation_points_certificate_id'))
    )
    op.create_index(op.f('ix_isolation_points_certificate_id'), 'isolation_points', ['certificate_id'], unique=False)
    op.create_table('permit_handovers',
    sa.Column('permit_id', sa.Uuid(), nullable=False),
    sa.Column('from_shift_id', sa.Uuid(), nullable=False),
    sa.Column('from_receiver_user_id', sa.Uuid(), nullable=False),
    sa.Column('to_receiver_user_id', sa.Uuid(), nullable=False),
    sa.Column('to_issuer_user_id', sa.Uuid(), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receiver_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issuer_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('initiated', 'accepted', 'lapsed', name='handoverstatus', native_enum=False, length=40), nullable=False),
    sa.Column('notes_en', sa.String(length=500), nullable=False),
    sa.Column('notes_ar', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['from_receiver_user_id'], ['users.id'], name=op.f('fk_permit_handovers_from_receiver_user_id_users')),
    sa.ForeignKeyConstraint(['from_shift_id'], ['permit_shifts.id'], name=op.f('fk_permit_handovers_from_shift_id_permit_shifts')),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], name=op.f('fk_permit_handovers_permit_id_permits')),
    sa.ForeignKeyConstraint(['to_issuer_user_id'], ['users.id'], name=op.f('fk_permit_handovers_to_issuer_user_id_users')),
    sa.ForeignKeyConstraint(['to_receiver_user_id'], ['users.id'], name=op.f('fk_permit_handovers_to_receiver_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permit_handovers'))
    )
    op.create_index(op.f('ix_permit_handovers_permit_id'), 'permit_handovers', ['permit_id'], unique=False)
    op.create_table('personal_lock_events',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('lock_id', sa.Uuid(), nullable=False),
    sa.Column('lockbox_id', sa.Uuid(), nullable=False),
    sa.Column('certificate_id', sa.Uuid(), nullable=True),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('permit_id', sa.Uuid(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by', sa.Enum('holder', 'cut', name='personallockremoval', native_enum=False, length=40), nullable=True),
    sa.Column('cut_record', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_user_id'], ['users.id'], name=op.f('fk_personal_lock_events_applied_by_user_id_users')),
    sa.ForeignKeyConstraint(['certificate_id'], ['isolation_certificates.id'], name=op.f('fk_personal_lock_events_certificate_id_isolation_certificates')),
    sa.ForeignKeyConstraint(['lock_id'], ['ptw_locks.id'], name=op.f('fk_personal_lock_events_lock_id_ptw_locks')),
    sa.ForeignKeyConstraint(['lockbox_id'], ['ptw_locks.id'], name=op.f('fk_personal_lock_events_lockbox_id_ptw_locks')),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], name=op.f('fk_personal_lock_events_permit_id_permits')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_personal_lock_events_project_id_projects')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_personal_lock_events_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_lock_events'))
    )
    op.create_index('ix_personal_lock_box', 'personal_lock_events', ['lockbox_id', 'removed_at'], unique=False)
    op.create_table('simops_coordinations',
    sa.Column('conflict_id', sa.Uuid(), nullable=False),
    sa.Column('agreed_controls_en', sa.String(length=1000), nullable=False),
    sa.Column('agreed_controls_ar', sa.String(length=1000), nullable=True),
    sa.Column('signatures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending_signatures', 'signed', 'expired', name='coordinationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conflict_id'], ['simops_conflicts.id'], name=op.f('fk_simops_coordinations_conflict_id_simops_conflicts')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_simops_coordinations_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simops_coordinations')),
    sa.UniqueConstraint('conflict_id', name=op.f('uq_simops_coordinations_conflict_id'))
    )
    op.add_column('investigations', sa.Column('ptw_ids', postgresql.ARRAY(sa.UUID()), nullable=False, server_default='{}'))
    op.add_column('user_sessions', sa.Column('last_authenticated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE user_sessions SET last_authenticated_at = created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'last_authenticated_at')
    op.drop_column('investigations', 'ptw_ids')
    op.drop_table('simops_coordinations')
    op.drop_index('ix_personal_lock_box', table_name='personal_lock_events')
    op.drop_table('personal_lock_events')
    op.drop_index(op.f('ix_permit_handovers_permit_id'), table_name='permit_handovers')
    op.drop_table('permit_handovers')
    op.drop_index(op.f('ix_isolation_points_certificate_id'), table_name='isolation_points')
    op.drop_table('isolation_points')
    op.drop_index('ix_simops_pair', table_name='simops_conflicts')
    op.drop_table('simops_conflicts')
    op.drop_index(op.f('ix_ptw_audits_permit_id'), table_name='ptw_audits')
    op.drop_index('ix_ptw_audit_project_time', table_name='ptw_audits')
    op.drop_table('ptw_audits')
    op.drop_index(op.f('ix_permit_suspensions_permit_id'), table_name='permit_suspensions')
    op.drop_index('ix_permit_susp_project_time', table_name='permit_suspensions')
    op.drop_table('permit_suspensions')
    op.drop_index(op.f('ix_permit_signatures_permit_id'), table_name='permit_signatures')
    op.drop_index(op.f('ix_permit_signatures_entity_id'), table_name='permit_signatures')
    op.drop_table('permit_signatures')
    op.drop_index(op.f('ix_permit_shifts_permit_id'), table_name='permit_shifts')
    op.drop_index('ix_permit_shift_started', table_name='permit_shifts')
    op.drop_table('permit_shifts')
    op.drop_index('ix_permit_record_kind', table_name='permit_records')
    op.drop_table('permit_records')
    op.drop_index(op.f('ix_permit_exemptions_permit_id'), table_name='permit_exemptions')
    op.drop_table('permit_exemptions')
    op.drop_index(op.f('ix_permit_equipment_permit_id'), table_name='permit_equipment')
    op.drop_table('permit_equipment')
    op.drop_index(op.f('ix_permit_documents_permit_id'), table_name='permit_documents')
    op.drop_table('permit_documents')
    op.drop_index('ix_permit_crew_worker', table_name='permit_crew')
    op.drop_index(op.f('ix_permit_crew_permit_id'), table_name='permit_crew')
    op.drop_table('permit_crew')
    op.drop_index(op.f('ix_jsas_permit_id'), table_name='jsas')
    op.drop_index(op.f('ix_jsas_jsa_no'), table_name='jsas')
    op.drop_index('ix_jsa_project_template', table_name='jsas')
    op.drop_table('jsas')
    op.drop_index(op.f('ix_isolation_certificates_project_id'), table_name='isolation_certificates')
    op.drop_table('isolation_certificates')
    op.drop_index(op.f('ix_gas_tests_project_id'), table_name='gas_tests')
    op.drop_index('ix_gas_test_permit_time', table_name='gas_tests')
    op.drop_table('gas_tests')
    op.drop_index(op.f('ix_zone_ptw_profiles_project_id'), table_name='zone_ptw_profiles')
    op.drop_table('zone_ptw_profiles')
    op.drop_index(op.f('ix_zone_adjacencies_project_id'), table_name='zone_adjacencies')
    op.drop_table('zone_adjacencies')
    op.drop_index(op.f('ix_ptw_locks_project_id'), table_name='ptw_locks')
    op.drop_table('ptw_locks')
    op.drop_index(op.f('ix_ptw_appointments_project_id'), table_name='ptw_appointments')
    op.drop_index(op.f('ix_ptw_appointments_holder_worker_id'), table_name='ptw_appointments')
    op.drop_index(op.f('ix_ptw_appointments_holder_user_id'), table_name='ptw_appointments')
    op.drop_table('ptw_appointments')
    op.drop_index(op.f('ix_permits_receiver_user_id'), table_name='permits')
    op.drop_index(op.f('ix_permits_engagement_id'), table_name='permits')
    op.drop_index('ix_permit_project_status', table_name='permits')
    op.drop_table('permits')
    op.drop_index('ix_bump_detector_time', table_name='gas_bump_tests')
    op.drop_table('gas_bump_tests')
    op.drop_index(op.f('ix_simops_rules_project_id'), table_name='simops_rules')
    op.drop_table('simops_rules')
    op.drop_table('project_ptw_settings')
    op.drop_table('permit_type_configs')
    op.drop_index(op.f('ix_gas_detectors_project_id'), table_name='gas_detectors')
    op.drop_table('gas_detectors')
    # ### end Alembic commands ###
