"""phase6d field assurance

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-09 14:44:35.108379

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | Sequence[str] | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checklist_templates",
        sa.Column("template_code", sa.String(length=8), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("inspection", "audit", name="templatekind", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column(
            "inspection_type",
            sa.Enum(
                "general_site",
                "scaffold",
                "lifting_equipment",
                "electrical",
                "excavation",
                "housekeeping",
                "fire_safety",
                "welfare",
                "airside_fod_walk",
                "plant_vehicle",
                "environmental",
                "ppe",
                "leadership_walk",
                name="inspectiontype",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column(
            "audit_type",
            sa.Enum(
                "contractor_hse",
                "system_iso45001",
                "client_requested",
                name="audittype",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("title_en", sa.String(length=150), nullable=False),
        sa.Column("title_ar", sa.String(length=150), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("zone_types", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("project_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("pass_mark_pct", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("review_due_on", sa.Date(), nullable=True),
        sa.Column("change_note", sa.String(length=500), nullable=True),
        sa.Column("authored_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("published_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "published",
                "superseded",
                "retired",
                name="versionstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.String(length=500), nullable=True),
        sa.Column("alerts_sent", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["authored_by_user_id"],
            ["users.id"],
            name=op.f("fk_checklist_templates_authored_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_checklist_templates_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["published_by_user_id"],
            ["users.id"],
            name=op.f("fk_checklist_templates_published_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_checklist_templates_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_templates")),
        sa.UniqueConstraint(
            "template_code", "version", name=op.f("uq_checklist_templates_template_code")
        ),
    )
    op.create_index(
        op.f("ix_checklist_templates_template_code"),
        "checklist_templates",
        ["template_code"],
        unique=False,
    )
    op.create_table(
        "project_field_settings",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("inspection_template_required_from", sa.Date(), nullable=True),
        sa.Column("toolbox_register_from", sa.Date(), nullable=True),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_field_settings_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_project_field_settings_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_project_field_settings")),
    )
    op.create_table(
        "toolbox_topics",
        sa.Column("topic_code", sa.String(length=10), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "work_at_height",
                "lifting",
                "excavation",
                "scaffolding",
                "electrical",
                "hot_work",
                "ppe",
                "housekeeping",
                "traffic_plant",
                "airside_fod_control",
                "airside_driving",
                "heat_stress",
                "confined_space",
                "manual_handling",
                "tools_equipment",
                "environmental",
                "fire_safety",
                "welfare",
                "permit_compliance",
                "behaviour_other",
                "general",
                "emergency",
                "health",
                name="topiccategory",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("title_en", sa.String(length=150), nullable=False),
        sa.Column("title_ar", sa.String(length=150), nullable=False),
        sa.Column("key_points_en", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("key_points_ar", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("translations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("linked_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("review_due_on", sa.Date(), nullable=True),
        sa.Column("authored_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("published_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "published",
                "superseded",
                "retired",
                name="versionstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.String(length=500), nullable=True),
        sa.Column("alerts_sent", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["authored_by_user_id"],
            ["users.id"],
            name=op.f("fk_toolbox_topics_authored_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_toolbox_topics_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["published_by_user_id"],
            ["users.id"],
            name=op.f("fk_toolbox_topics_published_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_toolbox_topics_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_toolbox_topics")),
        sa.UniqueConstraint("topic_code", "version", name=op.f("uq_toolbox_topics_topic_code")),
    )
    op.create_index(
        op.f("ix_toolbox_topics_topic_code"), "toolbox_topics", ["topic_code"], unique=False
    )
    op.create_table(
        "briefing_campaigns",
        sa.Column("campaign_no", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("topic_code", sa.String(length=10), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "incident",
                "lesson",
                "client_instruction",
                "regulatory",
                "seasonal",
                "audit_finding",
                name="campaignreason",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("reason_ref", sa.String(length=60), nullable=True),
        sa.Column("message_en", sa.String(length=1000), nullable=True),
        sa.Column("message_ar", sa.String(length=1000), nullable=True),
        sa.Column("site_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("pairs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("issued_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "issued",
                "closed",
                "cancelled",
                name="campaignstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.String(length=500), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("alerts_sent", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_briefing_campaigns_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["users.id"],
            name=op.f("fk_briefing_campaigns_issued_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_briefing_campaigns_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["toolbox_topics.id"],
            name=op.f("fk_briefing_campaigns_topic_id_toolbox_topics"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_briefing_campaigns_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_briefing_campaigns")),
        sa.UniqueConstraint("campaign_no", name=op.f("uq_briefing_campaigns_campaign_no")),
        sa.UniqueConstraint(
            "project_id", "year", "seq", name=op.f("uq_briefing_campaigns_project_id")
        ),
    )
    op.create_index(
        op.f("ix_briefing_campaigns_project_id"), "briefing_campaigns", ["project_id"], unique=False
    )
    op.create_table(
        "field_audits",
        sa.Column("audit_no", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "audit_type",
            sa.Enum(
                "contractor_hse",
                "system_iso45001",
                "client_requested",
                name="audittype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("template_code", sa.String(length=8), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("auditee_engagement_id", sa.Uuid(), nullable=True),
        sa.Column("site_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("lead_auditor_id", sa.Uuid(), nullable=False),
        sa.Column("team_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("planned_start", sa.Date(), nullable=False),
        sa.Column("planned_end", sa.Date(), nullable=False),
        sa.Column("fieldwork_start", sa.Date(), nullable=True),
        sa.Column("fieldwork_end", sa.Date(), nullable=True),
        sa.Column("opening_meeting_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closing_meeting_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("auditee_attendee_roles", sa.String(length=300), nullable=True),
        sa.Column("response_id", sa.Uuid(), nullable=True),
        sa.Column("summary_en", sa.String(length=3000), nullable=True),
        sa.Column("summary_ar", sa.String(length=3000), nullable=True),
        sa.Column("report_en_id", sa.Uuid(), nullable=True),
        sa.Column("report_ar_id", sa.Uuid(), nullable=True),
        sa.Column("issued_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "in_progress",
                "fieldwork_complete",
                "issued",
                "closed",
                "cancelled",
                "voided",
                name="auditstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.String(length=500), nullable=True),
        sa.Column("alerts_sent", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["auditee_engagement_id"],
            ["project_engagements.id"],
            name=op.f("fk_field_audits_auditee_engagement_id_project_engagements"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_field_audits_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["users.id"],
            name=op.f("fk_field_audits_issued_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["lead_auditor_id"], ["users.id"], name=op.f("fk_field_audits_lead_auditor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_field_audits_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["checklist_templates.id"],
            name=op.f("fk_field_audits_template_id_checklist_templates"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_field_audits_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_audits")),
        sa.UniqueConstraint("audit_no", name=op.f("uq_field_audits_audit_no")),
        sa.UniqueConstraint("project_id", "year", "seq", name=op.f("uq_field_audits_project_id")),
    )
    op.create_index(
        op.f("ix_field_audits_project_id"), "field_audits", ["project_id"], unique=False
    )
    op.create_table(
        "toolbox_talks",
        sa.Column("talk_no", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("client_uuid", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("zone_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("host_engagement_id", sa.Uuid(), nullable=False),
        sa.Column(
            "shift",
            sa.Enum("day", "night", name="talkshift", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_date", sa.Date(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("presenter_user_id", sa.Uuid(), nullable=True),
        sa.Column("presenter_deployment_id", sa.Uuid(), nullable=True),
        sa.Column("recorded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("topics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("topic_codes", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("interpreter_languages", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("unnamed_count", sa.Integer(), nullable=False),
        sa.Column("sheet_photo_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("questions_raised", sa.String(length=1000), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("offline_delay_min", sa.Integer(), nullable=True),
        sa.Column("rejected_rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "delivered", "locked", "voided", name="talkstatus", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_toolbox_talks_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["host_engagement_id"],
            ["project_engagements.id"],
            name=op.f("fk_toolbox_talks_host_engagement_id_project_engagements"),
        ),
        sa.ForeignKeyConstraint(
            ["presenter_deployment_id"],
            ["worker_deployments.id"],
            name=op.f("fk_toolbox_talks_presenter_deployment_id_worker_deployments"),
        ),
        sa.ForeignKeyConstraint(
            ["presenter_user_id"],
            ["users.id"],
            name=op.f("fk_toolbox_talks_presenter_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_toolbox_talks_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
            name=op.f("fk_toolbox_talks_recorded_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_toolbox_talks_site_id_sites")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_toolbox_talks_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_toolbox_talks")),
        sa.UniqueConstraint("project_id", "client_uuid", name="uq_toolbox_talk_client_uuid"),
        sa.UniqueConstraint("project_id", "year", "seq", name=op.f("uq_toolbox_talks_project_id")),
        sa.UniqueConstraint("talk_no", name=op.f("uq_toolbox_talks_talk_no")),
    )
    op.create_index(
        "ix_toolbox_talk_delivered", "toolbox_talks", ["project_id", "delivered_date"], unique=False
    )
    op.create_table(
        "checklist_responses",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("client_uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "owner_type",
            sa.Enum("inspection", "audit", name="responseownertype", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("inspection_id", sa.Uuid(), nullable=True),
        sa.Column("audit_id", sa.Uuid(), nullable=True),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("template_code", sa.String(length=8), nullable=False),
        sa.Column("template_version", sa.Integer(), nullable=False),
        sa.Column(
            "inspection_type",
            sa.Enum(
                "general_site",
                "scaffold",
                "lifting_equipment",
                "electrical",
                "excavation",
                "housekeeping",
                "fire_safety",
                "welfare",
                "airside_fod_walk",
                "plant_vehicle",
                "environmental",
                "ppe",
                "leadership_walk",
                name="inspectiontype",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=True),
        sa.Column("engagement_id", sa.Uuid(), nullable=True),
        sa.Column("airside", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_date", sa.Date(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("offline_delay_min", sa.Integer(), nullable=True),
        sa.Column("inspector_id", sa.Uuid(), nullable=True),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applicable_count", sa.Integer(), nullable=False),
        sa.Column("compliant_count", sa.Integer(), nullable=False),
        sa.Column("applicable_weight", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("earned_weight", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("score_pct", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("critical_fail_count", sa.Integer(), nullable=False),
        sa.Column(
            "result",
            sa.Enum("pass", "fail", name="responseresult", native_enum=False, length=40),
            nullable=True,
        ),
        sa.Column(
            "grade",
            sa.Enum("A", "B", "C", "D", name="auditgrade", native_enum=False, length=40),
            nullable=True,
        ),
        sa.Column("stop_work_order_id", sa.Uuid(), nullable=True),
        sa.Column("self_inspection", sa.Boolean(), nullable=False),
        sa.Column("submitted", sa.Boolean(), nullable=False),
        sa.Column("voided", sa.Boolean(), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_checklist_responses_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["project_engagements.id"],
            name=op.f("fk_checklist_responses_engagement_id_project_engagements"),
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_checklist_responses_inspection_id_inspections"),
        ),
        sa.ForeignKeyConstraint(
            ["inspector_id"], ["users.id"], name=op.f("fk_checklist_responses_inspector_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_checklist_responses_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_checklist_responses_site_id_sites")
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["checklist_templates.id"],
            name=op.f("fk_checklist_responses_template_id_checklist_templates"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_checklist_responses_updated_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zones.id"], name=op.f("fk_checklist_responses_zone_id_zones")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_responses")),
        sa.UniqueConstraint("project_id", "client_uuid", name="uq_checklist_response_client_uuid"),
    )
    op.create_index(
        "ix_checklist_response_completed",
        "checklist_responses",
        ["project_id", "completed_date"],
        unique=False,
    )
    op.create_table(
        "toolbox_attendance",
        sa.Column("talk_id", sa.Uuid(), nullable=False),
        sa.Column("deployment_id", sa.Uuid(), nullable=False),
        sa.Column("engagement_id", sa.Uuid(), nullable=True),
        sa.Column(
            "method",
            sa.Enum("card_scan", "list", name="attendancemethod", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("signature_id", sa.Uuid(), nullable=True),
        sa.Column(
            "understood_language",
            sa.Enum(
                "talk_language",
                "interpreter",
                "none",
                name="understoodlanguage",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("counted_person_type", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["worker_deployments.id"],
            name=op.f("fk_toolbox_attendance_deployment_id_worker_deployments"),
        ),
        sa.ForeignKeyConstraint(
            ["talk_id"],
            ["toolbox_talks.id"],
            name=op.f("fk_toolbox_attendance_talk_id_toolbox_talks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_toolbox_attendance")),
        sa.UniqueConstraint("talk_id", "deployment_id", name=op.f("uq_toolbox_attendance_talk_id")),
    )
    op.create_index(
        op.f("ix_toolbox_attendance_engagement_id"),
        "toolbox_attendance",
        ["engagement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_toolbox_attendance_talk_id"), "toolbox_attendance", ["talk_id"], unique=False
    )
    op.create_table(
        "field_findings",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("response_id", sa.Uuid(), nullable=False),
        sa.Column("finding_no", sa.String(length=60), nullable=False),
        sa.Column("item_code", sa.String(length=12), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "minor",
                "major",
                "critical",
                "major_nc",
                "minor_nc",
                "observation",
                "ofi",
                name="findingseverity",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("critical_item", sa.Boolean(), nullable=False),
        sa.Column("description_en", sa.String(length=1000), nullable=True),
        sa.Column("description_ar", sa.String(length=1000), nullable=True),
        sa.Column("repeat_of_id", sa.Uuid(), nullable=True),
        sa.Column("fixed_on_spot", sa.Boolean(), nullable=False),
        sa.Column("ca_required", sa.Boolean(), nullable=False),
        sa.Column("ca_id", sa.Uuid(), nullable=True),
        sa.Column("responsible_engagement_id", sa.Uuid(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=True),
        sa.Column("engagement_id", sa.Uuid(), nullable=True),
        sa.Column("completed_date", sa.Date(), nullable=True),
        sa.Column("voided", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ca_id"],
            ["corrective_actions.id"],
            name=op.f("fk_field_findings_ca_id_corrective_actions"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_field_findings_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_field_findings_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["checklist_responses.id"],
            name=op.f("fk_field_findings_response_id_checklist_responses"),
        ),
        sa.ForeignKeyConstraint(
            ["responsible_engagement_id"],
            ["project_engagements.id"],
            name=op.f("fk_field_findings_responsible_engagement_id_project_engagements"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_field_findings_site_id_sites")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_field_findings_updated_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zones.id"], name=op.f("fk_field_findings_zone_id_zones")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_findings")),
        sa.UniqueConstraint("finding_no", name=op.f("uq_field_findings_finding_no")),
    )
    op.create_index(
        "ix_field_finding_repeat",
        "field_findings",
        ["project_id", "item_code", "completed_date"],
        unique=False,
    )
    op.create_index("ix_field_finding_response", "field_findings", ["response_id"], unique=False)
    op.create_table(
        "stop_work_orders",
        sa.Column("order_no", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("response_id", sa.Uuid(), nullable=False),
        sa.Column("item_code", sa.String(length=12), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=True),
        sa.Column("engagement_id", sa.Uuid(), nullable=True),
        sa.Column("activity_en", sa.String(length=300), nullable=True),
        sa.Column("activity_ar", sa.String(length=300), nullable=True),
        sa.Column(
            "instructed_role",
            sa.Enum(
                "supervisor",
                "foreman",
                "operator",
                "permit_receiver",
                "other",
                name="instructedrole",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("instructed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raised_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_offline", sa.Boolean(), nullable=False),
        sa.Column("permit_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("ca_id", sa.Uuid(), nullable=True),
        sa.Column("released_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("release_note", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active", "released", "voided", name="stoporderstatus", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.String(length=500), nullable=True),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("alerts_sent", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ca_id"],
            ["corrective_actions.id"],
            name=op.f("fk_stop_work_orders_ca_id_corrective_actions"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_stop_work_orders_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["project_engagements.id"],
            name=op.f("fk_stop_work_orders_engagement_id_project_engagements"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_stop_work_orders_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["released_by_user_id"],
            ["users.id"],
            name=op.f("fk_stop_work_orders_released_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["checklist_responses.id"],
            name=op.f("fk_stop_work_orders_response_id_checklist_responses"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_stop_work_orders_site_id_sites")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_stop_work_orders_updated_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zones.id"], name=op.f("fk_stop_work_orders_zone_id_zones")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stop_work_orders")),
        sa.UniqueConstraint("order_no", name=op.f("uq_stop_work_orders_order_no")),
        sa.UniqueConstraint(
            "project_id", "year", "seq", name=op.f("uq_stop_work_orders_project_id")
        ),
    )
    op.create_index(
        op.f("ix_stop_work_orders_project_id"), "stop_work_orders", ["project_id"], unique=False
    )
    op.add_column(
        "inspection_plans", sa.Column("template_code", sa.String(length=8), nullable=True)
    )
    op.add_column(
        "inspection_plans",
        sa.Column(
            "rotation",
            sa.Enum("none", "zones", "engagements", name="rotation", native_enum=False, length=40),
            server_default="none",
            nullable=False,
        ),
    )
    op.add_column(
        "inspection_plans",
        sa.Column(
            "rotation_list", postgresql.ARRAY(sa.UUID()), server_default="{}", nullable=False
        ),
    )
    op.add_column("inspections", sa.Column("response_id", sa.Uuid(), nullable=True))
    op.add_column("inspections", sa.Column("offline_delay_min", sa.Integer(), nullable=True))
    op.add_column("inspections", sa.Column("void_reason", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inspections", "void_reason")
    op.drop_column("inspections", "offline_delay_min")
    op.drop_column("inspections", "response_id")
    op.drop_column("inspection_plans", "rotation_list")
    op.drop_column("inspection_plans", "rotation")
    op.drop_column("inspection_plans", "template_code")
    op.drop_index(op.f("ix_stop_work_orders_project_id"), table_name="stop_work_orders")
    op.drop_table("stop_work_orders")
    op.drop_index("ix_field_finding_response", table_name="field_findings")
    op.drop_index("ix_field_finding_repeat", table_name="field_findings")
    op.drop_table("field_findings")
    op.drop_index(op.f("ix_toolbox_attendance_talk_id"), table_name="toolbox_attendance")
    op.drop_index(op.f("ix_toolbox_attendance_engagement_id"), table_name="toolbox_attendance")
    op.drop_table("toolbox_attendance")
    op.drop_index("ix_checklist_response_completed", table_name="checklist_responses")
    op.drop_table("checklist_responses")
    op.drop_index("ix_toolbox_talk_delivered", table_name="toolbox_talks")
    op.drop_table("toolbox_talks")
    op.drop_index(op.f("ix_field_audits_project_id"), table_name="field_audits")
    op.drop_table("field_audits")
    op.drop_index(op.f("ix_briefing_campaigns_project_id"), table_name="briefing_campaigns")
    op.drop_table("briefing_campaigns")
    op.drop_index(op.f("ix_toolbox_topics_topic_code"), table_name="toolbox_topics")
    op.drop_table("toolbox_topics")
    op.drop_table("project_field_settings")
    op.drop_index(op.f("ix_checklist_templates_template_code"), table_name="checklist_templates")
    op.drop_table("checklist_templates")
    # ### end Alembic commands ###
