"""phase6a occupational health

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-08 20:01:36.257220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitness_codes',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('general', 'task', 'surveillance', name='fitnesscategory', native_enum=False, length=40), nullable=False),
    sa.Column('validity_months', sa.Integer(), nullable=False),
    sa.Column('examiner_classes', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('provider_kinds', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('typical_tests', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('extra_negated_by', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('seeded', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_fitness_codes_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_fitness_codes_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fitness_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_fitness_codes_code'))
    )
    op.create_table('medical_examiners',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('examiner_no', sa.String(length=12), nullable=False),
    sa.Column('full_name_en', sa.String(length=120), nullable=False),
    sa.Column('full_name_ar', sa.String(length=120), nullable=False),
    sa.Column('scfhs_licence_no', sa.String(length=30), nullable=False),
    sa.Column('classification', sa.Enum('occupational_physician', 'physician', 'nurse', name='examinerclass', native_enum=False, length=40), nullable=False),
    sa.Column('licence_valid_until', sa.Date(), nullable=False),
    sa.Column('licence_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('licence_checked_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('provider_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'withdrawn', 'expired', name='examinerstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_medical_examiners_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['licence_checked_by_user_id'], ['users.id'], name=op.f('fk_medical_examiners_licence_checked_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_medical_examiners_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_medical_examiners_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_examiners')),
    sa.UniqueConstraint('examiner_no', name=op.f('uq_medical_examiners_examiner_no')),
    sa.UniqueConstraint('scfhs_licence_no', name=op.f('uq_medical_examiners_scfhs_licence_no')),
    sa.UniqueConstraint('seq', name=op.f('uq_medical_examiners_seq')),
    sa.UniqueConstraint('user_id', name=op.f('uq_medical_examiners_user_id'))
    )
    op.create_table('medical_plan_lines',
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.String(length=40), nullable=False),
    sa.Column('applies_to_kind', sa.Enum('all_workers', 'trade', 'exposure_group', 'adp_category', 'zone', 'project_hook', 'crew_role', 'operator_binding', name='medicalappliesto', native_enum=False, length=40), nullable=False),
    sa.Column('applies_to_values', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('trades', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('due_within_days', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'hook', 'enforcement', name='medicallinesource', native_enum=False, length=40), nullable=False),
    sa.Column('kpi_counted', sa.Boolean(), nullable=False),
    sa.Column('hook_key', sa.String(length=200), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_medical_plan_lines_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_medical_plan_lines_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_medical_plan_lines_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_plan_lines'))
    )
    op.create_index('ix_medical_plan_line', 'medical_plan_lines', ['line_id'], unique=False)
    op.create_index('ix_medical_plan_project', 'medical_plan_lines', ['project_id', 'effective_from'], unique=False)
    op.create_table('medical_providers',
    sa.Column('provider_code', sa.String(length=12), nullable=False),
    sa.Column('legal_name_en', sa.String(length=200), nullable=False),
    sa.Column('legal_name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_norm_en', sa.String(length=200), nullable=False),
    sa.Column('name_norm_ar', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('site_clinic', 'external_clinic', 'contractor_clinic', name='medicalproviderkind', native_enum=False, length=40), nullable=False),
    sa.Column('project_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('contractor_id', sa.Uuid(), nullable=True),
    sa.Column('moh_licence_no', sa.String(length=40), nullable=False),
    sa.Column('licence_valid_until', sa.Date(), nullable=False),
    sa.Column('licence_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('licence_checked_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('verification_domains', postgresql.ARRAY(sa.String(length=253)), nullable=False),
    sa.Column('verification_email', sa.String(length=254), nullable=True),
    sa.Column('verification_phone', sa.String(length=20), nullable=True),
    sa.Column('verification_portal_url', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'suspended', 'blacklisted', name='medicalproviderstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('approved_on', sa.Date(), nullable=True),
    sa.Column('suspension_periods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blacklist_scope', sa.Enum('all_records', 'issued_from', name='medicalblacklistscope', native_enum=False, length=40), nullable=True),
    sa.Column('blacklist_from', sa.Date(), nullable=True),
    sa.Column('blacklisted_on', sa.Date(), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_medical_providers_contractor_id_contractors')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_medical_providers_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['licence_checked_by_user_id'], ['users.id'], name=op.f('fk_medical_providers_licence_checked_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_medical_providers_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_providers')),
    sa.UniqueConstraint('moh_licence_no', name=op.f('uq_medical_providers_moh_licence_no')),
    sa.UniqueConstraint('name_norm_ar', name=op.f('uq_medical_providers_name_norm_ar')),
    sa.UniqueConstraint('name_norm_en', name=op.f('uq_medical_providers_name_norm_en')),
    sa.UniqueConstraint('provider_code', name=op.f('uq_medical_providers_provider_code'))
    )
    op.create_table('project_medical_settings',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('medical_register_from', sa.Date(), nullable=True),
    sa.Column('fitness_validity_months', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('medical_hook_transition_days', sa.Integer(), nullable=False),
    sa.Column('medical_hook_critical_transition_days', sa.Integer(), nullable=False),
    sa.Column('medical_hook_critical_codes', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('unverified_fitness_acceptance_hours', sa.Integer(), nullable=False),
    sa.Column('fitness_verification_due_days', sa.Integer(), nullable=False),
    sa.Column('referral_assessment_hours', sa.Integer(), nullable=False),
    sa.Column('signoff_due_hours', sa.Integer(), nullable=False),
    sa.Column('assessment_backdate_max_days', sa.Integer(), nullable=False),
    sa.Column('restriction_review_max_days', sa.Integer(), nullable=False),
    sa.Column('unfit_review_max_days', sa.Integer(), nullable=False),
    sa.Column('medical_line_max_due_days', sa.Integer(), nullable=False),
    sa.Column('rtw_hold_case_categories', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('heat_illness_natures', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('exposure_group_trade_defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('medical_compliance_warning_pct', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('health_cell_min', sa.Integer(), nullable=False),
    sa.Column('fitness_scan_retention_months', sa.Integer(), nullable=False),
    sa.Column('fitness_record_retention_years', sa.Integer(), nullable=False),
    sa.Column('surveillance_record_retention_years', sa.Integer(), nullable=False),
    sa.Column('worker_purpose_notice_version', sa.String(length=40), nullable=False),
    sa.Column('alert_schedule_long_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_medical_settings_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_project_medical_settings_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_medical_settings'))
    )
    op.create_table('fitness_assessments',
    sa.Column('assessment_no', sa.String(length=40), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('assessment_type', sa.Enum('pre_placement', 'periodic', 'return_to_work', 'referral', 'change_of_task', 'post_exposure', 'exit', name='assessmenttype', native_enum=False, length=40), nullable=False),
    sa.Column('source', sa.Enum('site_clinic', 'external_certificate', 'import', name='assessmentsource', native_enum=False, length=40), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('examiner_id', sa.Uuid(), nullable=False),
    sa.Column('examined_on', sa.Date(), nullable=False),
    sa.Column('certificate_no', sa.String(length=40), nullable=False),
    sa.Column('related_hold_id', sa.UUID(), nullable=True),
    sa.Column('related_referral_id', sa.UUID(), nullable=True),
    sa.Column('purpose_notice_given', sa.Boolean(), nullable=False),
    sa.Column('purpose_notice_version', sa.String(length=40), nullable=True),
    sa.Column('name_as_printed', sa.String(length=120), nullable=True),
    sa.Column('name_match', sa.Enum('exact', 'partial', 'none', name='namematch', native_enum=False, length=40), nullable=True),
    sa.Column('id_match_result', sa.Enum('matched', 'matched_previous_id', 'not_shown', name='idmatchresult', native_enum=False, length=40), nullable=True),
    sa.Column('scan_attachment_id', sa.UUID(), nullable=True),
    sa.Column('scan_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinical_data_present', sa.Boolean(), nullable=True),
    sa.Column('historic', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'awaiting_signoff', 'submitted', 'accepted', 'rejected', 'revoked', name='assessmentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason_enc', sa.LargeBinary(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('not_verified', 'verified', 'failed', 'unable_to_verify', name='verificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('verification_due_on', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('signed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_code', sa.String(length=40), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_fitness_assessments_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_fitness_assessments_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['examiner_id'], ['medical_examiners.id'], name=op.f('fk_fitness_assessments_examiner_id_medical_examiners')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_fitness_assessments_project_id_projects')),
    sa.ForeignKeyConstraint(['provider_id'], ['medical_providers.id'], name=op.f('fk_fitness_assessments_provider_id_medical_providers')),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_fitness_assessments_recorded_by_user_id_users')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_fitness_assessments_reviewed_by_user_id_users')),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], name=op.f('fk_fitness_assessments_revoked_by_user_id_users')),
    sa.ForeignKeyConstraint(['signed_by_user_id'], ['users.id'], name=op.f('fk_fitness_assessments_signed_by_user_id_users')),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_fitness_assessments_submitted_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_fitness_assessments_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_fitness_assessments_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fitness_assessments')),
    sa.UniqueConstraint('assessment_no', name=op.f('uq_fitness_assessments_assessment_no')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_fitness_assessments_project_id')),
    sa.UniqueConstraint('provider_id', 'certificate_no', name=op.f('uq_fitness_assessments_provider_id'))
    )
    op.create_index('ix_fitness_assessment_project', 'fitness_assessments', ['project_id', 'status'], unique=False)
    op.create_index('ix_fitness_assessment_worker', 'fitness_assessments', ['worker_id'], unique=False)
    op.create_table('fitness_holds',
    sa.Column('hold_no', sa.String(length=40), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Enum('rtw_after_injury', 'heat_illness', 'referral', 'manual', name='holdreason', native_enum=False, length=40), nullable=False),
    sa.Column('source_type', sa.Enum('injury_case', 'referral', 'manual', name='holdsourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_ref', sa.String(length=40), nullable=True),
    sa.Column('reason_text_enc', sa.LargeBinary(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'released', 'cancelled', name='holdstatus', native_enum=False, length=40), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_assessment_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_code', sa.Enum('source_voided', 'source_reclassified', name='holdcancelcode', native_enum=False, length=40), nullable=True),
    sa.Column('cancel_reason_enc', sa.LargeBinary(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('work_during_hold', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], name=op.f('fk_fitness_holds_cancelled_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_fitness_holds_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_fitness_holds_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_fitness_holds_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_fitness_holds_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_fitness_holds_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fitness_holds')),
    sa.UniqueConstraint('hold_no', name=op.f('uq_fitness_holds_hold_no')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_fitness_holds_project_id'))
    )
    op.create_index('ix_fitness_hold_worker', 'fitness_holds', ['worker_id', 'status'], unique=False)
    op.create_index(op.f('ix_fitness_holds_source_id'), 'fitness_holds', ['source_id'], unique=False)
    op.create_table('fitness_referrals',
    sa.Column('referral_no', sa.String(length=40), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Enum('observed_unwell', 'heat_illness_episode', 'self_reported', 'return_after_absence', 'post_incident_no_injury', 'certificate_restriction', 'supervisor_concern', 'other', name='referralreason', native_enum=False, length=40), nullable=False),
    sa.Column('note_enc', sa.LargeBinary(), nullable=True),
    sa.Column('remove_from_work', sa.Boolean(), nullable=False),
    sa.Column('raised_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'assessed', 'cancelled', name='referralstatus', native_enum=False, length=40), nullable=False),
    sa.Column('hold_id', sa.UUID(), nullable=True),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason_enc', sa.LargeBinary(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('source_cert_id', sa.UUID(), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], name=op.f('fk_fitness_referrals_cancelled_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_fitness_referrals_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_fitness_referrals_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_fitness_referrals_project_id_projects')),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], name=op.f('fk_fitness_referrals_raised_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_fitness_referrals_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_fitness_referrals_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fitness_referrals')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_fitness_referrals_project_id')),
    sa.UniqueConstraint('referral_no', name=op.f('uq_fitness_referrals_referral_no'))
    )
    op.create_index('ix_fitness_referral_worker', 'fitness_referrals', ['worker_id', 'status'], unique=False)
    op.create_table('medical_import_batches',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('clinic_register_file', 'contractor_file', name='medicalimportsource', native_enum=False, length=40), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('evidence_file_name', sa.String(length=255), nullable=True),
    sa.Column('evidence_sha256', sa.String(length=64), nullable=True),
    sa.Column('evidence_sender', sa.String(length=254), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'validated', 'committed', 'discarded', 'expired', name='medicalimportstatus', native_enum=False, length=40), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rows_enc', sa.LargeBinary(), nullable=True),
    sa.Column('committed_assessment_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_medical_import_batches_project_id_projects')),
    sa.ForeignKeyConstraint(['provider_id'], ['medical_providers.id'], name=op.f('fk_medical_import_batches_provider_id_medical_providers')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_medical_import_batches_uploaded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_import_batches'))
    )
    op.create_index(op.f('ix_medical_import_batches_file_sha256'), 'medical_import_batches', ['file_sha256'], unique=False)
    op.create_index(op.f('ix_medical_import_batches_project_id'), 'medical_import_batches', ['project_id'], unique=False)
    op.create_table('fitness_lines',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('outcome', sa.Enum('fit', 'fit_with_restrictions', 'temporarily_unfit', 'permanently_unfit', name='fitnessoutcome', native_enum=False, length=40), nullable=False),
    sa.Column('restrictions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('restriction_codes', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('restriction_review_date', sa.Date(), nullable=True),
    sa.Column('unfit_review_date', sa.Date(), nullable=True),
    sa.Column('printed_next_due', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('limiting_factor', sa.Enum('restriction_review', 'printed_next_due', 'code_validity', 'project_override', name='fitnesslimitingfactor', native_enum=False, length=40), nullable=True),
    sa.Column('line_state', sa.Enum('pending', 'governing', 'superseded', 'revoked', 'rejected', name='fitnesslinestate', native_enum=False, length=40), nullable=False),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('anonymised', sa.Boolean(), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['fitness_assessments.id'], name=op.f('fk_fitness_lines_assessment_id_fitness_assessments')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_fitness_lines_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fitness_lines')),
    sa.UniqueConstraint('assessment_id', 'code', name=op.f('uq_fitness_lines_assessment_id'))
    )
    op.create_index('ix_fitness_line_worker', 'fitness_lines', ['worker_id', 'code'], unique=False)
    op.create_table('fitness_verifications',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.Enum('clinic_portal', 'clinic_email', 'clinic_phone', 'site_clinic_record', 'clinic_register_file', name='fitnessverificationmethod', native_enum=False, length=40), nullable=False),
    sa.Column('channel_used', sa.String(length=200), nullable=False),
    sa.Column('outcome', sa.Enum('confirmed', 'not_found', 'details_differ', 'revoked_by_clinic', 'no_response', name='fitnessverificationoutcome', native_enum=False, length=40), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('performed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('counts_as_verification', sa.Boolean(), nullable=False),
    sa.Column('verification_status_after', sa.Enum('not_verified', 'verified', 'failed', 'unable_to_verify', name='verificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['fitness_assessments.id'], name=op.f('fk_fitness_verifications_assessment_id_fitness_assessments')),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], name=op.f('fk_fitness_verifications_performed_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_fitness_verifications_project_id_projects')),
    sa.ForeignKeyConstraint(['provider_id'], ['medical_providers.id'], name=op.f('fk_fitness_verifications_provider_id_medical_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fitness_verifications'))
    )
    op.create_index('ix_fitness_verification_assessment', 'fitness_verifications', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_fitness_verifications_project_id'), 'fitness_verifications', ['project_id'], unique=False)
    op.create_table('health_profiles',
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('exposure_groups', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_health_profiles_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['deployment_id'], ['worker_deployments.id'], name=op.f('fk_health_profiles_deployment_id_worker_deployments')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_health_profiles_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_health_profiles_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_profiles')),
    sa.UniqueConstraint('deployment_id', name=op.f('uq_health_profiles_deployment_id'))
    )
    op.create_index(op.f('ix_health_profiles_project_id'), 'health_profiles', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_profiles_project_id'), table_name='health_profiles')
    op.drop_table('health_profiles')
    op.drop_index(op.f('ix_fitness_verifications_project_id'), table_name='fitness_verifications')
    op.drop_index('ix_fitness_verification_assessment', table_name='fitness_verifications')
    op.drop_table('fitness_verifications')
    op.drop_index('ix_fitness_line_worker', table_name='fitness_lines')
    op.drop_table('fitness_lines')
    op.drop_index(op.f('ix_medical_import_batches_project_id'), table_name='medical_import_batches')
    op.drop_index(op.f('ix_medical_import_batches_file_sha256'), table_name='medical_import_batches')
    op.drop_table('medical_import_batches')
    op.drop_index('ix_fitness_referral_worker', table_name='fitness_referrals')
    op.drop_table('fitness_referrals')
    op.drop_index(op.f('ix_fitness_holds_source_id'), table_name='fitness_holds')
    op.drop_index('ix_fitness_hold_worker', table_name='fitness_holds')
    op.drop_table('fitness_holds')
    op.drop_index('ix_fitness_assessment_worker', table_name='fitness_assessments')
    op.drop_index('ix_fitness_assessment_project', table_name='fitness_assessments')
    op.drop_table('fitness_assessments')
    op.drop_table('project_medical_settings')
    op.drop_table('medical_providers')
    op.drop_index('ix_medical_plan_project', table_name='medical_plan_lines')
    op.drop_index('ix_medical_plan_line', table_name='medical_plan_lines')
    op.drop_table('medical_plan_lines')
    op.drop_table('medical_examiners')
    op.drop_table('fitness_codes')
    # ### end Alembic commands ###
