"""phase6b heat stress

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-09 06:02:49.715093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heat_ban_exemptions',
    sa.Column('exemption_no', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('zone_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('reason', sa.Enum('emergency_repair', 'exempt_activity_mhrsd', 'shaded_and_cooled_workplace', name='banexemptionreason', native_enum=False, length=40), nullable=False),
    sa.Column('controls_en', sa.String(length=1000), nullable=True),
    sa.Column('controls_ar', sa.String(length=1000), nullable=True),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'revoked', name='banexemptionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=300), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_heat_ban_exemptions_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_heat_ban_exemptions_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], name=op.f('fk_heat_ban_exemptions_granted_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_heat_ban_exemptions_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_heat_ban_exemptions_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heat_ban_exemptions')),
    sa.UniqueConstraint('exemption_no', name=op.f('uq_heat_ban_exemptions_exemption_no')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_heat_ban_exemptions_project_id'))
    )
    op.create_table('heat_instruments',
    sa.Column('instrument_no', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('handheld_meter', 'fixed_station', name='instrumentkind', native_enum=False, length=40), nullable=False),
    sa.Column('make_model', sa.String(length=80), nullable=False),
    sa.Column('serial_no', sa.String(length=40), nullable=False),
    sa.Column('iso7243_compliant', sa.Boolean(), nullable=False),
    sa.Column('calibration_valid_until', sa.Date(), nullable=False),
    sa.Column('calibration_cert_ref', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('active', 'quarantined', 'retired', name='instrumentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=300), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_heat_instruments_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_heat_instruments_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_heat_instruments_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heat_instruments')),
    sa.UniqueConstraint('instrument_no', name=op.f('uq_heat_instruments_instrument_no')),
    sa.UniqueConstraint('project_id', 'seq', name='uq_heat_instruments_seq'),
    sa.UniqueConstraint('project_id', 'serial_no', name='uq_heat_instruments_serial')
    )
    op.create_table('heat_regime_limits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('basis', sa.Enum('acclimatised', 'unacclimatised', name='acclimatisationbasis', native_enum=False, length=40), nullable=False),
    sa.Column('regime', sa.Enum('R0', 'R1', 'R2', 'R3', 'R4', 'unknown', name='regime', native_enum=False, length=40), nullable=False),
    sa.Column('workload', sa.Enum('light', 'moderate', 'heavy', 'very_heavy', name='workload', native_enum=False, length=40), nullable=False),
    sa.Column('limit_c', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_heat_regime_limits_changed_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heat_regime_limits')),
    sa.UniqueConstraint('basis', 'regime', 'workload', name=op.f('uq_heat_regime_limits_basis'))
    )
    op.create_table('heat_rest_stations',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('station_code', sa.String(length=16), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('zone_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('station_type', sa.Enum('cooled_cabin', 'shaded_shelter', 'mobile_shade_unit', 'indoor_rest_area', name='stationtype', native_enum=False, length=40), nullable=False),
    sa.Column('capacity_persons', sa.Integer(), nullable=False),
    sa.Column('cooling', sa.Enum('none', 'fans', 'misting', 'air_conditioning', name='cooling', native_enum=False, length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_heat_rest_stations_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_heat_rest_stations_project_id_projects')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_heat_rest_stations_site_id_sites')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_heat_rest_stations_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heat_rest_stations')),
    sa.UniqueConstraint('project_id', 'station_code', name=op.f('uq_heat_rest_stations_project_id'))
    )
    op.create_table('heat_season_reports',
    sa.Column('report_no', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'superseded', name='seasonreportstatus', native_enum=False, length=40), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comments_en', sa.String(length=2000), nullable=True),
    sa.Column('comments_ar', sa.String(length=2000), nullable=True),
    sa.Column('reissue_reason', sa.String(length=300), nullable=True),
    sa.Column('issued_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], name=op.f('fk_heat_season_reports_issued_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_heat_season_reports_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heat_season_reports')),
    sa.UniqueConstraint('project_id', 'season_year', 'revision', name=op.f('uq_heat_season_reports_project_id')),
    sa.UniqueConstraint('report_no', name=op.f('uq_heat_season_reports_report_no'))
    )
    op.create_table('project_heat_settings',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('heat_register_from', sa.Date(), nullable=True),
    sa.Column('heat_ptw_enforcement_from', sa.Date(), nullable=True),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_heat_settings_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_project_heat_settings_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_heat_settings'))
    )
    op.create_table('heat_ban_patrols',
    sa.Column('patrol_no', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.Enum('no_outdoor_work', 'compliant_shaded_or_indoor', 'exempt_work', 'violation', name='patroloutcome', native_enum=False, length=40), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('activity', sa.String(length=200), nullable=True),
    sa.Column('exemption_ref', sa.String(length=40), nullable=True),
    sa.Column('permit_id', sa.UUID(), nullable=True),
    sa.Column('photo_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('ca_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('valid', 'voided', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.Column('void_reason', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checked_by_user_id'], ['users.id'], name=op.f('fk_heat_ban_patrols_checked_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_heat_ban_patrols_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_heat_ban_patrols_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_heat_ban_patrols_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_heat_ban_patrols_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_heat_ban_patrols_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heat_ban_patrols')),
    sa.UniqueConstraint('patrol_no', name=op.f('uq_heat_ban_patrols_patrol_no')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_heat_ban_patrols_project_id'))
    )
    op.create_index('ix_ban_patrol_zone_time', 'heat_ban_patrols', ['zone_id', 'checked_at'], unique=False)
    op.create_table('heat_illness_entries',
    sa.Column('entry_no', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('injury_case', 'referral', name='heatlogsource', native_enum=False, length=40), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('related_referral_id', sa.UUID(), nullable=True),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('control_gap', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('open', 'reviewed', 'voided', name='heatlogstatus', native_enum=False, length=40), nullable=False),
    sa.Column('hold_id', sa.UUID(), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_heat_illness_entries_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_heat_illness_entries_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_heat_illness_entries_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_heat_illness_entries_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_heat_illness_entries_worker_id_workers')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_heat_illness_entries_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heat_illness_entries')),
    sa.UniqueConstraint('entry_no', name=op.f('uq_heat_illness_entries_entry_no')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_heat_illness_entries_project_id'))
    )
    op.create_index(op.f('ix_heat_illness_entries_source_id'), 'heat_illness_entries', ['source_id'], unique=False)
    op.create_table('heat_monitoring_points',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('point_code', sa.String(length=16), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('zone_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('source_kind', sa.Enum('manual', 'station', name='pointsourcekind', native_enum=False, length=40), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=True),
    sa.Column('solar_load', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_heat_monitoring_points_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['instrument_id'], ['heat_instruments.id'], name=op.f('fk_heat_monitoring_points_instrument_id_heat_instruments')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_heat_monitoring_points_project_id_projects')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_heat_monitoring_points_site_id_sites')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_heat_monitoring_points_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heat_monitoring_points')),
    sa.UniqueConstraint('project_id', 'point_code', name=op.f('uq_heat_monitoring_points_project_id'))
    )
    op.create_table('heat_station_devices',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['heat_instruments.id'], name=op.f('fk_heat_station_devices_instrument_id_heat_instruments')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_heat_station_devices_project_id_projects')),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['users.id'], name=op.f('fk_heat_station_devices_registered_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heat_station_devices')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_heat_station_devices_token_hash'))
    )
    op.create_index(op.f('ix_heat_station_devices_project_id'), 'heat_station_devices', ['project_id'], unique=False)
    op.create_table('heat_welfare_checks',
    sa.Column('check_no', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('water_temp_c', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('persons_present', sa.Integer(), nullable=True),
    sa.Column('ca_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.Enum('valid', 'voided', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.Column('void_reason', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checked_by_user_id'], ['users.id'], name=op.f('fk_heat_welfare_checks_checked_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_heat_welfare_checks_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_heat_welfare_checks_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_heat_welfare_checks_project_id_projects')),
    sa.ForeignKeyConstraint(['station_id'], ['heat_rest_stations.id'], name=op.f('fk_heat_welfare_checks_station_id_heat_rest_stations')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_heat_welfare_checks_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heat_welfare_checks')),
    sa.UniqueConstraint('check_no', name=op.f('uq_heat_welfare_checks_check_no')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_heat_welfare_checks_project_id'))
    )
    op.create_index('ix_welfare_station_time', 'heat_welfare_checks', ['station_id', 'checked_at'], unique=False)
    op.create_table('acclimatisation_plans',
    sa.Column('plan_no', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('plan_type', sa.Enum('new_worker', 'returner', 'post_heat_illness', 'period_start', name='plantype', native_enum=False, length=40), nullable=False),
    sa.Column('trigger', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trigger_date', sa.Date(), nullable=False),
    sa.Column('schedule_pct', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('prior_heat_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('planned', 'waiting_restriction', 'active', 'completed', 'interrupted', 'cancelled', name='planstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=300), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_acclimatisation_plans_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['deployment_id'], ['worker_deployments.id'], name=op.f('fk_acclimatisation_plans_deployment_id_worker_deployments')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_acclimatisation_plans_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_acclimatisation_plans_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_acclimatisation_plans_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_acclimatisation_plans_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acclimatisation_plans')),
    sa.UniqueConstraint('plan_no', name=op.f('uq_acclimatisation_plans_plan_no')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_acclimatisation_plans_project_id'))
    )
    op.create_index('ix_acclim_plan_deployment', 'acclimatisation_plans', ['deployment_id', 'status'], unique=False)
    op.create_table('wbgt_readings',
    sa.Column('reading_no', sa.String(length=48), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('permit_id', sa.UUID(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('manual', 'station', 'import', name='readingsource', native_enum=False, length=40), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('device_pk', sa.Uuid(), nullable=True),
    sa.Column('ta_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('tnwb_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('tg_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('rh_pct', sa.Integer(), nullable=True),
    sa.Column('wbgt_entered_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('wbgt_c', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('regime_cells', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('late_entry', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('valid', 'voided', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.Column('void_reason', sa.String(length=300), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_pk'], ['heat_station_devices.id'], name=op.f('fk_wbgt_readings_device_pk_heat_station_devices')),
    sa.ForeignKeyConstraint(['instrument_id'], ['heat_instruments.id'], name=op.f('fk_wbgt_readings_instrument_id_heat_instruments')),
    sa.ForeignKeyConstraint(['point_id'], ['heat_monitoring_points.id'], name=op.f('fk_wbgt_readings_point_id_heat_monitoring_points')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_wbgt_readings_project_id_projects')),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_wbgt_readings_recorded_by_user_id_users')),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], name=op.f('fk_wbgt_readings_voided_by_user_id_users')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_wbgt_readings_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wbgt_readings')),
    sa.UniqueConstraint('project_id', 'local_date', 'seq', name=op.f('uq_wbgt_readings_project_id')),
    sa.UniqueConstraint('reading_no', name=op.f('uq_wbgt_readings_reading_no'))
    )
    op.create_index('ix_wbgt_point_time', 'wbgt_readings', ['point_id', 'measured_at'], unique=False)
    op.create_index('ix_wbgt_project_time', 'wbgt_readings', ['project_id', 'measured_at'], unique=False)
    op.create_index('uq_wbgt_station_time', 'wbgt_readings', ['device_pk', 'measured_at'], unique=True, postgresql_where=sa.text('device_pk IS NOT NULL'))
    op.add_column('permit_shifts', sa.Column('wbgt_reading_id', sa.UUID(), nullable=True))
    op.add_column('permits', sa.Column('heat_workload', sa.String(length=20), nullable=True))
    op.add_column('permits', sa.Column('heat_clothing', sa.String(length=40), nullable=True))
    op.add_column('permits', sa.Column('heat_hood', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permits', 'heat_hood')
    op.drop_column('permits', 'heat_clothing')
    op.drop_column('permits', 'heat_workload')
    op.drop_column('permit_shifts', 'wbgt_reading_id')
    op.drop_index('uq_wbgt_station_time', table_name='wbgt_readings', postgresql_where=sa.text('device_pk IS NOT NULL'))
    op.drop_index('ix_wbgt_project_time', table_name='wbgt_readings')
    op.drop_index('ix_wbgt_point_time', table_name='wbgt_readings')
    op.drop_table('wbgt_readings')
    op.drop_index('ix_acclim_plan_deployment', table_name='acclimatisation_plans')
    op.drop_table('acclimatisation_plans')
    op.drop_index('ix_welfare_station_time', table_name='heat_welfare_checks')
    op.drop_table('heat_welfare_checks')
    op.drop_index(op.f('ix_heat_station_devices_project_id'), table_name='heat_station_devices')
    op.drop_table('heat_station_devices')
    op.drop_table('heat_monitoring_points')
    op.drop_index(op.f('ix_heat_illness_entries_source_id'), table_name='heat_illness_entries')
    op.drop_table('heat_illness_entries')
    op.drop_index('ix_ban_patrol_zone_time', table_name='heat_ban_patrols')
    op.drop_table('heat_ban_patrols')
    op.drop_table('project_heat_settings')
    op.drop_table('heat_season_reports')
    op.drop_table('heat_rest_stations')
    op.drop_table('heat_regime_limits')
    op.drop_table('heat_instruments')
    op.drop_table('heat_ban_exemptions')
    # ### end Alembic commands ###
