"""phase6e environmental

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-09 18:15:53.614767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: Union[str, Sequence[str], None] = "0011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "env_aspects",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("aspect_no", sa.String(length=40), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("activity", sa.String(length=40), nullable=False),
        sa.Column("aspect", sa.String(length=40), nullable=False),
        sa.Column("impact", sa.String(length=40), nullable=False),
        sa.Column(
            "condition",
            sa.Enum(
                "normal",
                "abnormal",
                "emergency",
                name="aspectcondition",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("site_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("engagement_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("likelihood", sa.Integer(), nullable=False),
        sa.Column("legal_requirement", sa.Boolean(), nullable=False),
        sa.Column("permit_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("stakeholder_concern", sa.Boolean(), nullable=False),
        sa.Column("controls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("monitoring_links", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("activated_on", sa.Date(), nullable=True),
        sa.Column("review_due_on", sa.Date(), nullable=True),
        sa.Column("review_flag", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "active", "archived", name="aspectstatus", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_aspects_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_env_aspects_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_aspects_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_aspects")),
        sa.UniqueConstraint("aspect_no", name=op.f("uq_env_aspects_aspect_no")),
        sa.UniqueConstraint("project_id", "seq", name=op.f("uq_env_aspects_project_id")),
    )
    op.create_index(op.f("ix_env_aspects_project_id"), "env_aspects", ["project_id"], unique=False)
    op.create_table(
        "env_background_declarations",
        sa.Column("declaration_no", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("site_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("from_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("to_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "ncm_warning",
                "aocc",
                "visual_regional",
                "other",
                name="backgroundsource",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("source_ref", sa.String(length=40), nullable=False),
        sa.Column("declared_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_background_declarations_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["declared_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_background_declarations_declared_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_env_background_declarations_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_background_declarations_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_background_declarations")),
        sa.UniqueConstraint(
            "declaration_no", name=op.f("uq_env_background_declarations_declaration_no")
        ),
        sa.UniqueConstraint(
            "project_id", "year", "seq", name=op.f("uq_env_background_declarations_project_id")
        ),
    )
    op.create_table(
        "env_complaints",
        sa.Column("complaint_no", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_date", sa.Date(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "phone",
                "email",
                "in_person",
                "via_client",
                "via_authority",
                name="complaintchannel",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "dust",
                "noise",
                "odour",
                "waste",
                "water",
                "mud_on_road",
                "light",
                "other",
                name="complaintcategory",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("location_text", sa.String(length=200), nullable=True),
        sa.Column("anonymous", sa.Boolean(), nullable=False),
        sa.Column("complainant_name", sa.String(length=120), nullable=True),
        sa.Column("complainant_contact", sa.String(length=60), nullable=True),
        sa.Column("contact_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reading_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("exceedance_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("investigation_en", sa.Text(), nullable=True),
        sa.Column("investigation_ar", sa.Text(), nullable=True),
        sa.Column("response_due_on", sa.Date(), nullable=False),
        sa.Column("response_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_summary", sa.Text(), nullable=True),
        sa.Column("ca_id", sa.Uuid(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "responded",
                "closed",
                "voided",
                name="complaintstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("void_reason", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_complaints_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_env_complaints_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_env_complaints_site_id_sites")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_complaints_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_complaints")),
        sa.UniqueConstraint("complaint_no", name=op.f("uq_env_complaints_complaint_no")),
        sa.UniqueConstraint("project_id", "year", "seq", name=op.f("uq_env_complaints_project_id")),
    )
    op.create_table(
        "env_instruments",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_no", sa.String(length=30), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "pm_station",
                "pm_portable",
                "pm_sampler_24h",
                "sound_level_meter",
                "noise_station",
                "water_quality_meter",
                name="instrumentkind",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("make_model", sa.String(length=80), nullable=False),
        sa.Column("serial_no", sa.String(length=40), nullable=False),
        sa.Column("standard_class", sa.String(length=2), nullable=True),
        sa.Column("calibration_valid_until", sa.Date(), nullable=False),
        sa.Column("calibration_cert_ref", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "quarantined",
                "retired",
                name="instrumentstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_instruments_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_env_instruments_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_instruments_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_instruments")),
        sa.UniqueConstraint("project_id", "instrument_no", name="uq_env_instrument_no"),
        sa.UniqueConstraint("project_id", "serial_no", name="uq_env_instrument_serial"),
    )
    op.create_table(
        "env_providers",
        sa.Column("provider_code", sa.String(length=12), nullable=False),
        sa.Column("name_en", sa.String(length=150), nullable=False),
        sa.Column("name_ar", sa.String(length=150), nullable=False),
        sa.Column("cr_number", sa.String(length=10), nullable=False),
        sa.Column("kinds", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("facilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contact_email", sa.String(length=120), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "approved",
                "suspended",
                "blacklisted",
                name="providerstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_providers_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_providers_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_providers")),
        sa.UniqueConstraint("provider_code", name=op.f("uq_env_providers_provider_code")),
    )
    op.create_table(
        "env_water_entries",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "network",
                "tanker",
                "groundwater_dewatering_reuse",
                "treated_effluent",
                name="watersource",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("volume_m3", sa.Numeric(precision=10, scale=1), nullable=False),
        sa.Column("purpose", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("valid", "voided", name="recordstate", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("void_reason", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_water_entries_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_env_water_entries_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_env_water_entries_site_id_sites")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_water_entries_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_water_entries")),
    )
    op.create_index(
        "ix_water_entry_key",
        "env_water_entries",
        ["project_id", "site_id", "month", "source"],
        unique=False,
    )
    op.create_table(
        "project_env_settings",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("env_notifications_from", sa.Date(), nullable=True),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_env_settings_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_project_env_settings_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_project_env_settings")),
    )
    op.create_table(
        "waste_streams",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("stream_code", sa.String(length=30), nullable=False),
        sa.Column(
            "default_route",
            sa.Enum(
                "reuse",
                "recycle",
                "recovery",
                "treatment",
                "disposal_landfill",
                name="wasteroute",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("density", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_waste_streams_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_waste_streams_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_waste_streams_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_waste_streams")),
        sa.UniqueConstraint("project_id", "stream_code", name=op.f("uq_waste_streams_project_id")),
    )
    op.create_table(
        "env_monitor_devices",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("registered_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["env_instruments.id"],
            name=op.f("fk_env_monitor_devices_instrument_id_env_instruments"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_env_monitor_devices_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["registered_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_monitor_devices_registered_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_monitor_devices")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_env_monitor_devices_token_hash")),
    )
    op.create_index(
        op.f("ix_env_monitor_devices_project_id"),
        "env_monitor_devices",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "env_permits",
        sa.Column("record_no", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("provider_id", sa.Uuid(), nullable=True),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "permit_type",
            sa.Enum(
                "ncec_env_permit_construction",
                "ncec_env_permit_operation",
                "eia_approval",
                "mwan_producer_registration",
                "municipal_construction_permit",
                "dewatering_discharge_permit",
                "sewer_discharge_permit",
                "cemp_approval",
                "mwan_licence",
                "facility_authorisation",
                "lab_accreditation",
                "other",
                name="permittype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "issuer",
            sa.Enum(
                "ncec",
                "mwan",
                "momrah_municipality",
                "nwc",
                "mewa",
                "airport_operator",
                "gaca",
                "client",
                "saac",
                "other",
                name="issuer",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("requirement_code", sa.String(length=20), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("applies_from", sa.Date(), nullable=True),
        sa.Column("applies_to", sa.Date(), nullable=True),
        sa.Column("reference_no", sa.String(length=40), nullable=True),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column(
            "manual_status",
            sa.Enum(
                "pending",
                "valid",
                "expiring",
                "expired",
                "suspended",
                "superseded",
                "cancelled",
                name="permitstatus",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("manual_from", sa.Date(), nullable=True),
        sa.Column("status_reason", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_permits_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_env_permits_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["env_providers.id"],
            name=op.f("fk_env_permits_provider_id_env_providers"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["env_permits.id"],
            name=op.f("fk_env_permits_supersedes_id_env_permits"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_permits_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_permits")),
        sa.UniqueConstraint("record_no", name=op.f("uq_env_permits_record_no")),
    )
    op.create_index(op.f("ix_env_permits_project_id"), "env_permits", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_env_permits_provider_id"), "env_permits", ["provider_id"], unique=False
    )
    op.create_table(
        "waste_storage_areas",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("area_code", sa.String(length=16), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "skip",
                "segregated_bay",
                "hazardous_store",
                "liquid_store",
                "compactor",
                "sealed_bin_station",
                name="storageareatype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("accepted_streams", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("capacity_m3", sa.Numeric(precision=7, scale=1), nullable=False),
        sa.Column("secondary_containment_pct", sa.Integer(), nullable=True),
        sa.Column("covered", sa.Boolean(), nullable=False),
        sa.Column("lidded_secured", sa.Boolean(), nullable=False),
        sa.Column("signage_bilingual", sa.Boolean(), nullable=False),
        sa.Column("accumulation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "closed", name="areastatus", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_waste_storage_areas_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_waste_storage_areas_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_waste_storage_areas_site_id_sites")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_waste_storage_areas_updated_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zones.id"], name=op.f("fk_waste_storage_areas_zone_id_zones")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_waste_storage_areas")),
        sa.UniqueConstraint(
            "project_id", "area_code", name=op.f("uq_waste_storage_areas_project_id")
        ),
    )
    op.create_table(
        "env_points",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("point_code", sa.String(length=16), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "boundary",
                "sensitive_receptor",
                "airside",
                "background_upwind",
                "discharge",
                "work_area",
                name="pointkind",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "noise_area_category",
            sa.Enum(
                "residential",
                "mixed_commercial",
                "industrial",
                "sensitive",
                name="noisearea",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column(
            "source_kind",
            sa.Enum(
                "manual", "station", "visual", name="pointsource", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("instrument_id", sa.Uuid(), nullable=True),
        sa.Column("permit_id", sa.Uuid(), nullable=True),
        sa.Column("requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_points_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["env_instruments.id"],
            name=op.f("fk_env_points_instrument_id_env_instruments"),
        ),
        sa.ForeignKeyConstraint(
            ["permit_id"], ["env_permits.id"], name=op.f("fk_env_points_permit_id_env_permits")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_env_points_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_env_points_site_id_sites")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_points_updated_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zones.id"], name=op.f("fk_env_points_zone_id_zones")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_points")),
        sa.UniqueConstraint("project_id", "point_code", name=op.f("uq_env_points_project_id")),
    )
    op.create_table(
        "env_spills",
        sa.Column("spill_no", sa.String(length=40), nullable=False),
        sa.Column("client_uuid", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurred_date", sa.Date(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=True),
        sa.Column("responsible_engagement_id", sa.Uuid(), nullable=False),
        sa.Column(
            "substance",
            sa.Enum(
                "diesel",
                "petrol",
                "hydraulic_oil",
                "engine_oil",
                "bitumen_emulsion",
                "paint",
                "solvent",
                "concrete_washout",
                "sewage",
                "chemical_other",
                "other",
                name="spillsubstance",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "plant_leak",
                "refuelling",
                "container_failure",
                "tanker",
                "other",
                name="spillsource",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("quantity_l", sa.Numeric(precision=9, scale=1), nullable=False),
        sa.Column(
            "surface",
            sa.Enum(
                "paved",
                "unpaved_soil",
                "drain",
                "water_body",
                name="spillsurface",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("contained", sa.Boolean(), nullable=False),
        sa.Column(
            "reached",
            sa.Enum(
                "none",
                "soil",
                "drain",
                "water_body",
                name="envreached",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("spill_kit_asset_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("reportable", sa.Boolean(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("cleanup_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cleanup_consignment_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("cleanup_storage_area_id", sa.Uuid(), nullable=True),
        sa.Column("absorbed_and_binned", sa.Boolean(), nullable=False),
        sa.Column("photo_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("recorded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "reported",
                "cleaned_up",
                "closed",
                "voided",
                name="spillstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("void_reason", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cleanup_storage_area_id"],
            ["waste_storage_areas.id"],
            name=op.f("fk_env_spills_cleanup_storage_area_id_waste_storage_areas"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_spills_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incidents.id"], name=op.f("fk_env_spills_incident_id_incidents")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_env_spills_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_spills_recorded_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["responsible_engagement_id"],
            ["project_engagements.id"],
            name=op.f("fk_env_spills_responsible_engagement_id_project_engagements"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_env_spills_site_id_sites")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_spills_updated_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zones.id"], name=op.f("fk_env_spills_zone_id_zones")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_spills")),
        sa.UniqueConstraint("project_id", "client_uuid", name="uq_env_spill_client_uuid"),
        sa.UniqueConstraint("project_id", "year", "seq", name=op.f("uq_env_spills_project_id")),
        sa.UniqueConstraint("spill_no", name=op.f("uq_env_spills_spill_no")),
    )
    op.create_table(
        "waste_consignments",
        sa.Column("consignment_no", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("stream_code", sa.String(length=30), nullable=False),
        sa.Column("storage_area_id", sa.Uuid(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=True),
        sa.Column("generator_engagement_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=9, scale=3), nullable=False),
        sa.Column(
            "unit",
            sa.Enum("t", "m3", "L", name="quantityunit", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("estimated_t", sa.Numeric(precision=9, scale=3), nullable=False),
        sa.Column(
            "route",
            sa.Enum(
                "reuse",
                "recycle",
                "recovery",
                "treatment",
                "disposal_landfill",
                name="wasteroute",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("transporter_id", sa.Uuid(), nullable=False),
        sa.Column("transporter_licence_id", sa.Uuid(), nullable=True),
        sa.Column("facility_provider_id", sa.Uuid(), nullable=False),
        sa.Column("facility_code", sa.String(length=20), nullable=True),
        sa.Column("facility_licence_id", sa.Uuid(), nullable=True),
        sa.Column("vehicle_plate", sa.String(length=12), nullable=False),
        sa.Column("driver_name", sa.String(length=120), nullable=True),
        sa.Column("driver_mobile", sa.String(length=15), nullable=True),
        sa.Column("mwan_manifest_ref", sa.String(length=40), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched_date", sa.Date(), nullable=False),
        sa.Column("dispatched_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("due_on", sa.Date(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_net_t", sa.Numeric(precision=9, scale=3), nullable=True),
        sa.Column("ticket_ref", sa.String(length=40), nullable=True),
        sa.Column("ticket_file_id", sa.Uuid(), nullable=True),
        sa.Column("receipt_recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discrepancy_pct", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("discrepancy_reason", sa.String(length=500), nullable=True),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("redispatch_of_id", sa.Uuid(), nullable=True),
        sa.Column("ca_id", sa.Uuid(), nullable=True),
        sa.Column("warnings", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "dispatched",
                "received",
                "closed",
                "rejected",
                "voided",
                name="consignmentstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.String(length=500), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_waste_consignments_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["dispatched_by_user_id"],
            ["users.id"],
            name=op.f("fk_waste_consignments_dispatched_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["facility_licence_id"],
            ["env_permits.id"],
            name=op.f("fk_waste_consignments_facility_licence_id_env_permits"),
        ),
        sa.ForeignKeyConstraint(
            ["facility_provider_id"],
            ["env_providers.id"],
            name=op.f("fk_waste_consignments_facility_provider_id_env_providers"),
        ),
        sa.ForeignKeyConstraint(
            ["generator_engagement_id"],
            ["project_engagements.id"],
            name=op.f("fk_waste_consignments_generator_engagement_id_project_engagements"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_waste_consignments_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["redispatch_of_id"],
            ["waste_consignments.id"],
            name=op.f("fk_waste_consignments_redispatch_of_id_waste_consignments"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_waste_consignments_site_id_sites")
        ),
        sa.ForeignKeyConstraint(
            ["storage_area_id"],
            ["waste_storage_areas.id"],
            name=op.f("fk_waste_consignments_storage_area_id_waste_storage_areas"),
        ),
        sa.ForeignKeyConstraint(
            ["transporter_id"],
            ["env_providers.id"],
            name=op.f("fk_waste_consignments_transporter_id_env_providers"),
        ),
        sa.ForeignKeyConstraint(
            ["transporter_licence_id"],
            ["env_permits.id"],
            name=op.f("fk_waste_consignments_transporter_licence_id_env_permits"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_waste_consignments_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_waste_consignments")),
        sa.UniqueConstraint("consignment_no", name=op.f("uq_waste_consignments_consignment_no")),
        sa.UniqueConstraint(
            "project_id", "year", "seq", name=op.f("uq_waste_consignments_project_id")
        ),
    )
    op.create_index(
        "ix_consignment_project_dispatch",
        "waste_consignments",
        ["project_id", "dispatched_date"],
        unique=False,
    )
    op.create_table(
        "env_discharge_days",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("point_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("volume_m3", sa.Numeric(precision=10, scale=1), nullable=False),
        sa.Column("warnings", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_discharge_days_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["point_id"], ["env_points.id"], name=op.f("fk_env_discharge_days_point_id_env_points")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_env_discharge_days_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_discharge_days_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_discharge_days")),
        sa.UniqueConstraint("point_id", "day", name=op.f("uq_env_discharge_days_point_id")),
    )
    op.create_table(
        "env_exceedances",
        sa.Column("exceedance_no", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("point_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column(
            "parameter",
            sa.Enum(
                "pm10",
                "pm2_5",
                "visual_dust",
                "laeq",
                "ph",
                "tss",
                "oil_grease",
                "turbidity",
                name="parameter",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "averaging",
            sa.Enum(
                "15min",
                "1h",
                "24h",
                "spot",
                "measurement",
                name="averaging",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "period",
            sa.Enum("any", "day", "night", name="noiseperiod", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("reading_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("peak_value", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("limit_value", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("margin_pct", sa.Numeric(precision=8, scale=1), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("episode_open", sa.Boolean(), nullable=False),
        sa.Column("late_result", sa.Boolean(), nullable=False),
        sa.Column(
            "suggested_cause",
            sa.Enum(
                "project_activity",
                "background_natural",
                "third_party",
                "instrument_fault",
                "unknown",
                name="exceedancecause",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("background_ref", sa.String(length=40), nullable=True),
        sa.Column(
            "cause",
            sa.Enum(
                "project_activity",
                "background_natural",
                "third_party",
                "instrument_fault",
                "unknown",
                name="exceedancecause",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("responsible_engagement_id", sa.Uuid(), nullable=True),
        sa.Column("activity_en", sa.String(length=300), nullable=True),
        sa.Column("activity_ar", sa.String(length=300), nullable=True),
        sa.Column("immediate_action_en", sa.Text(), nullable=True),
        sa.Column("immediate_action_ar", sa.Text(), nullable=True),
        sa.Column("ca_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "reviewed",
                "closed",
                "voided",
                name="exceedancestatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("void_reason", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_exceedances_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["point_id"], ["env_points.id"], name=op.f("fk_env_exceedances_point_id_env_points")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_env_exceedances_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["responsible_engagement_id"],
            ["project_engagements.id"],
            name=op.f("fk_env_exceedances_responsible_engagement_id_project_engagements"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_exceedances_reviewed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_env_exceedances_site_id_sites")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_exceedances_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_exceedances")),
        sa.UniqueConstraint("exceedance_no", name=op.f("uq_env_exceedances_exceedance_no")),
        sa.UniqueConstraint(
            "project_id", "year", "seq", name=op.f("uq_env_exceedances_project_id")
        ),
    )
    op.create_index(
        "ix_env_exceedance_point",
        "env_exceedances",
        ["point_id", "parameter", "averaging"],
        unique=False,
    )
    op.create_table(
        "env_readings",
        sa.Column("reading_no", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("point_id", sa.Uuid(), nullable=False),
        sa.Column(
            "parameter",
            sa.Enum(
                "pm10",
                "pm2_5",
                "visual_dust",
                "laeq",
                "ph",
                "tss",
                "oil_grease",
                "turbidity",
                name="parameter",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "averaging",
            sa.Enum(
                "15min",
                "1h",
                "24h",
                "spot",
                "measurement",
                name="averaging",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "period",
            sa.Enum("any", "day", "night", name="noiseperiod", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "station",
                "derived",
                "lab",
                "import",
                name="readingsource",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=True),
        sa.Column("device_pk", sa.Uuid(), nullable=True),
        sa.Column("lab_provider_id", sa.Uuid(), nullable=True),
        sa.Column("lab_report_ref", sa.String(length=40), nullable=True),
        sa.Column("field_calibration_checked", sa.Boolean(), nullable=True),
        sa.Column("background", sa.Boolean(), nullable=False),
        sa.Column("background_ref", sa.String(length=40), nullable=True),
        sa.Column(
            "result",
            sa.Enum(
                "ok",
                "alert",
                "exceedance",
                "no_limit",
                name="readingresult",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("limit_value", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("late_entry", sa.Boolean(), nullable=False),
        sa.Column("recorded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("photo_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("exceedance_id", sa.Uuid(), nullable=True),
        sa.Column("warnings", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column(
            "status",
            sa.Enum("valid", "voided", name="recordstate", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("void_reason", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("seed_fake", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_readings_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["device_pk"],
            ["env_monitor_devices.id"],
            name=op.f("fk_env_readings_device_pk_env_monitor_devices"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["env_instruments.id"],
            name=op.f("fk_env_readings_instrument_id_env_instruments"),
        ),
        sa.ForeignKeyConstraint(
            ["lab_provider_id"],
            ["env_providers.id"],
            name=op.f("fk_env_readings_lab_provider_id_env_providers"),
        ),
        sa.ForeignKeyConstraint(
            ["point_id"], ["env_points.id"], name=op.f("fk_env_readings_point_id_env_points")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_env_readings_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_readings_recorded_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_env_readings_updated_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_env_readings")),
        sa.UniqueConstraint("project_id", "day", "seq", name=op.f("uq_env_readings_project_id")),
        sa.UniqueConstraint("reading_no", name=op.f("uq_env_readings_reading_no")),
    )
    op.create_index(
        "ix_env_reading_point",
        "env_readings",
        ["point_id", "parameter", "averaging", "window_start"],
        unique=False,
    )
    op.create_index(
        "ix_env_reading_project_day", "env_readings", ["project_id", "day"], unique=False
    )
    op.add_column(
        "emergency_assets", sa.Column("used_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("emergency_assets", "used_at")
    op.drop_index("ix_env_reading_project_day", table_name="env_readings")
    op.drop_index("ix_env_reading_point", table_name="env_readings")
    op.drop_table("env_readings")
    op.drop_index("ix_env_exceedance_point", table_name="env_exceedances")
    op.drop_table("env_exceedances")
    op.drop_table("env_discharge_days")
    op.drop_index("ix_consignment_project_dispatch", table_name="waste_consignments")
    op.drop_table("waste_consignments")
    op.drop_table("env_spills")
    op.drop_table("env_points")
    op.drop_table("waste_storage_areas")
    op.drop_index(op.f("ix_env_permits_provider_id"), table_name="env_permits")
    op.drop_index(op.f("ix_env_permits_project_id"), table_name="env_permits")
    op.drop_table("env_permits")
    op.drop_index(op.f("ix_env_monitor_devices_project_id"), table_name="env_monitor_devices")
    op.drop_table("env_monitor_devices")
    op.drop_table("waste_streams")
    op.drop_table("project_env_settings")
    op.drop_index("ix_water_entry_key", table_name="env_water_entries")
    op.drop_table("env_water_entries")
    op.drop_table("env_providers")
    op.drop_table("env_instruments")
    op.drop_table("env_complaints")
    op.drop_table("env_background_declarations")
    op.drop_index(op.f("ix_env_aspects_project_id"), table_name="env_aspects")
    op.drop_table("env_aspects")
    # ### end Alembic commands ###
