"""phase4 cert

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-08 08:06:42.474001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cert_types',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label_en', sa.String(length=120), nullable=False),
    sa.Column('label_ar', sa.String(length=120), nullable=False),
    sa.Column('cap_months', sa.Integer(), nullable=False),
    sa.Column('scope_categories_allowed', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('levels_allowed', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('seeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_cert_types_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_cert_types'))
    )
    op.create_table('hook_policy_states',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('training_course', 'personnel_certificate', 'equipment_certificate', 'medical_fitness', name='hookkind', native_enum=False, length=40), nullable=False),
    sa.Column('provider_registered_on', sa.Date(), nullable=False),
    sa.Column('critical_block_from', sa.Date(), nullable=False),
    sa.Column('general_block_from', sa.Date(), nullable=False),
    sa.Column('original_general_block_from', sa.Date(), nullable=False),
    sa.Column('deferral', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('early_switches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('switched_codes', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('all_switched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('critical_switched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('general_switched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage', sa.Enum('warn', 'transition', 'block', name='hookstage', native_enum=False, length=40), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_hook_policy_states_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_hook_policy_states_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_hook_policy_states_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hook_policy_states')),
    sa.UniqueConstraint('project_id', 'kind', name=op.f('uq_hook_policy_states_project_id'))
    )
    op.create_table('project_cert_settings',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_interval_months', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('personnel_cert_cap_months', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('require_client_approved_tpi', sa.Boolean(), nullable=False),
    sa.Column('client_approval_required_from', sa.Date(), nullable=True),
    sa.Column('unverified_acceptance_hours', sa.Integer(), nullable=False),
    sa.Column('verification_due_days', sa.Integer(), nullable=False),
    sa.Column('defect_b_max_days', sa.Integer(), nullable=False),
    sa.Column('defect_b_default_days', sa.Integer(), nullable=False),
    sa.Column('scaffold_inspection_interval_days', sa.Integer(), nullable=False),
    sa.Column('scaffold_design_height_m', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('arrival_inspection_hours', sa.Integer(), nullable=False),
    sa.Column('rigger_level_critical_min', sa.Integer(), nullable=False),
    sa.Column('trade_cert_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hook_transition_days', sa.Integer(), nullable=False),
    sa.Column('hook_critical_codes', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('hook_critical_transition_days', sa.Integer(), nullable=False),
    sa.Column('lifting_gear_colour_scheme', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('equipment_cert_warning_pct', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('personnel_cert_warning_pct', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('scaffold_tag_warning_pct', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('dangerous_defect_warning_count', sa.Integer(), nullable=False),
    sa.Column('ban_review_months', sa.Integer(), nullable=False),
    sa.Column('cert_scan_retention_years', sa.Integer(), nullable=False),
    sa.Column('alert_schedule_long_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_cert_settings_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_project_cert_settings_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_cert_settings'))
    )
    op.create_table('tpis',
    sa.Column('tpi_code', sa.String(length=12), nullable=False),
    sa.Column('legal_name_en', sa.String(length=200), nullable=False),
    sa.Column('legal_name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_norm_en', sa.String(length=200), nullable=False),
    sa.Column('name_norm_ar', sa.String(length=200), nullable=False),
    sa.Column('kinds', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('cr_number', sa.String(length=10), nullable=True),
    sa.Column('foreign_reg_no', sa.String(length=30), nullable=True),
    sa.Column('verification_portal_url', sa.String(length=300), nullable=True),
    sa.Column('verification_domains', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('verification_email', sa.String(length=254), nullable=True),
    sa.Column('verification_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_mobile', sa.String(length=20), nullable=True),
    sa.Column('affiliated_contractor_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'suspended', 'blacklisted', name='tpistatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('blacklist_scope', sa.Enum('all_certificates', 'issued_from', name='tpiblacklistscope', native_enum=False, length=40), nullable=True),
    sa.Column('blacklist_from', sa.Date(), nullable=True),
    sa.Column('blacklisted_on', sa.Date(), nullable=True),
    sa.Column('suspension_periods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_tpis_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_tpis_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_tpis_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tpis')),
    sa.UniqueConstraint('name_norm_ar', name=op.f('uq_tpis_name_norm_ar')),
    sa.UniqueConstraint('name_norm_en', name=op.f('uq_tpis_name_norm_en')),
    sa.UniqueConstraint('tpi_code', name=op.f('uq_tpis_tpi_code'))
    )
    op.create_table('cert_import_batches',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('template', sa.Enum('equipment_certificates', 'personnel_certificates', name='certimporttemplate', native_enum=False, length=40), nullable=False),
    sa.Column('source', sa.Enum('contractor_file', 'tpi_register_file', name='certimportsource', native_enum=False, length=40), nullable=False),
    sa.Column('tpi_id', sa.Uuid(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('create_items', sa.Boolean(), nullable=False),
    sa.Column('scans_zip_name', sa.String(length=255), nullable=True),
    sa.Column('scans_count', sa.Integer(), nullable=True),
    sa.Column('scan_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_file_name', sa.String(length=255), nullable=True),
    sa.Column('evidence_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('validated', 'committed', 'discarded', 'expired', name='certimportstatus', native_enum=False, length=40), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('committed_certificate_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_cert_import_batches_project_id_projects')),
    sa.ForeignKeyConstraint(['tpi_id'], ['tpis.id'], name=op.f('fk_cert_import_batches_tpi_id_tpis')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_cert_import_batches_uploaded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cert_import_batches'))
    )
    op.create_index(op.f('ix_cert_import_batches_file_sha256'), 'cert_import_batches', ['file_sha256'], unique=False)
    op.create_index(op.f('ix_cert_import_batches_project_id'), 'cert_import_batches', ['project_id'], unique=False)
    op.create_table('cert_verifications',
    sa.Column('cert_kind', sa.Enum('equipment', 'personnel', name='certkind', native_enum=False, length=40), nullable=False),
    sa.Column('cert_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('tpi_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.Enum('tpi_portal', 'tpi_qr_url', 'tpi_email', 'tpi_phone', 'tpi_register_file', 'client_register', 'original_sighted', name='certverificationmethod', native_enum=False, length=40), nullable=False),
    sa.Column('channel_used', sa.String(length=200), nullable=False),
    sa.Column('outcome', sa.Enum('confirmed', 'not_found', 'details_differ', 'revoked_by_tpi', 'no_response', name='verificationoutcome', native_enum=False, length=40), nullable=False),
    sa.Column('differences', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('differences_text', sa.String(length=300), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('evidence_attachment_id', sa.UUID(), nullable=True),
    sa.Column('performed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('counts_as_verification', sa.Boolean(), nullable=False),
    sa.Column('verification_status_after', sa.Enum('not_verified', 'verified', 'failed', 'unable_to_verify', name='verificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], name=op.f('fk_cert_verifications_performed_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_cert_verifications_project_id_projects')),
    sa.ForeignKeyConstraint(['tpi_id'], ['tpis.id'], name=op.f('fk_cert_verifications_tpi_id_tpis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cert_verifications'))
    )
    op.create_index('ix_cert_verification_cert', 'cert_verifications', ['cert_kind', 'cert_id'], unique=False)
    op.create_index(op.f('ix_cert_verifications_project_id'), 'cert_verifications', ['project_id'], unique=False)
    op.create_table('certification_bans',
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('scope_all', sa.Boolean(), nullable=False),
    sa.Column('cert_types', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('reason_code', sa.Enum('forged_certificate', 'certificate_misuse', 'unsafe_operation', 'incident_investigation', 'other', name='banreason', native_enum=False, length=40), nullable=False),
    sa.Column('reason_text', sa.String(length=500), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('review_due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'lifted', name='banstatus', native_enum=False, length=40), nullable=False),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('lift_reason', sa.String(length=500), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_certification_bans_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['lifted_by_user_id'], ['users.id'], name=op.f('fk_certification_bans_lifted_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_certification_bans_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_certification_bans_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certification_bans'))
    )
    op.create_index(op.f('ix_certification_bans_worker_id'), 'certification_bans', ['worker_id'], unique=False)
    op.create_table('equipment_items',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('equipment_no', sa.String(length=12), nullable=False),
    sa.Column('category', sa.Enum('tower_crane', 'mobile_crane', 'crawler_crane', 'loader_crane', 'overhead_gantry_crane', 'construction_hoist', 'mast_climber', 'bmu', 'mewp', 'man_basket', 'forklift', 'telehandler', 'excavator', 'wheel_loader', 'piling_rig', 'concrete_pump_boom', 'lifting_accessory', 'tripod_winch', 'pressure_vessel', 'scaffold', name='equipmentcertcategory', native_enum=False, length=40), nullable=False),
    sa.Column('subtype', sa.Enum('flat_top', 'hammerhead', 'luffing', 'scissor', 'boom', 'vertical_mast', 'wire_rope_sling', 'chain_sling', 'synthetic_sling', 'shackle', 'hook', 'eyebolt', 'spreader_beam', 'lifting_beam', 'plate_clamp', 'chain_block', 'lever_hoist', 'beam_clamp', 'air_receiver', 'hydraulic_accumulator', 'other', name='equipmentsubtype', native_enum=False, length=40), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=False),
    sa.Column('manufacturer_norm', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('serial_no', sa.String(length=40), nullable=False),
    sa.Column('serial_norm', sa.String(length=40), nullable=False),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=False),
    sa.Column('owner_contractor_id', sa.Uuid(), nullable=False),
    sa.Column('hired_from', sa.String(length=120), nullable=True),
    sa.Column('owner_fleet_no', sa.String(length=20), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('rated_capacity_t', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('max_radius_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_height_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('persons_capacity', sa.Integer(), nullable=True),
    sa.Column('pressure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lifting_duty', sa.Boolean(), nullable=False),
    sa.Column('safety_devices', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('service_status', sa.Enum('awaiting_certificate', 'in_service', 'quarantined', 'out_of_service', 'blacklisted', 'retired', name='servicestatus', native_enum=False, length=40), nullable=False),
    sa.Column('service_status_reason', sa.Enum('awaiting_certificate', 'certificate_expired', 'certificate_suspended', 'certificate_revoked', 'certificate_unverified', 'configuration_changed', 'failed_inspection', 'defect_a', 'defect_b_overdue', 'tpi_blacklisted', 'manual_tag_out', 'blacklisted', 'retired_destroyed', 'retired_sold', 'retired_other', name='servicestatusreason', native_enum=False, length=40), nullable=True),
    sa.Column('service_status_text', sa.String(length=500), nullable=True),
    sa.Column('service_status_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tagged_out_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_equipment_items_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['owner_contractor_id'], ['contractors.id'], name=op.f('fk_equipment_items_owner_contractor_id_contractors')),
    sa.ForeignKeyConstraint(['tagged_out_by_user_id'], ['users.id'], name=op.f('fk_equipment_items_tagged_out_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_equipment_items_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_equipment_items_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_items')),
    sa.UniqueConstraint('equipment_no', name=op.f('uq_equipment_items_equipment_no')),
    sa.UniqueConstraint('manufacturer_norm', 'serial_norm', name=op.f('uq_equipment_items_manufacturer_norm')),
    sa.UniqueConstraint('seq', name=op.f('uq_equipment_items_seq')),
    sa.UniqueConstraint('vehicle_id', name=op.f('uq_equipment_items_vehicle_id'))
    )
    op.create_index(op.f('ix_equipment_items_serial_norm'), 'equipment_items', ['serial_norm'], unique=False)
    op.create_table('personnel_certificates',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('record_no', sa.String(length=12), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('cert_type', sa.String(length=40), nullable=False),
    sa.Column('tpi_id', sa.Uuid(), nullable=False),
    sa.Column('cert_no', sa.String(length=40), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('printed_expiry', sa.Date(), nullable=True),
    sa.Column('cap_end', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('limiting_factor', sa.Enum('printed_next_due', 'category_interval', 'printed_expiry', 'cap', name='certlimitingfactor', native_enum=False, length=40), nullable=True),
    sa.Column('scope_categories', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('max_capacity_t', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('level', sa.Enum('1', '2', '3', 'I', 'II', 'III', 'basic', 'advanced', name='certlevel', native_enum=False, length=40), nullable=True),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('medical_restriction_on_card', sa.Boolean(), nullable=False),
    sa.Column('restriction_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restriction_reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('name_as_printed', sa.String(length=120), nullable=True),
    sa.Column('id_match_result', sa.Enum('matched', 'matched_previous_id', 'not_shown', name='idmatchresult', native_enum=False, length=40), nullable=False),
    sa.Column('name_match', sa.Enum('exact', 'partial', 'none', name='namematch', native_enum=False, length=40), nullable=False),
    sa.Column('identity_confirmed_by_tpi', sa.Boolean(), nullable=False),
    sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scan_front_attachment_id', sa.UUID(), nullable=True),
    sa.Column('scan_back_attachment_id', sa.UUID(), nullable=True),
    sa.Column('scans_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tpi_verification_url', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'accepted', 'rejected', 'superseded', 'suspended', 'revoked', 'expired', 'historic', name='certificatestatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.Enum('configuration_changed', 'verification_failed', 'tpi_blacklisted', 'tpi_revocation_notice', 'tpi_suspension_notice', 'hse_suspension', 'document_review', 'newer_certificate', 'other', name='certstatusreason', native_enum=False, length=40), nullable=True),
    sa.Column('status_reason_text', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.Enum('not_verified', 'verified', 'failed', 'unable_to_verify', name='verificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('verification_due_on', sa.Date(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'import', 'tpi_register_file', name='certsource', native_enum=False, length=40), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_force_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('anonymised', sa.Boolean(), nullable=False),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_personnel_certificates_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_personnel_certificates_project_id_projects')),
    sa.ForeignKeyConstraint(['restriction_reviewed_by_user_id'], ['users.id'], name=op.f('fk_personnel_certificates_restriction_reviewed_by_user_id_users')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_personnel_certificates_reviewed_by_user_id_users')),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_personnel_certificates_submitted_by_user_id_users')),
    sa.ForeignKeyConstraint(['tpi_id'], ['tpis.id'], name=op.f('fk_personnel_certificates_tpi_id_tpis')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_personnel_certificates_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_personnel_certificates_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personnel_certificates')),
    sa.UniqueConstraint('record_no', name=op.f('uq_personnel_certificates_record_no')),
    sa.UniqueConstraint('seq', name=op.f('uq_personnel_certificates_seq')),
    sa.UniqueConstraint('tpi_id', 'cert_type', 'cert_no', name=op.f('uq_personnel_certificates_tpi_id'))
    )
    op.create_index('ix_personnel_cert_worker', 'personnel_certificates', ['worker_id', 'cert_type'], unique=False)
    op.create_index(op.f('ix_personnel_certificates_project_id'), 'personnel_certificates', ['project_id'], unique=False)
    op.create_table('scaffolds',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('scaffold_no', sa.String(length=40), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('location_desc', sa.String(length=150), nullable=False),
    sa.Column('level_code', sa.String(length=10), nullable=True),
    sa.Column('grid_x_m', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('grid_y_m', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('scaffold_type', sa.Enum('independent_tied', 'system_modular', 'mobile_tower', 'birdcage', 'cantilever', 'suspended_hanging', 'loading_bay', 'other', name='scaffoldtype', native_enum=False, length=40), nullable=False),
    sa.Column('height_m', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('load_class', sa.Integer(), nullable=False),
    sa.Column('design_ref', sa.String(length=40), nullable=True),
    sa.Column('sheeting_fitted', sa.Boolean(), nullable=False),
    sa.Column('erection_supervisor_worker_id', sa.Uuid(), nullable=False),
    sa.Column('erection_crew_worker_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.Enum('under_erection', 'in_use', 'closed_red', 'under_alteration', 'dismantled', name='scaffoldstatus', native_enum=False, length=40), nullable=False),
    sa.Column('tag_status', sa.Enum('none', 'green', 'yellow', 'red', 'expired', 'inspection_required', name='scaffoldtagstatus', native_enum=False, length=40), nullable=False),
    sa.Column('tag_valid_until', sa.Date(), nullable=True),
    sa.Column('restrictions_en', sa.String(length=300), nullable=True),
    sa.Column('restrictions_ar', sa.String(length=300), nullable=True),
    sa.Column('inspection_required_reason', sa.Enum('adverse_weather', 'nearby_impact', 'incident', 'ops_event', 'other', name='reinspectionreason', native_enum=False, length=40), nullable=True),
    sa.Column('inspection_required_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_inspection_id', sa.UUID(), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_scaffolds_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_scaffolds_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['erection_supervisor_worker_id'], ['workers.id'], name=op.f('fk_scaffolds_erection_supervisor_worker_id_workers')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scaffolds_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_scaffolds_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_scaffolds_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scaffolds')),
    sa.UniqueConstraint('scaffold_no', name=op.f('uq_scaffolds_scaffold_no'))
    )
    op.create_index('ix_scaffold_project_tag', 'scaffolds', ['project_id', 'tag'], unique=False)
    op.create_index(op.f('ix_scaffolds_project_id'), 'scaffolds', ['project_id'], unique=False)
    op.create_table('tpi_accreditations',
    sa.Column('tpi_id', sa.Uuid(), nullable=False),
    sa.Column('accreditation_body', sa.Enum('sac', 'ilac_mra_other', 'client', name='accreditationbody', native_enum=False, length=40), nullable=False),
    sa.Column('standard', sa.Enum('iso_iec_17020', 'iso_iec_17024', 'iso_iec_17025', 'client_scheme', name='accreditationstandard', native_enum=False, length=40), nullable=False),
    sa.Column('accreditation_no', sa.String(length=40), nullable=False),
    sa.Column('scope_categories', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('scope_cert_types', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('certificate_attachment_id', sa.UUID(), nullable=True),
    sa.Column('register_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('register_checked_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('register_check_note', sa.String(length=300), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_tpi_accreditations_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['register_checked_by_user_id'], ['users.id'], name=op.f('fk_tpi_accreditations_register_checked_by_user_id_users')),
    sa.ForeignKeyConstraint(['tpi_id'], ['tpis.id'], name=op.f('fk_tpi_accreditations_tpi_id_tpis')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_tpi_accreditations_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tpi_accreditations')),
    sa.UniqueConstraint('accreditation_body', 'accreditation_no', name=op.f('uq_tpi_accreditations_accreditation_body'))
    )
    op.create_index(op.f('ix_tpi_accreditations_tpi_id'), 'tpi_accreditations', ['tpi_id'], unique=False)
    op.create_table('tpi_client_approvals',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('tpi_id', sa.Uuid(), nullable=False),
    sa.Column('approval_ref', sa.String(length=40), nullable=False),
    sa.Column('scope_categories', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('scope_cert_types', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'withdrawn', name='clientapprovalstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_tpi_client_approvals_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tpi_client_approvals_project_id_projects')),
    sa.ForeignKeyConstraint(['tpi_id'], ['tpis.id'], name=op.f('fk_tpi_client_approvals_tpi_id_tpis')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_tpi_client_approvals_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tpi_client_approvals')),
    sa.UniqueConstraint('project_id', 'tpi_id', name=op.f('uq_tpi_client_approvals_project_id'))
    )
    op.create_index(op.f('ix_tpi_client_approvals_project_id'), 'tpi_client_approvals', ['project_id'], unique=False)
    op.create_table('equipment_blacklist_events',
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('reason_code', sa.Enum('forged_certificate', 'identity_unverifiable', 'structural_damage', 'repeated_dangerous_defects', 'recall_unresolved', 'other', name='equipmentblacklistreason', native_enum=False, length=40), nullable=False),
    sa.Column('reason_text', sa.String(length=500), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('by_user_id', sa.Uuid(), nullable=True),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('lift_reason', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['by_user_id'], ['users.id'], name=op.f('fk_equipment_blacklist_events_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_equipment_blacklist_events_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_items.id'], name=op.f('fk_equipment_blacklist_events_equipment_id_equipment_items')),
    sa.ForeignKeyConstraint(['lifted_by_user_id'], ['users.id'], name=op.f('fk_equipment_blacklist_events_lifted_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_equipment_blacklist_events_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_blacklist_events'))
    )
    op.create_index(op.f('ix_equipment_blacklist_events_equipment_id'), 'equipment_blacklist_events', ['equipment_id'], unique=False)
    op.create_table('equipment_configuration_events',
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('erection', 'climb_jacking', 'jib_change', 'tie_in_change', 'relocation', 'mast_extension', 'major_repair', 'storm_exceedance', 'boom_configuration_change', name='configurationeventtype', native_enum=False, length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_configuration', sa.String(length=100), nullable=False),
    sa.Column('new_height_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('late_record', sa.Boolean(), nullable=False),
    sa.Column('suspended_line_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('cleared_by_line_id', sa.UUID(), nullable=True),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('obstacle_refs', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_equipment_configuration_events_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_items.id'], name=op.f('fk_equipment_configuration_events_equipment_id_equipment_items')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_equipment_configuration_events_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_equipment_configuration_events_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_configuration_events'))
    )
    op.create_index(op.f('ix_equipment_configuration_events_equipment_id'), 'equipment_configuration_events', ['equipment_id'], unique=False)
    op.create_table('equipment_defects',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('defect_no', sa.String(length=40), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('scaffold_id', sa.Uuid(), nullable=True),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('tpi_inspection', 'pre_use_check', 'arrival_inspection', 'site_inspection', 'incident', 'observation', 'ptw_audit', 'operator_report', 'other', name='defectsource', native_enum=False, length=40), nullable=False),
    sa.Column('source_ref', sa.String(length=40), nullable=True),
    sa.Column('cert_line_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('A', 'B', 'C', name='defectcategory', native_enum=False, length=40), nullable=False),
    sa.Column('description_en', sa.String(length=1000), nullable=False),
    sa.Column('description_ar', sa.String(length=1000), nullable=True),
    sa.Column('photo_attachment_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('raised_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('raised_by_worker_id', sa.Uuid(), nullable=True),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('physical_tag_applied', sa.Boolean(), nullable=False),
    sa.Column('tpi_due_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('rectification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rectified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('rectified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('closed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'rectified', 'closed', 'cancelled', name='defectstatus', native_enum=False, length=40), nullable=False),
    sa.Column('cancelled_reason', sa.String(length=500), nullable=True),
    sa.Column('overdue_applied', sa.Boolean(), nullable=False),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], name=op.f('fk_equipment_defects_closed_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_equipment_defects_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_equipment_defects_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_items.id'], name=op.f('fk_equipment_defects_equipment_id_equipment_items')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_equipment_defects_project_id_projects')),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], name=op.f('fk_equipment_defects_raised_by_user_id_users')),
    sa.ForeignKeyConstraint(['raised_by_worker_id'], ['workers.id'], name=op.f('fk_equipment_defects_raised_by_worker_id_workers')),
    sa.ForeignKeyConstraint(['rectified_by_user_id'], ['users.id'], name=op.f('fk_equipment_defects_rectified_by_user_id_users')),
    sa.ForeignKeyConstraint(['scaffold_id'], ['scaffolds.id'], name=op.f('fk_equipment_defects_scaffold_id_scaffolds')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_equipment_defects_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_defects')),
    sa.UniqueConstraint('defect_no', name=op.f('uq_equipment_defects_defect_no'))
    )
    op.create_index('ix_defect_item', 'equipment_defects', ['equipment_id'], unique=False)
    op.create_index('ix_defect_project_raised', 'equipment_defects', ['project_id', 'raised_at'], unique=False)
    op.create_table('equipment_deployments',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('deployment_no', sa.String(length=40), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=False),
    sa.Column('site_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('planned_arrival_on', sa.Date(), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_inspection', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('arrival_inspection_passed', sa.Boolean(), nullable=False),
    sa.Column('demobilised_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'approved', 'on_site', 'demobilised', 'cancelled', name='equipmentdeploymentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_equipment_deployments_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_equipment_deployments_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_equipment_deployments_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_items.id'], name=op.f('fk_equipment_deployments_equipment_id_equipment_items')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_equipment_deployments_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_equipment_deployments_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_equipment_deployments_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_deployments')),
    sa.UniqueConstraint('deployment_no', name=op.f('uq_equipment_deployments_deployment_no'))
    )
    op.create_index('ix_eq_deployment_item', 'equipment_deployments', ['equipment_id'], unique=False)
    op.create_index('ix_eq_deployment_project_tag', 'equipment_deployments', ['project_id', 'tag'], unique=False)
    op.create_index(op.f('ix_equipment_deployments_project_id'), 'equipment_deployments', ['project_id'], unique=False)
    op.create_table('equipment_status_events',
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_status', sa.Enum('awaiting_certificate', 'in_service', 'quarantined', 'out_of_service', 'blacklisted', 'retired', name='servicestatus', native_enum=False, length=40), nullable=True),
    sa.Column('to_status', sa.Enum('awaiting_certificate', 'in_service', 'quarantined', 'out_of_service', 'blacklisted', 'retired', name='servicestatus', native_enum=False, length=40), nullable=False),
    sa.Column('reason', sa.Enum('awaiting_certificate', 'certificate_expired', 'certificate_suspended', 'certificate_revoked', 'certificate_unverified', 'configuration_changed', 'failed_inspection', 'defect_a', 'defect_b_overdue', 'tpi_blacklisted', 'manual_tag_out', 'blacklisted', 'retired_destroyed', 'retired_sold', 'retired_other', name='servicestatusreason', native_enum=False, length=40), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('ref', sa.String(length=60), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_equipment_status_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_items.id'], name=op.f('fk_equipment_status_events_equipment_id_equipment_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_status_events'))
    )
    op.create_index('ix_eq_status_event_item', 'equipment_status_events', ['equipment_id', 'occurred_at'], unique=False)
    op.create_table('scaffold_inspections',
    sa.Column('scaffold_id', sa.Uuid(), nullable=False),
    sa.Column('inspection_type', sa.Enum('handover', 'periodic', 'after_alteration', 'after_adverse_weather', 'after_incident', name='scaffoldinspectiontype', native_enum=False, length=40), nullable=False),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inspector_worker_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.Enum('green', 'yellow', 'red', name='scaffoldinspectionresult', native_enum=False, length=40), nullable=False),
    sa.Column('restrictions_en', sa.String(length=300), nullable=True),
    sa.Column('restrictions_ar', sa.String(length=300), nullable=True),
    sa.Column('tag_valid_until', sa.Date(), nullable=True),
    sa.Column('photo_attachment_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inspector_worker_id'], ['workers.id'], name=op.f('fk_scaffold_inspections_inspector_worker_id_workers')),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_scaffold_inspections_recorded_by_user_id_users')),
    sa.ForeignKeyConstraint(['scaffold_id'], ['scaffolds.id'], name=op.f('fk_scaffold_inspections_scaffold_id_scaffolds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scaffold_inspections'))
    )
    op.create_index('ix_scaffold_inspection', 'scaffold_inspections', ['scaffold_id', 'inspected_at'], unique=False)
    op.create_table('equipment_certificates',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('tpi_id', sa.Uuid(), nullable=False),
    sa.Column('cert_no', sa.String(length=40), nullable=False),
    sa.Column('inspection_type', sa.Enum('initial', 'periodic', 'after_repair', 'after_configuration_change', 'after_incident', 'pre_mobilisation', name='certinspectiontype', native_enum=False, length=40), nullable=False),
    sa.Column('inspected_on', sa.Date(), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('printed_next_due', sa.Date(), nullable=True),
    sa.Column('inspector_name', sa.String(length=120), nullable=False),
    sa.Column('inspector_staff_no', sa.String(length=30), nullable=True),
    sa.Column('scan_attachment_id', sa.UUID(), nullable=True),
    sa.Column('tpi_verification_url', sa.String(length=300), nullable=True),
    sa.Column('configuration_event_id', sa.Uuid(), nullable=True),
    sa.Column('configuration_mismatch_confirmed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'accepted', 'rejected', 'superseded', 'suspended', 'revoked', 'expired', 'historic', name='certificatestatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.Enum('configuration_changed', 'verification_failed', 'tpi_blacklisted', 'tpi_revocation_notice', 'tpi_suspension_notice', 'hse_suspension', 'document_review', 'newer_certificate', 'other', name='certstatusreason', native_enum=False, length=40), nullable=True),
    sa.Column('status_reason_text', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.Enum('not_verified', 'verified', 'failed', 'unable_to_verify', name='verificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('verification_due_on', sa.Date(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'import', 'tpi_register_file', name='certsource', native_enum=False, length=40), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_force_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['configuration_event_id'], ['equipment_configuration_events.id'], name=op.f('fk_equipment_certificates_configuration_event_id_equipment_configuration_events')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_equipment_certificates_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_equipment_certificates_project_id_projects')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_equipment_certificates_reviewed_by_user_id_users')),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_equipment_certificates_submitted_by_user_id_users')),
    sa.ForeignKeyConstraint(['tpi_id'], ['tpis.id'], name=op.f('fk_equipment_certificates_tpi_id_tpis')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_equipment_certificates_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_certificates')),
    sa.UniqueConstraint('tpi_id', 'cert_no', name=op.f('uq_equipment_certificates_tpi_id'))
    )
    op.create_index(op.f('ix_equipment_certificates_project_id'), 'equipment_certificates', ['project_id'], unique=False)
    op.create_table('equipment_cert_lines',
    sa.Column('certificate_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('serial_as_printed', sa.String(length=40), nullable=False),
    sa.Column('result', sa.Enum('pass', 'pass_with_conditions', 'fail', name='lineresult', native_enum=False, length=40), nullable=False),
    sa.Column('swl_t', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('configuration_ref', sa.String(length=100), nullable=True),
    sa.Column('load_test', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('structural_repair', sa.Boolean(), nullable=False),
    sa.Column('lifting_duty_certified', sa.Boolean(), nullable=False),
    sa.Column('colour_code', sa.Enum('red', 'yellow', 'blue', 'green', 'white', 'orange', 'black', 'brown', name='liftinggearcolour', native_enum=False, length=40), nullable=True),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('defects_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interval_end', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('limiting_factor', sa.Enum('printed_next_due', 'category_interval', 'printed_expiry', 'cap', name='certlimitingfactor', native_enum=False, length=40), nullable=True),
    sa.Column('superseded_by_line_id', sa.UUID(), nullable=True),
    sa.Column('suspended_for_configuration', sa.Boolean(), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['equipment_certificates.id'], name=op.f('fk_equipment_cert_lines_certificate_id_equipment_certificates')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_items.id'], name=op.f('fk_equipment_cert_lines_equipment_id_equipment_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_cert_lines')),
    sa.UniqueConstraint('certificate_id', 'equipment_id', name=op.f('uq_equipment_cert_lines_certificate_id'))
    )
    op.create_index('ix_eq_cert_line_item', 'equipment_cert_lines', ['equipment_id'], unique=False)
    op.add_column('gas_detectors', sa.Column('calibration_body_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_gas_detectors_calibration_body_id_tpis'), 'gas_detectors', 'tpis', ['calibration_body_id'], ['id'])
    op.add_column('gate_checks', sa.Column('equipment_deployment_id', sa.UUID(), nullable=True))
    op.add_column('obstacle_clearances', sa.Column('equipment_item_id', sa.UUID(), nullable=True))
    op.add_column('permit_equipment', sa.Column('equipment_item_id', sa.UUID(), nullable=True))
    op.add_column('permit_equipment', sa.Column('deployment_id', sa.UUID(), nullable=True))
    op.add_column('permit_equipment', sa.Column('operator_worker_id', sa.Uuid(), nullable=True))
    op.add_column('permit_equipment', sa.Column('operator_hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.alter_column('permit_equipment', 'operator_hooks', server_default=None)
    op.add_column('permit_equipment', sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.alter_column('permit_equipment', 'conditions', server_default=None)
    op.add_column('permit_equipment', sa.Column('swl_t', sa.Numeric(precision=8, scale=3), nullable=True))
    op.create_foreign_key(op.f('fk_permit_equipment_operator_worker_id_workers'), 'permit_equipment', 'workers', ['operator_worker_id'], ['id'])
    op.add_column('permits', sa.Column('scaffold_hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.alter_column('permits', 'scaffold_hooks', server_default=None)
    op.add_column('permits', sa.Column('hook_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.alter_column('permits', 'hook_conditions', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permits', 'hook_conditions')
    op.drop_column('permits', 'scaffold_hooks')
    op.drop_constraint(op.f('fk_permit_equipment_operator_worker_id_workers'), 'permit_equipment', type_='foreignkey')
    op.drop_column('permit_equipment', 'swl_t')
    op.drop_column('permit_equipment', 'conditions')
    op.drop_column('permit_equipment', 'operator_hooks')
    op.drop_column('permit_equipment', 'operator_worker_id')
    op.drop_column('permit_equipment', 'deployment_id')
    op.drop_column('permit_equipment', 'equipment_item_id')
    op.drop_column('obstacle_clearances', 'equipment_item_id')
    op.drop_column('gate_checks', 'equipment_deployment_id')
    op.drop_constraint(op.f('fk_gas_detectors_calibration_body_id_tpis'), 'gas_detectors', type_='foreignkey')
    op.drop_column('gas_detectors', 'calibration_body_id')
    op.drop_index('ix_eq_cert_line_item', table_name='equipment_cert_lines')
    op.drop_table('equipment_cert_lines')
    op.drop_index(op.f('ix_equipment_certificates_project_id'), table_name='equipment_certificates')
    op.drop_table('equipment_certificates')
    op.drop_index('ix_scaffold_inspection', table_name='scaffold_inspections')
    op.drop_table('scaffold_inspections')
    op.drop_index('ix_eq_status_event_item', table_name='equipment_status_events')
    op.drop_table('equipment_status_events')
    op.drop_index(op.f('ix_equipment_deployments_project_id'), table_name='equipment_deployments')
    op.drop_index('ix_eq_deployment_project_tag', table_name='equipment_deployments')
    op.drop_index('ix_eq_deployment_item', table_name='equipment_deployments')
    op.drop_table('equipment_deployments')
    op.drop_index('ix_defect_project_raised', table_name='equipment_defects')
    op.drop_index('ix_defect_item', table_name='equipment_defects')
    op.drop_table('equipment_defects')
    op.drop_index(op.f('ix_equipment_configuration_events_equipment_id'), table_name='equipment_configuration_events')
    op.drop_table('equipment_configuration_events')
    op.drop_index(op.f('ix_equipment_blacklist_events_equipment_id'), table_name='equipment_blacklist_events')
    op.drop_table('equipment_blacklist_events')
    op.drop_index(op.f('ix_tpi_client_approvals_project_id'), table_name='tpi_client_approvals')
    op.drop_table('tpi_client_approvals')
    op.drop_index(op.f('ix_tpi_accreditations_tpi_id'), table_name='tpi_accreditations')
    op.drop_table('tpi_accreditations')
    op.drop_index(op.f('ix_scaffolds_project_id'), table_name='scaffolds')
    op.drop_index('ix_scaffold_project_tag', table_name='scaffolds')
    op.drop_table('scaffolds')
    op.drop_index(op.f('ix_personnel_certificates_project_id'), table_name='personnel_certificates')
    op.drop_index('ix_personnel_cert_worker', table_name='personnel_certificates')
    op.drop_table('personnel_certificates')
    op.drop_index(op.f('ix_equipment_items_serial_norm'), table_name='equipment_items')
    op.drop_table('equipment_items')
    op.drop_index(op.f('ix_certification_bans_worker_id'), table_name='certification_bans')
    op.drop_table('certification_bans')
    op.drop_index(op.f('ix_cert_verifications_project_id'), table_name='cert_verifications')
    op.drop_index('ix_cert_verification_cert', table_name='cert_verifications')
    op.drop_table('cert_verifications')
    op.drop_index(op.f('ix_cert_import_batches_project_id'), table_name='cert_import_batches')
    op.drop_index(op.f('ix_cert_import_batches_file_sha256'), table_name='cert_import_batches')
    op.drop_table('cert_import_batches')
    op.drop_table('tpis')
    op.drop_table('project_cert_settings')
    op.drop_table('hook_policy_states')
    op.drop_table('cert_types')
    # ### end Alembic commands ###
