"""foundation schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 22:12:19.283494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.Enum('hse_manager', 'hse_officer', 'site_engineer', 'permit_issuer', 'permit_receiver', 'contractor_hse_rep', 'viewer_client', name='role', native_enum=False, length=40), nullable=True),
    sa.Column('on_behalf_project_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('action', sa.Enum('login_success', 'login_failed', 'logout', 'account_locked', 'password_reset_requested', 'password_changed', 'mfa_changed', 'user_invited', 'user_status_changed', 'role_assigned', 'role_revoked', 'create', 'update', 'status_change', 'archive', 'settings_changed', 'sensitive_field_read', 'export', 'access_denied', 'audit_log_viewed', 'audit_chain_verified', 'retention_purge', 'privacy_notice_acknowledged', name='auditaction', native_enum=False, length=40), nullable=False),
    sa.Column('entity_type', sa.Enum('project', 'site', 'zone', 'contractor', 'project_engagement', 'user', 'role_assignment', 'project_settings', 'audit_log', name='entitytype', native_enum=False, length=40), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fields_read', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.Enum('success', 'denied', 'failed', name='auditresult', native_enum=False, length=40), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    sa.UniqueConstraint('seq', name=op.f('uq_audit_log_seq'))
    )
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_index('ix_audit_log_project_occurred', 'audit_log', ['project_id', 'occurred_at'], unique=False)
    op.create_table('contractors',
    sa.Column('legal_name_en', sa.String(length=200), nullable=False),
    sa.Column('legal_name_ar', sa.String(length=200), nullable=False),
    sa.Column('legal_name_en_norm', sa.String(length=200), nullable=False),
    sa.Column('legal_name_ar_norm', sa.String(length=200), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('cr_number', sa.String(length=10), nullable=False),
    sa.Column('cr_expiry_date', sa.Date(), nullable=True),
    sa.Column('vat_number', sa.String(length=15), nullable=True),
    sa.Column('contractor_category', sa.Enum('civil', 'mep', 'steel', 'airfield', 'scaffolding', 'lifting', 'facade', 'specialist', 'consultant', 'other', name='contractorcategory', native_enum=False, length=40), nullable=False),
    sa.Column('primary_contact_name', sa.String(length=120), nullable=False),
    sa.Column('primary_contact_mobile', sa.String(length=16), nullable=False),
    sa.Column('primary_contact_email', sa.String(length=254), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'suspended', 'demobilised', 'blacklisted', name='contractorstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('cr_alerts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contractors')),
    sa.UniqueConstraint('cr_number', name=op.f('uq_contractors_cr_number')),
    sa.UniqueConstraint('legal_name_ar_norm', name=op.f('uq_contractors_legal_name_ar_norm')),
    sa.UniqueConstraint('legal_name_en_norm', name=op.f('uq_contractors_legal_name_en_norm')),
    sa.UniqueConstraint('short_code', name=op.f('uq_contractors_short_code'))
    )
    op.create_table('projects',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('project_type', sa.Enum('airport', 'building_highrise', 'infrastructure', 'industrial', 'other', name='projecttype', native_enum=False, length=40), nullable=False),
    sa.Column('client_name_en', sa.String(length=150), nullable=False),
    sa.Column('client_name_ar', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('planning', 'active', 'on_hold', 'closed', name='projectstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('airport_icao', sa.String(length=4), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('code', name=op.f('uq_projects_code'))
    )
    op.create_table('project_engagements',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('contractor_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('parent_engagement_id', sa.Uuid(), nullable=True),
    sa.Column('root_engagement_id', sa.Uuid(), nullable=True),
    sa.Column('scope_of_work_en', sa.String(length=500), nullable=False),
    sa.Column('scope_of_work_ar', sa.String(length=500), nullable=False),
    sa.Column('site_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('mobilisation_date', sa.Date(), nullable=False),
    sa.Column('demobilisation_date', sa.Date(), nullable=True),
    sa.Column('parent_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_project_engagements_contractor_id_contractors')),
    sa.ForeignKeyConstraint(['parent_engagement_id'], ['project_engagements.id'], name=op.f('fk_project_engagements_parent_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_engagements_project_id_projects')),
    sa.ForeignKeyConstraint(['root_engagement_id'], ['project_engagements.id'], name=op.f('fk_project_engagements_root_engagement_id_project_engagements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_engagements')),
    sa.UniqueConstraint('project_id', 'contractor_id', name='uq_engagement_project_contractor')
    )
    op.create_index(op.f('ix_project_engagements_contractor_id'), 'project_engagements', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_project_engagements_parent_engagement_id'), 'project_engagements', ['parent_engagement_id'], unique=False)
    op.create_index(op.f('ix_project_engagements_project_id'), 'project_engagements', ['project_id'], unique=False)
    op.create_table('sites',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('site_side', sa.Enum('airside', 'landside', 'mixed', 'other', name='siteside', native_enum=False, length=40), nullable=False),
    sa.Column('gps_lat', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=True),
    sa.Column('gps_lng', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='sitestatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sites_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('project_id', 'code', name='uq_sites_project_code')
    )
    op.create_index(op.f('ix_sites_project_id'), 'sites', ['project_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name_en', sa.String(length=120), nullable=False),
    sa.Column('full_name_ar', sa.String(length=120), nullable=True),
    sa.Column('mobile', sa.String(length=16), nullable=True),
    sa.Column('employer_type', sa.Enum('client', 'pmc_consultant', 'contractor', name='employertype', native_enum=False, length=40), nullable=False),
    sa.Column('employer_contractor_id', sa.Uuid(), nullable=True),
    sa.Column('job_title', sa.String(length=80), nullable=True),
    sa.Column('preferred_language', sa.Enum('en', 'ar', name='language', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('invited', 'active', 'locked', 'deactivated', name='userstatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('failed_window_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('privacy_notice_version', sa.String(length=20), nullable=True),
    sa.Column('privacy_notice_ack_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inactivity_warned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employer_contractor_id'], ['contractors.id'], name=op.f('fk_users_employer_contractor_id_contractors')),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_users_invited_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_employer_contractor_id'), 'users', ['employer_contractor_id'], unique=False)
    op.create_table('email_outbox',
    sa.Column('to_email', sa.String(length=254), nullable=False),
    sa.Column('to_user_id', sa.Uuid(), nullable=True),
    sa.Column('language', sa.Enum('en', 'ar', name='language', native_enum=False, length=40), nullable=False),
    sa.Column('template', sa.String(length=60), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_email_outbox_to_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_outbox'))
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('account_locked', 'contractor_cr_expiry', 'contractor_submitted', 'contractor_status_changed', 'engagement_parent_blacklisted', 'settings_changed', 'audit_chain_break', 'last_hse_manager_risk', 'role_assignment_ending', 'invite_expired', 'inactive_account', name='notificationkind', native_enum=False, length=40), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_ar', sa.String(length=200), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=True),
    sa.Column('body_ar', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.Enum('project', 'site', 'zone', 'contractor', 'project_engagement', 'user', 'role_assignment', 'project_settings', 'audit_log', name='entitytype', native_enum=False, length=40), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('project_settings',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('ltifr_base_hours', sa.Integer(), nullable=False),
    sa.Column('rate_base_hours', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('show_hijri', sa.Boolean(), nullable=False),
    sa.Column('hijri_calendar', sa.Enum('umm_al_qura', name='hijricalendar', native_enum=False, length=40), nullable=False),
    sa.Column('default_language', sa.Enum('en', 'ar', name='language', native_enum=False, length=40), nullable=False),
    sa.Column('week_start', sa.Enum('sunday', 'monday', name='weekstart', native_enum=False, length=40), nullable=False),
    sa.Column('digits', sa.Enum('western', 'arabic_indic', name='digitstyle', native_enum=False, length=40), nullable=False),
    sa.Column('date_format_en', sa.Enum('DD MMM YYYY', 'DD/MM/YYYY', name='dateformaten', native_enum=False, length=40), nullable=False),
    sa.Column('audit_retention_years', sa.Integer(), nullable=False),
    sa.Column('inactive_account_days', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_settings_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_project_settings_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_settings'))
    )
    op.create_table('role_assignments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('hse_manager', 'hse_officer', 'site_engineer', 'permit_issuer', 'permit_receiver', 'contractor_hse_rep', 'viewer_client', name='role', native_enum=False, length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('site_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('contractor_engagement_id', sa.Uuid(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('ending_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_engagement_id'], ['project_engagements.id'], name=op.f('fk_role_assignments_contractor_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_role_assignments_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_role_assignments_project_id_projects')),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], name=op.f('fk_role_assignments_revoked_by_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_role_assignments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_assignments'))
    )
    op.create_index(op.f('ix_role_assignments_project_id'), 'role_assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_user_id'), 'role_assignments', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=40), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('invite', 'password_reset', name='tokenkind', native_enum=False, length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_user_tokens_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_tokens_token_hash'))
    )
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    op.create_table('zones',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('zone_type', sa.Enum('airside', 'landside', 'other', name='zonetype', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('active', 'temporarily_closed', 'archived', name='zonestatus', native_enum=False, length=40), nullable=False),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('airside_area', sa.Enum('runway', 'runway_strip', 'resa', 'taxiway', 'taxiway_strip', 'apron', 'ils_critical', 'ils_sensitive', 'airside_road', 'other_airside', name='airsidearea', native_enum=False, length=40), nullable=True),
    sa.Column('in_movement_area', sa.Boolean(), nullable=True),
    sa.Column('runway_ref', sa.String(length=10), nullable=True),
    sa.Column('security_restricted_area', sa.Boolean(), nullable=True),
    sa.Column('notam_required_for_works', sa.Boolean(), nullable=True),
    sa.Column('ols_height_limit_m_amsl', sa.Numeric(precision=7, scale=2, asdecimal=False), nullable=True),
    sa.Column('max_equipment_height_m_agl', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=True),
    sa.Column('escort_required', sa.Boolean(), nullable=True),
    sa.Column('adp_required', sa.Boolean(), nullable=True),
    sa.Column('fod_control_required', sa.Boolean(), nullable=True),
    sa.Column('works_safety_plan_ref', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_zones_project_id_projects')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_zones_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones')),
    sa.UniqueConstraint('site_id', 'code', name='uq_zones_site_code')
    )
    op.create_index(op.f('ix_zones_project_id'), 'zones', ['project_id'], unique=False)
    op.create_index(op.f('ix_zones_site_id'), 'zones', ['site_id'], unique=False)
    # ### end Alembic commands ###
    op.create_foreign_key(
        op.f('fk_contractors_created_by_user_id_users'), 'contractors', 'users',
        ['created_by_user_id'], ['id'],
    )
    _audit_protection_up()


AUDIT_PROTECTION_SQL = """
-- Spec 0-foundation §5.6 rule 36: the audit log is append-only.
CREATE OR REPLACE FUNCTION hse_audit_log_guard() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' AND current_setting('hse.audit_purge', true) = 'on' THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'audit_log is append-only (% blocked)', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_log_append_only
    BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION hse_audit_log_guard();

-- Retention purge (rule 40) is the only deletion path. SECURITY DEFINER so a restricted
-- application role needs only EXECUTE on this function.
CREATE OR REPLACE FUNCTION hse_audit_purge(p_project_id uuid, p_cutoff timestamptz)
RETURNS TABLE(purged bigint, min_occurred timestamptz, max_occurred timestamptz)
LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    PERFORM set_config('hse.audit_purge', 'on', true);
    RETURN QUERY
    WITH d AS (
        DELETE FROM audit_log
        WHERE occurred_at < p_cutoff
          AND project_id IS NOT DISTINCT FROM p_project_id
          AND action <> 'retention_purge'
        RETURNING occurred_at
    )
    SELECT count(*)::bigint, min(d.occurred_at), max(d.occurred_at) FROM d;
    PERFORM set_config('hse.audit_purge', 'off', true);
END;
$$;

-- If a dedicated application role exists, it gets INSERT/SELECT only on the audit log.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'hse_app') THEN
        REVOKE ALL ON audit_log FROM hse_app;
        GRANT SELECT, INSERT ON audit_log TO hse_app;
        GRANT EXECUTE ON FUNCTION hse_audit_purge(uuid, timestamptz) TO hse_app;
    END IF;
END $$;
"""


def _audit_protection_up() -> None:
    op.execute(AUDIT_PROTECTION_SQL)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("fk_contractors_created_by_user_id_users"), "contractors")
    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS hse_audit_purge(uuid, timestamptz)")
    op.execute("DROP FUNCTION IF EXISTS hse_audit_log_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zones_site_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_project_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.drop_table('user_tokens')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_role_assignments_user_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_project_id'), table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_table('project_settings')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('email_outbox')
    op.drop_index(op.f('ix_users_employer_contractor_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sites_project_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_project_engagements_project_id'), table_name='project_engagements')
    op.drop_index(op.f('ix_project_engagements_parent_engagement_id'), table_name='project_engagements')
    op.drop_index(op.f('ix_project_engagements_contractor_id'), table_name='project_engagements')
    op.drop_table('project_engagements')
    op.drop_table('projects')
    op.drop_table('contractors')
    op.drop_index('ix_audit_log_project_occurred', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
