"""phase6g scorecard reports

Revision ID: 0015
Revises: 0014
Create Date: 2026-10-10 01:42:27.950671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0015'
down_revision: Union[str, Sequence[str], None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_scorecard_settings',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('scorecard_from_month', sa.Date(), nullable=True),
    sa.Column('source_live_from', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sources_confirmed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_scorecard_settings_project_id_projects')),
    sa.ForeignKeyConstraint(['sources_confirmed_by_user_id'], ['users.id'], name=op.f('fk_project_scorecard_settings_sources_confirmed_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_project_scorecard_settings_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_scorecard_settings'))
    )
    op.create_table('rp_packs',
    sa.Column('report_type', sa.Enum('MCR', 'SCP', 'CPS', 'OSHA300', 'HEAT', name='rptype', native_enum=False, length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('contractor_id', sa.Uuid(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('doc_no', sa.String(length=80), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('with_names', sa.Boolean(), nullable=False),
    sa.Column('scorecards_provisional', sa.Boolean(), nullable=False),
    sa.Column('provisional_reason', sa.String(length=500), nullable=True),
    sa.Column('prepared_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.String(length=500), nullable=True),
    sa.Column('reissue_reason', sa.String(length=500), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('revised_since_issue', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_revision', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_review', 'issued', 'superseded', name='rpstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_rp_packs_contractor_id_contractors')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_rp_packs_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_rp_packs_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], name=op.f('fk_rp_packs_issued_by_user_id_users')),
    sa.ForeignKeyConstraint(['prepared_by_user_id'], ['users.id'], name=op.f('fk_rp_packs_prepared_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_rp_packs_project_id_projects')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_rp_packs_reviewed_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_rp_packs_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rp_packs')),
    sa.UniqueConstraint('doc_no', 'revision', name=op.f('uq_rp_packs_doc_no'))
    )
    op.create_index('ix_rp_pack_project_type', 'rp_packs', ['project_id', 'report_type'], unique=False)
    op.create_table('rp_recipients',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.Enum('MCR', 'SCP', 'CPS', 'OSHA300', 'HEAT', name='rptype', native_enum=False, length=40), nullable=False),
    sa.Column('kind', sa.Enum('user', 'external', name='rpmemberkind', native_enum=False, length=40), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('display_name_en', sa.String(length=120), nullable=True),
    sa.Column('display_name_ar', sa.String(length=120), nullable=True),
    sa.Column('organisation', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('language', sa.Enum('en', 'ar', 'both', name='rplanguage', native_enum=False, length=40), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], name=op.f('fk_rp_recipients_acknowledged_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_rp_recipients_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rp_recipients_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rp_recipients'))
    )
    op.create_index(op.f('ix_rp_recipients_project_id'), 'rp_recipients', ['project_id'], unique=False)
    op.create_table('sc_cards',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('own', 'tree', name='scscope', native_enum=False, length=40), nullable=False),
    sa.Column('scorecard_no', sa.String(length=80), nullable=False),
    sa.Column('profile_code', sa.String(length=16), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('month_man_hours', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('r12_man_hours', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('credibility_z', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('score', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('coverage_pct', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('band_grade', sa.Enum('A', 'B', 'C', 'D', name='scgrade', native_enum=False, length=40), nullable=True),
    sa.Column('grade', sa.Enum('A', 'B', 'C', 'D', name='scgrade', native_enum=False, length=40), nullable=True),
    sa.Column('caps_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pillars', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trend_delta', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('trend_label', sa.Enum('improving', 'stable', 'declining', name='sctrend', native_enum=False, length=40), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rank_of', sa.Integer(), nullable=True),
    sa.Column('rank_status', sa.Enum('ranked', 'low_exposure', 'low_coverage', name='scrankstatus', native_enum=False, length=40), nullable=True),
    sa.Column('commended', sa.Boolean(), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('comment_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('provisional', 'issued', 'final', 'superseded', name='sccardstatus', native_enum=False, length=40), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalised_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reissue_reason', sa.String(length=500), nullable=True),
    sa.Column('revised_since_final', sa.Boolean(), nullable=False),
    sa.Column('recomputed_score', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_sc_cards_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_sc_cards_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['finalised_by_user_id'], ['users.id'], name=op.f('fk_sc_cards_finalised_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sc_cards_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_sc_cards_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sc_cards')),
    sa.UniqueConstraint('engagement_id', 'month', 'scope', 'revision', name=op.f('uq_sc_cards_engagement_id'))
    )
    op.create_index('ix_sc_card_project_month', 'sc_cards', ['project_id', 'month'], unique=False)
    op.create_table('sc_profiles',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('profile_code', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from_month', sa.Date(), nullable=False),
    sa.Column('pillars', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('caps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bands', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'retired', name='scprofilestatus', native_enum=False, length=40), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_sc_profiles_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sc_profiles_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_sc_profiles_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sc_profiles')),
    sa.UniqueConstraint('profile_code', 'version', name=op.f('uq_sc_profiles_profile_code'))
    )
    op.create_index(op.f('ix_sc_profiles_project_id'), 'sc_profiles', ['project_id'], unique=False)
    op.create_table('xp_subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('dataset', sa.String(length=40), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('format', sa.Enum('csv', 'xlsx', 'pdf', name='xpformat', native_enum=False, length=40), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', 'monthly', name='xpfrequency', native_enum=False, length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_xp_subscriptions_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_xp_subscriptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_subscriptions'))
    )
    op.create_index(op.f('ix_xp_subscriptions_user_id'), 'xp_subscriptions', ['user_id'], unique=False)
    op.create_table('rp_deliveries',
    sa.Column('pack_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('channel', sa.Enum('in_app', 'email', name='rpchannel', native_enum=False, length=40), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'bounced', 'failed', name='rpdeliverystatus', native_enum=False, length=40), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['rp_packs.id'], name=op.f('fk_rp_deliveries_pack_id_rp_packs')),
    sa.ForeignKeyConstraint(['recipient_id'], ['rp_recipients.id'], name=op.f('fk_rp_deliveries_recipient_id_rp_recipients')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rp_deliveries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rp_deliveries'))
    )
    op.create_index(op.f('ix_rp_deliveries_pack_id'), 'rp_deliveries', ['pack_id'], unique=False)
    op.create_table('sc_lines',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('metric_code', sa.String(length=20), nullable=False),
    sa.Column('pillar_code', sa.String(length=8), nullable=False),
    sa.Column('kpi_ref', sa.String(length=12), nullable=False),
    sa.Column('window', sa.Enum('r12_rate', 'month', 'month_end', 'latest_3m', name='scwindow', native_enum=False, length=40), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('numerator', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('denominator', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('base', sa.Integer(), nullable=True),
    sa.Column('own_value', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('project_value', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('points', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('line_status', sa.Enum('scored', 'not_applicable', 'insufficient_volume', 'source_not_live', 'excluded_by_manager', name='sclinestatus', native_enum=False, length=40), nullable=False),
    sa.Column('original_weight', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('effective_weight', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('contribution', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['sc_cards.id'], name=op.f('fk_sc_lines_card_id_sc_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sc_lines')),
    sa.UniqueConstraint('card_id', 'metric_code', name=op.f('uq_sc_lines_card_id'))
    )
    op.create_table('sc_remarks',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('target_code', sa.String(length=20), nullable=True),
    sa.Column('kind', sa.Enum('comment', 'dispute', name='scremarkkind', native_enum=False, length=40), nullable=False),
    sa.Column('internal', sa.Boolean(), nullable=False),
    sa.Column('reason_code', sa.Enum('data_error', 'wrong_attribution', 'not_applicable', 'other', name='scdisputereason', native_enum=False, length=40), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('file_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('warnings', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('raised_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Enum('upheld_data_corrected', 'upheld_metric_excluded', 'rejected', name='scresolution', native_enum=False, length=40), nullable=True),
    sa.Column('resolution_text', sa.Text(), nullable=True),
    sa.Column('corrected_record_ref', sa.String(length=80), nullable=True),
    sa.Column('old_points', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('new_points', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('old_score', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('new_score', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('resolved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'withdrawn', name='scremarkstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['sc_cards.id'], name=op.f('fk_sc_remarks_card_id_sc_cards')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_sc_remarks_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_sc_remarks_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sc_remarks_project_id_projects')),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], name=op.f('fk_sc_remarks_raised_by_user_id_users')),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('fk_sc_remarks_resolved_by_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_sc_remarks_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sc_remarks'))
    )
    op.create_index(op.f('ix_sc_remarks_card_id'), 'sc_remarks', ['card_id'], unique=False)
    op.create_table('xp_jobs',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('export_no', sa.String(length=20), nullable=False),
    sa.Column('dataset', sa.String(length=40), nullable=False),
    sa.Column('format', sa.Enum('csv', 'xlsx', 'pdf', name='xpformat', native_enum=False, length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('purpose', sa.Enum('gosi', 'mhrsd', 'client_report', 'legal', 'insurance', 'audit', 'data_subject_request', 'internal_analysis', 'other', name='xppurpose', native_enum=False, length=40), nullable=True),
    sa.Column('purpose_text', sa.String(length=500), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('attachment_id', sa.Uuid(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('contains_personal', sa.Boolean(), nullable=False),
    sa.Column('contains_sensitive', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'ready', 'expired', 'failed', name='xpjobstatus', native_enum=False, length=40), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], name=op.f('fk_xp_jobs_attachment_id_attachments')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_xp_jobs_project_id_projects')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_xp_jobs_requested_by_user_id_users')),
    sa.ForeignKeyConstraint(['subscription_id'], ['xp_subscriptions.id'], name=op.f('fk_xp_jobs_subscription_id_xp_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_jobs')),
    sa.UniqueConstraint('year', 'seq', name=op.f('uq_xp_jobs_year'))
    )
    op.create_index(op.f('ix_xp_jobs_project_id'), 'xp_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_xp_jobs_requested_by_user_id'), 'xp_jobs', ['requested_by_user_id'], unique=False)
    op.create_table('sc_watch_entries',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('entry_no', sa.String(length=40), nullable=False),
    sa.Column('level', sa.Enum('watch', 'improvement_plan', 'suspension_review', name='scwatchlevel', native_enum=False, length=40), nullable=False),
    sa.Column('trigger_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('baseline_score', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('opened_month', sa.Date(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_reason', sa.String(length=500), nullable=True),
    sa.Column('proposal', sa.Enum('improvement_plan', 'suspension_review', 'close', name='scwatchproposal', native_enum=False, length=40), nullable=True),
    sa.Column('proposal_reason', sa.String(length=300), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_ca_id', sa.Uuid(), nullable=True),
    sa.Column('pip_ca_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('pip_due_on', sa.Date(), nullable=True),
    sa.Column('pip_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pip_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.Enum('suspend', 'continue_with_conditions', 'remove_from_project', name='scwatchdecision', native_enum=False, length=40), nullable=True),
    sa.Column('decision_text', sa.String(length=1000), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contractor_status_ref', sa.String(length=80), nullable=True),
    sa.Column('closed_reason', sa.String(length=500), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='scwatchstatus', native_enum=False, length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_sc_watch_entries_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_sc_watch_entries_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sc_watch_entries_project_id_projects')),
    sa.ForeignKeyConstraint(['review_ca_id'], ['corrective_actions.id'], name=op.f('fk_sc_watch_entries_review_ca_id_corrective_actions')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_sc_watch_entries_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sc_watch_entries')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name=op.f('uq_sc_watch_entries_project_id'))
    )
    op.create_index(op.f('ix_sc_watch_entries_project_id'), 'sc_watch_entries', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sc_watch_entries_project_id'), table_name='sc_watch_entries')
    op.drop_table('sc_watch_entries')
    op.drop_index(op.f('ix_xp_jobs_requested_by_user_id'), table_name='xp_jobs')
    op.drop_index(op.f('ix_xp_jobs_project_id'), table_name='xp_jobs')
    op.drop_table('xp_jobs')
    op.drop_index(op.f('ix_sc_remarks_card_id'), table_name='sc_remarks')
    op.drop_table('sc_remarks')
    op.drop_table('sc_lines')
    op.drop_index(op.f('ix_rp_deliveries_pack_id'), table_name='rp_deliveries')
    op.drop_table('rp_deliveries')
    op.drop_index(op.f('ix_xp_subscriptions_user_id'), table_name='xp_subscriptions')
    op.drop_table('xp_subscriptions')
    op.drop_index(op.f('ix_sc_profiles_project_id'), table_name='sc_profiles')
    op.drop_table('sc_profiles')
    op.drop_index('ix_sc_card_project_month', table_name='sc_cards')
    op.drop_table('sc_cards')
    op.drop_index(op.f('ix_rp_recipients_project_id'), table_name='rp_recipients')
    op.drop_table('rp_recipients')
    op.drop_index('ix_rp_pack_project_type', table_name='rp_packs')
    op.drop_table('rp_packs')
    op.drop_table('project_scorecard_settings')
    # ### end Alembic commands ###
