"""phase1 dashboard

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 00:20:54.949816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_marks',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_job_marks'))
    )
    op.create_table('reference_items',
    sa.Column('list_name', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label_en', sa.String(length=120), nullable=False),
    sa.Column('label_ar', sa.String(length=120), nullable=False),
    sa.Column('group', sa.String(length=40), nullable=True),
    sa.Column('description_en', sa.String(length=300), nullable=True),
    sa.Column('description_ar', sa.String(length=300), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('list_name', 'code', name=op.f('pk_reference_items'))
    )
    op.create_table('ai_insight_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ai_insight_cache_project_id_projects')),
    sa.PrimaryKeyConstraint('cache_key', name=op.f('pk_ai_insight_cache'))
    )
    op.create_index(op.f('ix_ai_insight_cache_project_id'), 'ai_insight_cache', ['project_id'], unique=False)
    op.create_table('ai_answers',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grounding', sa.Enum('passed', 'passed_after_retry', 'failed', 'not_applicable', name='groundingresult', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ai_answers_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_answers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_answers'))
    )
    op.create_index('ix_ai_answer_cache', 'ai_answers', ['cache_key'], unique=False)
    op.create_index(op.f('ix_ai_answers_conversation_id'), 'ai_answers', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_answers_user_id'), 'ai_answers', ['user_id'], unique=False)
    op.create_table('ai_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('question_masked', sa.Text(), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer_excerpt', sa.Text(), nullable=True),
    sa.Column('grounding', sa.Enum('passed', 'passed_after_retry', 'failed', 'not_applicable', name='groundingresult', native_enum=False, length=40), nullable=False),
    sa.Column('grounding_failures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ai_logs_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_logs'))
    )
    op.create_index('ix_ai_log_user_created', 'ai_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('attachments',
    sa.Column('owner_type', sa.Enum('incident', 'injury_case_medical', 'observation', 'corrective_action_evidence', 'hse_meeting_minutes', name='attachmentowner', native_enum=False, length=40), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_bucket', sa.String(length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('scan_status', sa.Enum('pending', 'clean', 'infected', 'skipped', name='scanstatus', native_enum=False, length=40), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_attachments_project_id_projects')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_attachments_uploaded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_index('ix_attachment_owner', 'attachments', ['owner_type', 'owner_id'], unique=False)
    op.create_table('dashboard_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dashboard_preferences_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_dashboard_preferences'))
    )
    op.create_table('hse_meetings',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('meeting_type', sa.Enum('hse_committee', 'contractor_hse', 'management_walk', 'other', name='meetingtype', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('held_date', sa.Date(), nullable=True),
    sa.Column('invited_count', sa.Integer(), nullable=False),
    sa.Column('attended_count', sa.Integer(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_hse_meetings_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_hse_meetings_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hse_meetings'))
    )
    op.create_index('ix_meeting_project_planned', 'hse_meetings', ['project_id', 'planned_date'], unique=False)
    op.create_table('monthly_reports',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('generating', 'draft', 'reviewed', 'published', 'failed', name='monthlyreportstatus', native_enum=False, length=40), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_monthly_reports_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_monthly_reports_project_id_projects')),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['users.id'], name=op.f('fk_monthly_reports_published_by_user_id_users')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_monthly_reports_reviewed_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_reports'))
    )
    op.create_index('ix_monthly_report_project_month', 'monthly_reports', ['project_id', 'month'], unique=False)
    op.create_table('period_locks',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('restated', sa.Boolean(), nullable=False),
    sa.Column('restated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unlock_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['users.id'], name=op.f('fk_period_locks_locked_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_period_locks_project_id_projects')),
    sa.PrimaryKeyConstraint('project_id', 'month', name=op.f('pk_period_locks'))
    )
    op.create_table('project_hse_settings',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('lost_days_cap', sa.Integer(), nullable=False),
    sa.Column('fatality_lost_days_charge', sa.Integer(), nullable=False),
    sa.Column('include_commuting_in_rates', sa.Boolean(), nullable=False),
    sa.Column('include_non_contractor_cases_in_rates', sa.Boolean(), nullable=False),
    sa.Column('max_hours_per_person_day', sa.Integer(), nullable=False),
    sa.Column('warn_hours_per_person_day', sa.Integer(), nullable=False),
    sa.Column('daily_return_deadline', sa.Time(), nullable=False),
    sa.Column('completeness_threshold_pct', sa.Integer(), nullable=False),
    sa.Column('inspection_grace_days', sa.Integer(), nullable=False),
    sa.Column('ca_due_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ca_max_extensions', sa.Integer(), nullable=False),
    sa.Column('new_starter_days', sa.Integer(), nullable=False),
    sa.Column('heat_season_start', sa.String(length=5), nullable=False),
    sa.Column('heat_season_end', sa.String(length=5), nullable=False),
    sa.Column('low_exposure_hours', sa.Integer(), nullable=False),
    sa.Column('leading_warning_drop_pct', sa.Integer(), nullable=False),
    sa.Column('leading_warning_rise_pct', sa.Integer(), nullable=False),
    sa.Column('kpi_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('month_lock_day', sa.Integer(), nullable=False),
    sa.Column('injury_identity_retention_years', sa.Integer(), nullable=False),
    sa.Column('ai_requested', sa.Boolean(), nullable=False),
    sa.Column('ai_approved_on', sa.Date(), nullable=True),
    sa.Column('ai_approver_name', sa.String(length=120), nullable=True),
    sa.Column('ai_approver_organisation', sa.String(length=150), nullable=True),
    sa.Column('ai_approval_reference', sa.String(length=80), nullable=True),
    sa.Column('ai_approval_notes', sa.String(length=500), nullable=True),
    sa.Column('ai_approval_recorded_by', sa.Uuid(), nullable=True),
    sa.Column('ai_approval_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['ai_approval_recorded_by'], ['users.id'], name=op.f('fk_project_hse_settings_ai_approval_recorded_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_hse_settings_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_project_hse_settings_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_hse_settings'))
    )
    op.create_table('workforce_import_batches',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('insert_only', 'upsert', name='importmode', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('validated', 'committed', 'discarded', 'expired', name='importstatus', native_enum=False, length=40), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_workforce_import_batches_project_id_projects')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_workforce_import_batches_uploaded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workforce_import_batches'))
    )
    op.create_index(op.f('ix_workforce_import_batches_file_sha256'), 'workforce_import_batches', ['file_sha256'], unique=False)
    op.create_index(op.f('ix_workforce_import_batches_project_id'), 'workforce_import_batches', ['project_id'], unique=False)
    op.create_table('corrective_actions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('incident', 'observation', 'inspection', 'ai_recommendation', 'other', name='casourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('ai_recommendation_id', sa.String(length=40), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('responsible_engagement_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('control_level', sa.Enum('elimination', 'substitution', 'engineering', 'administrative', 'ppe', name='controllevel', native_enum=False, length=40), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='capriority', native_enum=False, length=40), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('original_due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'pending_verification', 'closed', 'cancelled', name='castatus', native_enum=False, length=40), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.Column('verification_comment', sa.String(length=1000), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_date', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_corrective_actions_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_corrective_actions_owner_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_corrective_actions_project_id_projects')),
    sa.ForeignKeyConstraint(['responsible_engagement_id'], ['project_engagements.id'], name=op.f('fk_corrective_actions_responsible_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_corrective_actions_site_id_sites')),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('fk_corrective_actions_verifier_id_users')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_corrective_actions_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrective_actions')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name='uq_ca_seq'),
    sa.UniqueConstraint('ref', name=op.f('uq_corrective_actions_ref'))
    )
    op.create_index('ix_ca_project_due', 'corrective_actions', ['project_id', 'due_date'], unique=False)
    op.create_index('ix_ca_project_status', 'corrective_actions', ['project_id', 'status'], unique=False)
    op.create_index('ix_ca_source', 'corrective_actions', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_corrective_actions_owner_id'), 'corrective_actions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_corrective_actions_responsible_engagement_id'), 'corrective_actions', ['responsible_engagement_id'], unique=False)
    op.create_index(op.f('ix_corrective_actions_verifier_id'), 'corrective_actions', ['verifier_id'], unique=False)
    op.create_table('incidents',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('location_detail', sa.String(length=200), nullable=True),
    sa.Column('responsible_engagement_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurred_date', sa.Date(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('shift', sa.Enum('day', 'night', name='incidentshift', native_enum=False, length=40), nullable=True),
    sa.Column('incident_types', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('primary_type', sa.Enum('injury_illness', 'near_miss', 'property_damage', 'environmental', 'dangerous_occurrence', name='incidenttype', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('immediate_actions', sa.Text(), nullable=True),
    sa.Column('activity', sa.Enum('excavation', 'concrete', 'formwork', 'rebar', 'steel_erection', 'scaffolding', 'lifting', 'work_at_height', 'electrical', 'mep_installation', 'hot_work', 'paving_asphalt', 'airfield_lighting', 'road_works', 'demolition', 'driving_transport', 'material_handling', 'housekeeping', 'survey', 'testing_commissioning', 'maintenance', 'other', name='activity', native_enum=False, length=40), nullable=True),
    sa.Column('work_related', sa.Boolean(), nullable=False),
    sa.Column('not_work_related_reason', sa.Enum('off_duty_camp', 'personal_task', 'pre_existing_condition', 'commuting', 'voluntary_wellness', 'other', name='notworkrelatedreason', native_enum=False, length=40), nullable=True),
    sa.Column('work_related_rationale', sa.String(length=500), nullable=True),
    sa.Column('actual_severity', sa.Integer(), nullable=True),
    sa.Column('potential_severity', sa.Integer(), nullable=True),
    sa.Column('ambient_temp_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('airside_flags', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('pd_asset_type', sa.Enum('plant', 'vehicle', 'structure', 'utility', 'airport_asset', 'aircraft', 'other', name='assettype', native_enum=False, length=40), nullable=True),
    sa.Column('pd_estimated_cost_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('env_category', sa.Enum('spill', 'emission', 'dust', 'noise', 'waste', 'water', 'wildlife_habitat', name='envcategory', native_enum=False, length=40), nullable=True),
    sa.Column('env_substance', sa.String(length=100), nullable=True),
    sa.Column('env_quantity_l', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('env_contained', sa.Boolean(), nullable=True),
    sa.Column('env_reached', sa.Enum('none', 'soil', 'drain', 'water_body', name='envreached', native_enum=False, length=40), nullable=True),
    sa.Column('do_category', sa.Enum('crane_lifting_failure', 'scaffold_collapse', 'structural_collapse', 'excavation_collapse', 'electrical_short_fire', 'fire_explosion', 'gas_release', 'pressure_failure', 'vehicle_overturn', 'other', name='dangerousoccurrencecategory', native_enum=False, length=40), nullable=True),
    sa.Column('status', sa.Enum('draft', 'reported', 'under_investigation', 'pending_review', 'actions_pending', 'closed', 'voided', name='incidentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('void_reason', sa.String(length=1000), nullable=True),
    sa.Column('status_reason', sa.String(length=1000), nullable=True),
    sa.Column('higher_control_justification', sa.String(length=1000), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_incidents_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_incidents_project_id_projects')),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], name=op.f('fk_incidents_reported_by_user_id_users')),
    sa.ForeignKeyConstraint(['responsible_engagement_id'], ['project_engagements.id'], name=op.f('fk_incidents_responsible_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_incidents_site_id_sites')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_incidents_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name='uq_incident_seq'),
    sa.UniqueConstraint('ref', name=op.f('uq_incidents_ref'))
    )
    op.create_index('ix_incident_project_date', 'incidents', ['project_id', 'occurred_date'], unique=False)
    op.create_index('ix_incident_project_status', 'incidents', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_incidents_responsible_engagement_id'), 'incidents', ['responsible_engagement_id'], unique=False)
    op.create_table('inspection_plans',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('inspection_type', sa.Enum('general_site', 'scaffold', 'lifting_equipment', 'electrical', 'excavation', 'housekeeping', 'fire_safety', 'welfare', 'airside_fod_walk', 'plant_vehicle', 'environmental', 'ppe', 'leadership_walk', name='inspectiontype', native_enum=False, length=40), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'fortnightly', 'monthly', 'once', name='inspectionfrequency', native_enum=False, length=40), nullable=False),
    sa.Column('weekday', sa.Enum('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', name='weekday', native_enum=False, length=40), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('assignee_role', sa.Enum('hse_officer', 'site_engineer', 'contractor_hse_rep', name='inspectionassigneerole', native_enum=False, length=40), nullable=False),
    sa.Column('assignee_user_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('generated_until', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], name=op.f('fk_inspection_plans_assignee_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_inspection_plans_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_inspection_plans_project_id_projects')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_inspection_plans_site_id_sites')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_inspection_plans_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_plans'))
    )
    op.create_index(op.f('ix_inspection_plans_project_id'), 'inspection_plans', ['project_id'], unique=False)
    op.create_table('observations',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_date', sa.Date(), nullable=False),
    sa.Column('observer_id', sa.Uuid(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('observed_engagement_id', sa.Uuid(), nullable=False),
    sa.Column('obs_type', sa.Enum('safe_behaviour', 'safe_condition', 'unsafe_act', 'unsafe_condition', name='observationtype', native_enum=False, length=40), nullable=False),
    sa.Column('category', sa.Enum('work_at_height', 'lifting', 'excavation', 'scaffolding', 'electrical', 'hot_work', 'ppe', 'housekeeping', 'traffic_plant', 'airside_fod_control', 'airside_driving', 'heat_stress', 'confined_space', 'manual_handling', 'tools_equipment', 'environmental', 'fire_safety', 'welfare', 'permit_compliance', 'behaviour_other', name='observationcategory', native_enum=False, length=40), nullable=False),
    sa.Column('risk_rating', sa.Enum('low', 'medium', 'high', name='riskrating', native_enum=False, length=40), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('stop_work_applied', sa.Boolean(), nullable=False),
    sa.Column('immediate_action', sa.String(length=500), nullable=True),
    sa.Column('closed_on_spot', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('open', 'action_raised', 'closed', name='observationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('closure_comment', sa.String(length=500), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('closed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('no_ca_alert_sent', sa.Boolean(), nullable=False),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], name=op.f('fk_observations_closed_by_user_id_users')),
    sa.ForeignKeyConstraint(['observed_engagement_id'], ['project_engagements.id'], name=op.f('fk_observations_observed_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['observer_id'], ['users.id'], name=op.f('fk_observations_observer_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_observations_project_id_projects')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_observations_site_id_sites')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_observations_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations')),
    sa.UniqueConstraint('project_id', 'year', 'seq', name='uq_observation_seq'),
    sa.UniqueConstraint('ref', name=op.f('uq_observations_ref'))
    )
    op.create_index('ix_observation_project_date', 'observations', ['project_id', 'observed_date'], unique=False)
    op.create_index(op.f('ix_observations_observed_engagement_id'), 'observations', ['observed_engagement_id'], unique=False)
    op.create_table('workforce_returns',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Enum('day', 'night', 'all', name='shift', native_enum=False, length=40), nullable=False),
    sa.Column('no_work', sa.Boolean(), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('man_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('toolbox_talks', sa.Integer(), nullable=False),
    sa.Column('toolbox_attendees', sa.Integer(), nullable=False),
    sa.Column('inductions', sa.Integer(), nullable=False),
    sa.Column('training_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('manual', 'import', name='workforcesource', native_enum=False, length=40), nullable=False),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'verified', 'locked', name='workforcestatus', native_enum=False, length=40), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('verified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_workforce_returns_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_workforce_returns_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['import_batch_id'], ['workforce_import_batches.id'], name=op.f('fk_workforce_returns_import_batch_id_workforce_import_batches')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_workforce_returns_project_id_projects')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_workforce_returns_site_id_sites')),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_workforce_returns_verified_by_user_id_users')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_workforce_returns_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workforce_returns')),
    sa.UniqueConstraint('project_id', 'work_date', 'site_id', 'zone_id', 'engagement_id', 'shift', name='uq_workforce_return_key', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_workforce_engagement_date', 'workforce_returns', ['engagement_id', 'work_date'], unique=False)
    op.create_index('ix_workforce_project_date', 'workforce_returns', ['project_id', 'work_date'], unique=False)
    op.create_table('ca_extensions',
    sa.Column('ca_id', sa.Uuid(), nullable=False),
    sa.Column('new_due_date', sa.Date(), nullable=False),
    sa.Column('previous_due_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', name='extensionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ca_id'], ['corrective_actions.id'], name=op.f('fk_ca_extensions_ca_id_corrective_actions')),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_ca_extensions_decided_by_user_id_users')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_ca_extensions_requested_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ca_extensions'))
    )
    op.create_index(op.f('ix_ca_extensions_ca_id'), 'ca_extensions', ['ca_id'], unique=False)
    op.create_table('incident_external_notifications',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Enum('gosi', 'mhrsd', 'civil_defense', 'gaca', 'airport_operator', 'client', 'police', name='externalbody', native_enum=False, length=40), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference_no', sa.String(length=60), nullable=True),
    sa.Column('notified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_external_notifications_incident_id_incidents')),
    sa.ForeignKeyConstraint(['notified_by_user_id'], ['users.id'], name=op.f('fk_incident_external_notifications_notified_by_user_id_users')),
    sa.PrimaryKeyConstraint('incident_id', 'body', name=op.f('pk_incident_external_notifications'))
    )
    op.create_table('injury_cases',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('person_no', sa.Integer(), nullable=False),
    sa.Column('person_type', sa.Enum('contractor_worker', 'client_pmc_staff', 'visitor', 'third_party_public', name='persontype', native_enum=False, length=40), nullable=False),
    sa.Column('employer_engagement_id', sa.Uuid(), nullable=True),
    sa.Column('person_name', sa.String(length=120), nullable=False),
    sa.Column('id_type', sa.Enum('iqama', 'national_id', 'passport', name='idtype', native_enum=False, length=40), nullable=True),
    sa.Column('id_number_enc', sa.LargeBinary(), nullable=True),
    sa.Column('id_number_masked', sa.String(length=12), nullable=True),
    sa.Column('employee_no', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=2), nullable=True),
    sa.Column('trade', sa.Enum('labourer', 'carpenter', 'steel_fixer', 'steel_erector', 'scaffolder', 'rigger', 'crane_operator', 'plant_operator', 'driver', 'electrician', 'plumber', 'welder', 'mason', 'painter', 'surveyor', 'supervisor', 'engineer', 'hse_staff', 'flagman', 'other', name='trade', native_enum=False, length=40), nullable=False),
    sa.Column('age_band', sa.Enum('<20', '20-29', '30-39', '40-49', '50-59', '60+', name='ageband', native_enum=False, length=40), nullable=True),
    sa.Column('site_start_date', sa.Date(), nullable=True),
    sa.Column('hours_into_shift', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('illness', sa.Boolean(), nullable=False),
    sa.Column('body_part', sa.Enum('head', 'eye', 'face', 'neck', 'shoulder', 'upper_arm', 'elbow', 'forearm', 'wrist', 'hand', 'finger', 'chest', 'upper_back', 'lower_back', 'abdomen', 'hip_pelvis', 'thigh', 'knee', 'lower_leg', 'ankle', 'foot', 'toe', 'multiple', 'internal_systemic', name='bodypart', native_enum=False, length=40), nullable=False),
    sa.Column('body_side', sa.Enum('left', 'right', 'both', 'n/a', name='bodyside', native_enum=False, length=40), nullable=True),
    sa.Column('nature', sa.Enum('fracture', 'laceration', 'abrasion', 'contusion', 'sprain_strain', 'puncture', 'burn_thermal', 'burn_chemical', 'electric_shock', 'amputation', 'crush', 'dislocation', 'foreign_body_eye', 'concussion', 'heat_exhaustion', 'heat_stroke', 'inhalation_poisoning', 'noise_hearing', 'dermatitis', 'multiple', 'other', name='injurynature', native_enum=False, length=40), nullable=False),
    sa.Column('mechanism', sa.Enum('fall_from_height', 'slip_trip_same_level', 'struck_by_falling_object', 'struck_by_moving_object', 'struck_against', 'caught_in_between', 'contact_electricity', 'contact_hot_fire', 'contact_chemical', 'overexertion_manual_handling', 'repetitive_motion', 'vehicle_plant_collision', 'vehicle_overturn', 'exposure_heat', 'exposure_noise', 'bite_sting', 'assault', 'other', name='mechanism', native_enum=False, length=40), nullable=False),
    sa.Column('agency', sa.Enum('scaffold', 'ladder', 'mewp', 'crane_lifting_gear', 'earthmoving', 'light_vehicle', 'heavy_vehicle', 'airside_gse', 'aircraft', 'hand_tool', 'power_tool', 'formwork', 'rebar_steel', 'materials', 'electrical_installation', 'chemical', 'hot_work_equipment', 'ground_surface', 'stairs_openings', 'excavation_trench', 'weather_sun', 'other', name='agency', native_enum=False, length=40), nullable=False),
    sa.Column('treatments', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('loss_of_consciousness', sa.Boolean(), nullable=False),
    sa.Column('treated_at', sa.Enum('site_clinic', 'hospital_outpatient', 'hospital_admitted', 'none', name='treatedat', native_enum=False, length=40), nullable=False),
    sa.Column('fatal', sa.Boolean(), nullable=False),
    sa.Column('date_of_death', sa.Date(), nullable=True),
    sa.Column('away_start_date', sa.Date(), nullable=True),
    sa.Column('rtw_date', sa.Date(), nullable=True),
    sa.Column('restricted_start', sa.Date(), nullable=True),
    sa.Column('restricted_end', sa.Date(), nullable=True),
    sa.Column('transfer_start', sa.Date(), nullable=True),
    sa.Column('transfer_end', sa.Date(), nullable=True),
    sa.Column('permanent_disability', sa.Enum('none', 'partial', 'total', name='permanentdisability', native_enum=False, length=40), nullable=False),
    sa.Column('commuting', sa.Boolean(), nullable=False),
    sa.Column('privacy_case', sa.Boolean(), nullable=False),
    sa.Column('privacy_reason', sa.Enum('sexual_assault', 'mental_illness', 'infectious_disease', 'needlestick_contaminated', 'reproductive_organs', 'employee_request', name='privacycasereason', native_enum=False, length=40), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('gosi_case_ref', sa.String(length=30), nullable=True),
    sa.Column('derived_category', sa.Enum('FAT', 'LTI', 'RWC', 'JTC', 'MTC', 'FAC', name='casecategory', native_enum=False, length=40), nullable=False),
    sa.Column('confirmed_category', sa.Enum('FAT', 'LTI', 'RWC', 'JTC', 'MTC', 'FAC', name='casecategory', native_enum=False, length=40), nullable=True),
    sa.Column('classification_status', sa.Enum('provisional', 'confirmed', name='classificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('override_justification', sa.String(length=1000), nullable=True),
    sa.Column('anonymised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_open_alert_on', sa.Date(), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employer_engagement_id'], ['project_engagements.id'], name=op.f('fk_injury_cases_employer_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_injury_cases_incident_id_incidents')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_injury_cases_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_injury_cases')),
    sa.UniqueConstraint('incident_id', 'person_no', name='uq_case_person_no')
    )
    op.create_index(op.f('ix_injury_cases_employer_engagement_id'), 'injury_cases', ['employer_engagement_id'], unique=False)
    op.create_index(op.f('ix_injury_cases_incident_id'), 'injury_cases', ['incident_id'], unique=False)
    op.create_index(op.f('ix_injury_cases_project_id'), 'injury_cases', ['project_id'], unique=False)
    op.create_table('inspections',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('inspection_type', sa.Enum('general_site', 'scaffold', 'lifting_equipment', 'electrical', 'excavation', 'housekeeping', 'fire_safety', 'welfare', 'airside_fod_walk', 'plant_vehicle', 'environmental', 'ppe', 'leadership_walk', name='inspectiontype', native_enum=False, length=40), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('assignee_role', sa.Enum('hse_officer', 'site_engineer', 'contractor_hse_rep', name='inspectionassigneerole', native_enum=False, length=40), nullable=True),
    sa.Column('assignee_user_id', sa.Uuid(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('inspector_id', sa.Uuid(), nullable=True),
    sa.Column('items_checked', sa.Integer(), nullable=True),
    sa.Column('items_compliant', sa.Integer(), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('planned', 'completed', 'missed', 'cancelled', name='inspectionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('missed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seed_fake', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], name=op.f('fk_inspections_assignee_user_id_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_engagements.id'], name=op.f('fk_inspections_engagement_id_project_engagements')),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], name=op.f('fk_inspections_inspector_id_users')),
    sa.ForeignKeyConstraint(['plan_id'], ['inspection_plans.id'], name=op.f('fk_inspections_plan_id_inspection_plans')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_inspections_project_id_projects')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_inspections_site_id_sites')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_inspections_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections')),
    sa.UniqueConstraint('plan_id', 'planned_date', name='uq_inspection_plan_date'),
    sa.UniqueConstraint('project_id', 'year', 'seq', name='uq_inspection_seq'),
    sa.UniqueConstraint('ref', name=op.f('uq_inspections_ref'))
    )
    op.create_index('ix_inspection_project_completed', 'inspections', ['project_id', 'completed_date'], unique=False)
    op.create_index('ix_inspection_project_planned', 'inspections', ['project_id', 'planned_date'], unique=False)
    op.create_table('investigations',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Enum('L1', 'L2', 'L3', name='investigationlevel', native_enum=False, length=40), nullable=False),
    sa.Column('lead_investigator_id', sa.Uuid(), nullable=True),
    sa.Column('team_member_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('method', sa.Enum('simple', 'five_why', 'icam', 'taproot', name='investigationmethod', native_enum=False, length=40), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('extensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preliminary_report', sa.Text(), nullable=True),
    sa.Column('preliminary_report_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sequence_of_events', sa.Text(), nullable=True),
    sa.Column('immediate_causes', sa.Text(), nullable=True),
    sa.Column('root_causes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('ptw_involved', sa.Boolean(), nullable=True),
    sa.Column('ptw_ref', sa.String(length=40), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_comment', sa.String(length=1000), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alerts_sent', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_investigations_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_investigations_incident_id_incidents')),
    sa.ForeignKeyConstraint(['lead_investigator_id'], ['users.id'], name=op.f('fk_investigations_lead_investigator_id_users')),
    sa.PrimaryKeyConstraint('incident_id', name=op.f('pk_investigations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investigations')
    op.drop_index('ix_inspection_project_planned', table_name='inspections')
    op.drop_index('ix_inspection_project_completed', table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_injury_cases_project_id'), table_name='injury_cases')
    op.drop_index(op.f('ix_injury_cases_incident_id'), table_name='injury_cases')
    op.drop_index(op.f('ix_injury_cases_employer_engagement_id'), table_name='injury_cases')
    op.drop_table('injury_cases')
    op.drop_table('incident_external_notifications')
    op.drop_index(op.f('ix_ca_extensions_ca_id'), table_name='ca_extensions')
    op.drop_table('ca_extensions')
    op.drop_index('ix_workforce_project_date', table_name='workforce_returns')
    op.drop_index('ix_workforce_engagement_date', table_name='workforce_returns')
    op.drop_table('workforce_returns')
    op.drop_index(op.f('ix_observations_observed_engagement_id'), table_name='observations')
    op.drop_index('ix_observation_project_date', table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_inspection_plans_project_id'), table_name='inspection_plans')
    op.drop_table('inspection_plans')
    op.drop_index(op.f('ix_incidents_responsible_engagement_id'), table_name='incidents')
    op.drop_index('ix_incident_project_status', table_name='incidents')
    op.drop_index('ix_incident_project_date', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_corrective_actions_verifier_id'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_responsible_engagement_id'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_owner_id'), table_name='corrective_actions')
    op.drop_index('ix_ca_source', table_name='corrective_actions')
    op.drop_index('ix_ca_project_status', table_name='corrective_actions')
    op.drop_index('ix_ca_project_due', table_name='corrective_actions')
    op.drop_table('corrective_actions')
    op.drop_index(op.f('ix_workforce_import_batches_project_id'), table_name='workforce_import_batches')
    op.drop_index(op.f('ix_workforce_import_batches_file_sha256'), table_name='workforce_import_batches')
    op.drop_table('workforce_import_batches')
    op.drop_table('project_hse_settings')
    op.drop_table('period_locks')
    op.drop_index('ix_monthly_report_project_month', table_name='monthly_reports')
    op.drop_table('monthly_reports')
    op.drop_index('ix_meeting_project_planned', table_name='hse_meetings')
    op.drop_table('hse_meetings')
    op.drop_table('dashboard_preferences')
    op.drop_index('ix_attachment_owner', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('ix_ai_log_user_created', table_name='ai_logs')
    op.drop_table('ai_logs')
    op.drop_index(op.f('ix_ai_answers_user_id'), table_name='ai_answers')
    op.drop_index(op.f('ix_ai_answers_conversation_id'), table_name='ai_answers')
    op.drop_index('ix_ai_answer_cache', table_name='ai_answers')
    op.drop_table('ai_answers')
    op.drop_index(op.f('ix_ai_insight_cache_project_id'), table_name='ai_insight_cache')
    op.drop_table('ai_insight_cache')
    op.drop_table('reference_items')
    op.drop_table('job_marks')
    # ### end Alembic commands ###
