"""Stable error codes and the API error envelope.

Every error response body is ``{"detail": {"code": ..., "message": ..., "message_ar": ...}}``
(see docs/CONVENTIONS.md). The frontend maps ``code`` to EN/AR text (spec §5.7 rule 48).
"""

from enum import StrEnum
from typing import Any

from fastapi import Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from starlette.exceptions import HTTPException as StarletteHTTPException


class ErrorCode(StrEnum):
    """Machine-readable error codes. Stable: the frontend translates these."""

    UNAUTHENTICATED = "UNAUTHENTICATED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    PRIVACY_ACK_REQUIRED = "PRIVACY_ACK_REQUIRED"
    PRIVACY_NOTICE_VERSION_MISMATCH = "PRIVACY_NOTICE_VERSION_MISMATCH"
    INVITE_INVALID = "INVITE_INVALID"
    INVITE_EXPIRED = "INVITE_EXPIRED"
    RESET_TOKEN_INVALID = "RESET_TOKEN_INVALID"
    WEAK_PASSWORD = "WEAK_PASSWORD"
    CURRENT_PASSWORD_INCORRECT = "CURRENT_PASSWORD_INCORRECT"
    FORBIDDEN = "FORBIDDEN"
    READ_ONLY_ROLE = "READ_ONLY_ROLE"
    CONTRACTOR_SUSPENDED = "CONTRACTOR_SUSPENDED"
    SELF_MODIFICATION_FORBIDDEN = "SELF_MODIFICATION_FORBIDDEN"
    ROLE_NOT_ASSIGNABLE = "ROLE_NOT_ASSIGNABLE"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DUPLICATE_VALUE = "DUPLICATE_VALUE"
    INVALID_TRANSITION = "INVALID_TRANSITION"
    TRANSITION_CONDITION_NOT_MET = "TRANSITION_CONDITION_NOT_MET"
    PROJECT_CLOSED = "PROJECT_CLOSED"
    SITE_INACTIVE = "SITE_INACTIVE"
    ZONE_ARCHIVED = "ZONE_ARCHIVED"
    CONTRACTOR_NOT_APPROVED = "CONTRACTOR_NOT_APPROVED"
    LAST_HSE_MANAGER = "LAST_HSE_MANAGER"
    SOD_CONFLICT = "SOD_CONFLICT"
    # ---- Phase 1 (1-dashboard) ----
    DUPLICATE_RETURN = "DUPLICATE_RETURN"  # W-1 / AC2
    PERIOD_LOCKED = "PERIOD_LOCKED"  # W-10: row/case in a Locked month
    VERIFIER_IS_CREATOR = "VERIFIER_IS_CREATOR"  # §4.1 verifier ≠ creator
    OUTSIDE_MOBILISATION = "OUTSIDE_MOBILISATION"  # E05 for manual entry
    IMPORT_FILE_INVALID = "IMPORT_FILE_INVALID"  # E14 whole file, size/row limits, type
    IMPORT_HAS_ERRORS = "IMPORT_HAS_ERRORS"  # W-5 commit with rows_error > 0
    IMPORT_EXPIRED = "IMPORT_EXPIRED"  # W-5 / AC5 dry-run older than 60 min
    IMPORT_NOT_VALIDATED = "IMPORT_NOT_VALIDATED"  # batch already committed/discarded
    NEAR_MISS_EXCLUSIVE = "NEAR_MISS_EXCLUSIVE"  # I-3 / AC19
    INJURY_CASE_REQUIRED = "INJURY_CASE_REQUIRED"  # I-2 / AC20
    INVESTIGATION_LEVEL_TOO_LOW = "INVESTIGATION_LEVEL_TOO_LOW"  # I-14 / AC23
    INVESTIGATION_INCOMPLETE = "INVESTIGATION_INCOMPLETE"  # §3.5 / I-16 at submit
    INVESTIGATION_LEAD_NOT_ALLOWED = "INVESTIGATION_LEAD_NOT_ALLOWED"  # §3.5 / I-15
    INVESTIGATION_TEAM_INCOMPLETE = "INVESTIGATION_TEAM_INCOMPLETE"  # I-15 L3 team
    APPROVER_IS_LEAD = "APPROVER_IS_LEAD"  # §3.5 approver ≠ lead investigator
    CASES_NOT_CONFIRMED = "CASES_NOT_CONFIRMED"  # §4.2 Pending Review → Actions Pending
    HIGHER_CONTROL_REQUIRED = "HIGHER_CONTROL_REQUIRED"  # I-17 / AC24
    JUSTIFICATION_REQUIRED = "JUSTIFICATION_REQUIRED"  # I-6 category override
    POSSIBLE_ID_NUMBER = "POSSIBLE_ID_NUMBER"  # P1-8 warning code (never an error status)
    SAFE_OBSERVATION_IMMUTABLE = "SAFE_OBSERVATION_IMMUTABLE"  # O-3
    FINDING_CA_REQUIRED = "FINDING_CA_REQUIRED"  # N-4
    VERIFIER_IS_OWNER = "VERIFIER_IS_OWNER"  # CA-5 / AC40
    VERIFIER_ROLE_NOT_ALLOWED = "VERIFIER_ROLE_NOT_ALLOWED"  # CA-5 role per priority
    EVIDENCE_REQUIRED = "EVIDENCE_REQUIRED"  # CA-4 / AC42
    EXTENSION_LIMIT_REACHED = "EXTENSION_LIMIT_REACHED"  # CA-3 / AC41
    DUE_DATE_TOO_LATE = "DUE_DATE_TOO_LATE"  # CA-2
    RESTRICTED_DIMENSION = "RESTRICTED_DIMENSION"  # D-7 / AI-6 nationality, age band
    MIXED_PROJECT_SCOPE = "MIXED_PROJECT_SCOPE"  # all-projects requested by non-manager
    EXPORT_PURPOSE_REQUIRED = "EXPORT_PURPOSE_REQUIRED"  # P1-6
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    SIGNED_URL_INVALID = "SIGNED_URL_INVALID"  # P1-3 expired or tampered link
    AI_DISABLED = "AI_DISABLED"  # AI-14 / AC73 (ai_enabled false or no transfer approval)
    AI_TRANSFER_APPROVAL_REQUIRED = "AI_TRANSFER_APPROVAL_REQUIRED"  # AI-14 enabling AI
    AI_UNAVAILABLE = "AI_UNAVAILABLE"  # AI-18: no API key / provider down / timeout
    AI_RATE_LIMITED = "AI_RATE_LIMITED"  # AI-17 per-user / per-project limits
    # ---- Phase 2 (2-access-permits) ----
    GATE_DEVICE_FORBIDDEN = "GATE_DEVICE_FORBIDDEN"  # GC-1 device session outside gate checks
    GATE_DEVICE_REVOKED = "GATE_DEVICE_REVOKED"  # GC-1 revoked / unknown device token
    GATE_RATE_LIMITED = "GATE_RATE_LIMITED"  # GC-3 120 checks/min per device or user
    PAIRING_NOT_FOUND = "PAIRING_NOT_FOUND"  # GC-8 pairing id unknown / other device
    WORKER_EXISTS = "WORKER_EXISTS"  # WK-2 (meta.worker_no, meta.worker_id)
    WORKER_EXISTS_OUT_OF_SCOPE = "WORKER_EXISTS_OUT_OF_SCOPE"  # WK-2 (no identifying data)
    ADULT_ATTESTATION_REQUIRED = "ADULT_ATTESTATION_REQUIRED"  # WK-6
    DEPLOYMENT_EXISTS = "DEPLOYMENT_EXISTS"  # WK-10
    WORKER_BANNED = "WORKER_BANNED"  # WK-12
    PHOTO_REQUIRED = "PHOTO_REQUIRED"  # §3.1 photo for airside/pass, AP-5
    DELIVERER_NOT_ALLOWED = "DELIVERER_NOT_ALLOWED"  # IN-3 / IN-12 / AC13
    INDUCTION_PREREQUISITE = "INDUCTION_PREREQUISITE"  # IN-4
    INDUCTION_ATTEMPTS_EXCEEDED = "INDUCTION_ATTEMPTS_EXCEEDED"  # IN-5
    INDUCTION_TOO_SHORT = "INDUCTION_TOO_SHORT"  # IN-7
    INDUCTION_EDIT_LOCKED = "INDUCTION_EDIT_LOCKED"  # IN-11 edits after 24 h
    PROFILE_LOOSENING = "PROFILE_LOOSENING"  # ZP-2
    HOOK_PROVIDER_MISSING = "HOOK_PROVIDER_MISSING"  # HK-4
    NOT_AIRPORT_PROJECT = "NOT_AIRPORT_PROJECT"  # AP-2
    APPLICATION_OPEN = "APPLICATION_OPEN"  # AP-3
    ID_EXPIRES_SOON = "ID_EXPIRES_SOON"  # AP-5
    ID_EXPIRED = "ID_EXPIRED"  # WK-7 on writes that need a valid ID
    VALIDITY_EXCEEDS_LIMIT = "VALIDITY_EXCEEDS_LIMIT"  # AP-6 (meta.limiting_factor, meta.max)
    BACKGROUND_NOT_CLEARED = "BACKGROUND_NOT_CLEARED"  # AP-4
    ENDORSER_NOT_ALLOWED = "ENDORSER_NOT_ALLOWED"  # AP-8
    PREREQUISITES_NOT_MET = "PREREQUISITES_NOT_MET"  # AP-7 endorse (meta.requirements)
    AREA_NOT_REQUESTED = "AREA_NOT_REQUESTED"  # AP-9 issued areas ⊆ requested
    ADP_PASS_REQUIRED = "ADP_PASS_REQUIRED"  # DP-3
    ADP_EXISTS = "ADP_EXISTS"  # DP-2
    LICENCE_NOT_VALID = "LICENCE_NOT_VALID"  # DP-4
    RTF_REQUIRED = "RTF_REQUIRED"  # DP-5
    TESTS_NOT_VALID = "TESTS_NOT_VALID"  # DP-6
    SUSPENSION_PERIOD_RUNNING = "SUSPENSION_PERIOD_RUNNING"  # DP-8
    AVP_PRECONDITION = "AVP_PRECONDITION"  # VP-3 / VP-4
    AVP_EXISTS = "AVP_EXISTS"  # VP-2
    LATE_JUSTIFICATION_REQUIRED = "LATE_JUSTIFICATION_REQUIRED"  # NT-2 / OB-5 short lead
    OB_CONDITIONS_REQUIRED = "OB_CONDITIONS_REQUIRED"  # OB-4
    CLEARANCE_NOT_LINKABLE = "CLEARANCE_NOT_LINKABLE"  # OB-8 rejected clearance on a WAP
    WAP_DURATION_EXCEEDED = "WAP_DURATION_EXCEEDED"  # WA-5 wap_max_days
    WSP_REQUIRED = "WSP_REQUIRED"  # WA-6
    WAP_BLOCKED = "WAP_BLOCKED"  # WA-13 resume with blockers (meta.blockers)
    CREW_INVALID = "CREW_INVALID"  # WA-2 crew / supervisor composition
    FOD_HANDBACK_REQUIRED = "FOD_HANDBACK_REQUIRED"  # WA-17
    OPS_ZONES_LOCKED = "OPS_ZONES_LOCKED"  # WA-16 default zones cannot be removed
    SYSTEM_SUSPENSION = "SYSTEM_SUSPENSION"  # LC-6 dependency suspensions lift automatically
    CREDENTIAL_TERMINAL = "CREDENTIAL_TERMINAL"  # LC-5 revoked/expired/lost
    # ---- Phase 3 (3-ptw) ----
    REAUTH_REQUIRED = "REAUTH_REQUIRED"  # PT-15 (401): re-authenticate, then retry
    COSIGNER_INVALID = "COSIGNER_INVALID"  # co-signature password wrong / wrong person
    CONTRACTOR_BLACKLISTED = "CONTRACTOR_BLACKLISTED"  # PT-6
    MIXED_SIDE_ZONES = "MIXED_SIDE_ZONES"  # PT-4
    ZONES_NOT_SAME_SITE = "ZONES_NOT_SAME_SITE"  # PT-4
    RECEIVER_LIMIT = "RECEIVER_LIMIT"  # PT-5
    CREW_NOT_IN_TREE = "CREW_NOT_IN_TREE"  # PT-7
    DURATION_EXCEEDS_LIMIT = "DURATION_EXCEEDS_LIMIT"  # PT-11 (meta.limiting_type)
    BACKDATED_PERMIT = "BACKDATED_PERMIT"  # PT-10 valid_from_at < now − 15 min
    PERMIT_READ_ONLY = "PERMIT_READ_ONLY"  # CL-7 terminal permit
    KEY_ROLE_BUSY = "KEY_ROLE_BUSY"  # PR-10
    APPOINTMENT_INVALID = "APPOINTMENT_INVALID"  # PR-2 / PR-4 / GT-2 / IS
    ISSUER_APPOINTMENT_MANAGER_ONLY = "ISSUER_APPOINTMENT_MANAGER_ONLY"  # PR-2 (403)
    JSA_MISSING = "JSA_MISSING"  # JS-1
    JSA_NOT_APPROVED = "JSA_NOT_APPROVED"  # JS-6
    JSA_TYPE_MISMATCH = "JSA_TYPE_MISMATCH"  # JS-3
    JSA_MANDATORY_HAZARD_MISSING = "JSA_MANDATORY_HAZARD_MISSING"  # JS-4
    JSA_RESIDUAL_EXTREME = "JSA_RESIDUAL_EXTREME"  # JS-6
    JSA_FROZEN = "JSA_FROZEN"  # JS-10 approved instance: create a revision
    RESIDUAL_ACCEPTANCE_MISSING = "RESIDUAL_ACCEPTANCE_MISSING"  # JS-7
    RESIDUAL_ABOVE_INITIAL = "RESIDUAL_ABOVE_INITIAL"  # JS-5
    PPE_ONLY_CONTROLS = "PPE_ONLY_CONTROLS"  # JS-8
    TEMPLATE_REVIEW_DUE = "TEMPLATE_REVIEW_DUE"  # JS-9
    HSE_REVIEW_MISSING = "HSE_REVIEW_MISSING"  # PT-9
    DOCUMENT_MISSING = "DOCUMENT_MISSING"  # §3.1 mandatory documents
    CHECKLIST_INCOMPLETE = "CHECKLIST_INCOMPLETE"  # list C / X
    ROLE_MISSING = "ROLE_MISSING"  # §3.1 mandatory roles
    KEY_ROLE_INELIGIBLE = "KEY_ROLE_INELIGIBLE"  # PT-8
    NO_ELIGIBLE_CREW = "NO_ELIGIBLE_CREW"  # PT-8
    HOOK_NOT_MET = "HOOK_NOT_MET"  # HK3-1 under block policy
    GAS_TEST_REQUIRED = "GAS_TEST_REQUIRED"  # GT-1
    GAS_TEST_FAILED = "GAS_TEST_FAILED"  # GT-6
    GAS_TEST_EXPIRED = "GAS_TEST_EXPIRED"  # GT-3 / GT-4
    DETECTOR_CALIBRATION_OVERDUE = "DETECTOR_CALIBRATION_OVERDUE"  # GT-5
    DETECTOR_NOT_IN_SERVICE = "DETECTOR_NOT_IN_SERVICE"  # GT-5 quarantined / retired
    BUMP_TEST_MISSING = "BUMP_TEST_MISSING"  # GT-5
    DETECTOR_SENSOR_MISSING = "DETECTOR_SENSOR_MISSING"  # GT-5
    BACKDATED_TEST = "BACKDATED_TEST"  # GT-5 tested_at > 60 min before saving
    CSE_POINTS_REQUIRED = "CSE_POINTS_REQUIRED"  # CS-2
    TESTER_SIGNATURE_REQUIRED = "TESTER_SIGNATURE_REQUIRED"  # §3.10 tester without account
    ISOLATION_NOT_VERIFIED = "ISOLATION_NOT_VERIFIED"  # IS-6
    VERIFIER_IS_APPLIER = "VERIFIER_IS_APPLIER"  # IS-4
    PERSONAL_LOCKS_MISSING = "PERSONAL_LOCKS_MISSING"  # IS-5
    DEISOLATION_BLOCKED = "DEISOLATION_BLOCKED"  # IS-7 (meta.permits, meta.locks)
    LOCK_NOT_AVAILABLE = "LOCK_NOT_AVAILABLE"  # IS-2 lock already applied / wrong type
    SIMOPS_PROHIBITED = "SIMOPS_PROHIBITED"  # SM-5
    SIMOPS_COORDINATION_REQUIRED = "SIMOPS_COORDINATION_REQUIRED"  # SM-6
    SIMOPS_RULE_LOCKED = "SIMOPS_RULE_LOCKED"  # SM-3 default rules cannot be deleted/loosened
    WAP_NOT_ACTIVE = "WAP_NOT_ACTIVE"  # AW-2
    WAP_CREW_MISSING = "WAP_CREW_MISSING"  # AW-3
    OUTSIDE_WAP_WINDOW = "OUTSIDE_WAP_WINDOW"  # AW-4
    NOTAM_NOT_IN_EFFECT = "NOTAM_NOT_IN_EFFECT"  # AW-4
    OBS_CLEARANCE_REQUIRED = "OBS_CLEARANCE_REQUIRED"  # LF-9
    AIRCRAFT_PROXIMITY = "AIRCRAFT_PROXIMITY"  # AW-6
    WIND_LIMIT_EXCEEDED = "WIND_LIMIT_EXCEEDED"  # LF-6 / LF-7 / WH-7
    MIDDAY_BAN = "MIDDAY_BAN"  # HT-3 resume before 15:00
    MIDDAY_BAN_WINDOW = "MIDDAY_BAN_WINDOW"  # HT-2
    OUTSIDE_WINDOW = "OUTSIDE_WINDOW"  # PT-12 / SH-7
    LICENCE_INVALID = "LICENCE_INVALID"  # RG-1
    BARRIER_TOO_SMALL = "BARRIER_TOO_SMALL"  # RG-3
    BARRIER_NOT_VERIFIED = "BARRIER_NOT_VERIFIED"  # RG-3
    FIRE_IMPAIRMENT_NOT_APPROVED = "FIRE_IMPAIRMENT_NOT_APPROVED"  # HW-8
    UTILITY_CLEARANCE_MISSING = "UTILITY_CLEARANCE_MISSING"  # EX-3
    FALL_CLEARANCE_INSUFFICIENT = "FALL_CLEARANCE_INSUFFICIENT"  # WH-5
    HAZARDOUS_AREA_PROHIBITED = "HAZARDOUS_AREA_PROHIBITED"  # HW-9
    FIRE_WATCH_RUNNING = "FIRE_WATCH_RUNNING"  # HW-4
    ENTRANTS_INSIDE = "ENTRANTS_INSIDE"  # CS-7
    HEAT_CONTROLS_REQUIRED = "HEAT_CONTROLS_REQUIRED"  # HT-6
    HANDOVER_LIMIT = "HANDOVER_LIMIT"  # SH-6
    HANDOVER_TOO_EARLY = "HANDOVER_TOO_EARLY"  # §4.2 initiate ≤ 60 min before planned end
    MECHANICAL_NEAR_SERVICE = "MECHANICAL_NEAR_SERVICE"  # EX-4
    INSPECTION_REQUIRED = "INSPECTION_REQUIRED"  # EX-6
    ENERGIZED_HV_PROHIBITED = "ENERGIZED_HV_PROHIBITED"  # EL-3
    EXEMPTION_REQUIRED = "EXEMPTION_REQUIRED"  # EL-3 / LF-3 / HW-8 / HT-4
    CAPACITY_EXCEEDED = "CAPACITY_EXCEEDED"  # LF-3
    REVALIDATION_NOT_ALLOWED = "REVALIDATION_NOT_ALLOWED"  # SH-7
    CREW_NOT_BRIEFED = "CREW_NOT_BRIEFED"  # SH-4
    CAUSE_NOT_CLEARED = "CAUSE_NOT_CLEARED"  # SH-3 (text, CA In Progress after audit_critical)
    PAUSE_NOT_ALLOWED = "PAUSE_NOT_ALLOWED"  # SH-9
    CLOSURE_INCOMPLETE = "CLOSURE_INCOMPLETE"  # CL-2 (meta.items)
    POST_EXPIRY_CHECK_PENDING = "POST_EXPIRY_CHECK_PENDING"  # CL-6 / IS-7
    CA_REQUIRED = "CA_REQUIRED"  # AU-5 / CL-6
    AUDIT_LOCKED = "AUDIT_LOCKED"  # §4.9 locked audits: HSE Manager edits with reason
    # ---- Phase 4 (4-third-party-cert) ----
    CODE_IN_OTHER_CATALOGUE = "CODE_IN_OTHER_CATALOGUE"  # BD-3
    TPI_NOT_ACCEPTABLE = "TPI_NOT_ACCEPTABLE"  # TP-4 (meta.reason = one of the next five)
    TPI_NOT_APPROVED = "TPI_NOT_APPROVED"  # TP-4 (a)
    TPI_SUSPENDED = "TPI_SUSPENDED"  # TP-4 (a) / BL-6
    TPI_BLACKLISTED = "TPI_BLACKLISTED"  # TP-4 (a) / BL-7
    TPI_ACCREDITATION_INVALID = "TPI_ACCREDITATION_INVALID"  # TP-3 / TP-4 (b)
    TPI_SCOPE_NOT_COVERED = "TPI_SCOPE_NOT_COVERED"  # TP-4 (b)
    TPI_NOT_CLIENT_APPROVED = "TPI_NOT_CLIENT_APPROVED"  # TP-5
    TPI_NOT_INDEPENDENT = "TPI_NOT_INDEPENDENT"  # TP-6
    TPI_ACCREDITATION_REQUIRED = "TPI_ACCREDITATION_REQUIRED"  # §4.1 submit needs a checked one
    STANDARD_KIND_MISMATCH = "STANDARD_KIND_MISMATCH"  # §3.2 standard ↔ TPI kind
    SCOPE_EXCEEDS_ACCREDITATION = "SCOPE_EXCEEDS_ACCREDITATION"  # §3.3 client approval scope
    EQUIPMENT_EXISTS = "EQUIPMENT_EXISTS"  # EQ-1 (meta.equipment_no, meta.equipment_id)
    EQUIPMENT_EXISTS_OUT_OF_SCOPE = "EQUIPMENT_EXISTS_OUT_OF_SCOPE"  # EQ-1 (no identifying data)
    EQUIPMENT_BLACKLISTED = "EQUIPMENT_BLACKLISTED"  # EQ-1 / BL-3 / GE-2
    CATEGORY_MISMATCH = "CATEGORY_MISMATCH"  # EQ-2 / HK4-8
    VEHICLE_ALREADY_LINKED = "VEHICLE_ALREADY_LINKED"  # EQ-2 (1 : 1)
    USE_DETECTOR_REGISTER = "USE_DETECTOR_REGISTER"  # EQ-3
    ATTRIBUTE_REQUIRED = "ATTRIBUTE_REQUIRED"  # EQ-4 (meta.field)
    RELIEF_ABOVE_MAWP = "RELIEF_ABOVE_MAWP"  # §3.4 pressure fields
    EQUIPMENT_NOT_IN_SERVICE = "EQUIPMENT_NOT_IN_SERVICE"  # EM-2 (meta.reason = SSR)
    EQUIPMENT_DEPLOYED_ELSEWHERE = "EQUIPMENT_DEPLOYED_ELSEWHERE"  # EM-4
    TAG_EXISTS = "TAG_EXISTS"  # EM-1 / §3.8
    EQUIPMENT_RETIRED = "EQUIPMENT_RETIRED"  # §4.2 terminal
    EQUIPMENT_NOT_REGISTERED = "EQUIPMENT_NOT_REGISTERED"  # HK4-8
    EQUIPMENT_NOT_DEPLOYED = "EQUIPMENT_NOT_DEPLOYED"  # HK4-8 / GE-2
    OPERATOR_REQUIRED = "OPERATOR_REQUIRED"  # HK4-9 / 3-ptw v1.1 equipment lines
    EQUIPMENT_NOT_APPROVED = "EQUIPMENT_NOT_APPROVED"  # GE-2
    EQUIPMENT_OUT_OF_SERVICE = "EQUIPMENT_OUT_OF_SERVICE"  # HK4-3 / GE-2
    EQUIPMENT_QUARANTINED = "EQUIPMENT_QUARANTINED"  # GE-2
    ARRIVAL_INSPECTION_MISSING = "ARRIVAL_INSPECTION_MISSING"  # EM-3
    CERT_EXISTS = "CERT_EXISTS"  # EC-1 / PC-2
    CERT_NO_REUSED = "CERT_NO_REUSED"  # EC-1 / PC-2 (meta: existing item / holder)
    CERT_ALREADY_EXPIRED = "CERT_ALREADY_EXPIRED"  # EC-2
    SCAN_REQUIRED = "SCAN_REQUIRED"  # §3.6 / §3.9 scan to Submit
    SERIAL_MISMATCH = "SERIAL_MISMATCH"  # EC-5
    LOAD_TEST_REQUIRED = "LOAD_TEST_REQUIRED"  # EC-7
    SWL_ABOVE_RATING = "SWL_ABOVE_RATING"  # EC-8
    LIFTING_DUTY_NOT_CERTIFIED = "LIFTING_DUTY_NOT_CERTIFIED"  # EC-9
    LIMITATION_CONFLICT = "LIMITATION_CONFLICT"  # EC-11
    COLOUR_CODE_OUT_OF_PERIOD = "COLOUR_CODE_OUT_OF_PERIOD"  # EC-12
    CONFIGURATION_MISMATCH = "CONFIGURATION_MISMATCH"  # CF-3 (Accept needs the tick)
    CONFIGURATION_CHANGED = "CONFIGURATION_CHANGED"  # CF-1 hard stop
    INSPECTION_BEFORE_EVENT = "INSPECTION_BEFORE_EVENT"  # CF-1 / Z3
    BACKDATED_EVENT = "BACKDATED_EVENT"  # CF-2
    CONFIGURATION_EVENT_NOT_ALLOWED = "CONFIGURATION_EVENT_NOT_ALLOWED"  # §3.7 categories
    SCAFFOLD_DESIGN_REQUIRED = "SCAFFOLD_DESIGN_REQUIRED"  # SF-2
    CREW_NOT_CERTIFIED = "CREW_NOT_CERTIFIED"  # SF-3
    INSPECTOR_NOT_CERTIFIED = "INSPECTOR_NOT_CERTIFIED"  # SF-4
    BACKDATED_INSPECTION = "BACKDATED_INSPECTION"  # §3.8 inspected_at > 60 min ago
    RESTRICTIONS_REQUIRED = "RESTRICTIONS_REQUIRED"  # §3.8 yellow tag needs restrictions
    SCAFFOLD_NOT_REGISTERED = "SCAFFOLD_NOT_REGISTERED"  # SF-1 tag unknown on the project
    SCAFFOLD_INSPECTION_OVERDUE = "SCAFFOLD_INSPECTION_OVERDUE"  # SF-5 / Z6
    SCAFFOLD_TAG_RED = "SCAFFOLD_TAG_RED"  # HK4-3
    SCAFFOLD_INSPECTION_REQUIRED = "SCAFFOLD_INSPECTION_REQUIRED"  # SF-5 hard stop
    SCAFFOLD_YELLOW_TAG = "SCAFFOLD_YELLOW_TAG"  # SF-6 (met with conditions)
    CERT_ID_MISMATCH = "CERT_ID_MISMATCH"  # PC-3 (nothing stored)
    NAME_MISMATCH_CONFIRMATION = "NAME_MISMATCH_CONFIRMATION"  # PC-4
    LEVEL_NOT_ACCEPTED = "LEVEL_NOT_ACCEPTED"  # PC-7 (RADIOGRAPHER level I)
    LEVEL_REQUIRED = "LEVEL_REQUIRED"  # §3.9 level for RIGGER / ROPE-ACCESS / RADIOGRAPHER…
    CERT_SCOPE_MISMATCH = "CERT_SCOPE_MISMATCH"  # PC-7 (meta.which)
    CERT_LIMITATION = "CERT_LIMITATION"  # PC-8
    CARD_RESTRICTION_REVIEW = "CARD_RESTRICTION_REVIEW"  # PC-13
    TRADE_CERT_MISSING = "TRADE_CERT_MISSING"  # PC-12 (deployment warning)
    HOLDER_BANNED = "HOLDER_BANNED"  # BL-4 new submission
    CERT_HOLDER_BANNED = "CERT_HOLDER_BANNED"  # BL-4 provider hard stop
    CERT_MISSING = "CERT_MISSING"  # HK4-8
    CERT_EXPIRED = "CERT_EXPIRED"  # HK4-8
    CERT_UNVERIFIED = "CERT_UNVERIFIED"  # VF-1
    CERT_SUSPENDED = "CERT_SUSPENDED"  # HK4-8 / PC-10
    CERT_REVOKED = "CERT_REVOKED"  # HK4-8
    SWL_LIMITATION = "SWL_LIMITATION"  # HK4-8 rated load above certified / derated SWL
    WORKER_NOT_IN_SCOPE = "WORKER_NOT_IN_SCOPE"  # PC-1 holder without deployment in scope
    CHANNEL_NOT_REGISTERED = "CHANNEL_NOT_REGISTERED"  # VF-3
    VERIFICATION_URL_FOREIGN_DOMAIN = "VERIFICATION_URL_FOREIGN_DOMAIN"  # VF-4 (warning)
    EVIDENCE_REQUIRED_FOR_METHOD = "EVIDENCE_REQUIRED_FOR_METHOD"  # §3.10 evidence_file
    VERIFICATION_CLOSED = "VERIFICATION_CLOSED"  # already verified / failed
    ACCESSORY_REPAIR_NOT_ALLOWED = "ACCESSORY_REPAIR_NOT_ALLOWED"  # DF-7
    TPI_REINSPECTION_REQUIRED = "TPI_REINSPECTION_REQUIRED"  # DF-6
    DEFECTS_OPEN = "DEFECTS_OPEN"  # DF-6 return to service with open A / overdue B
    PHYSICAL_TAG_REQUIRED = "PHYSICAL_TAG_REQUIRED"  # DF-3 physical_tag_applied
    TPI_DEFECT_NOT_CANCELLABLE = "TPI_DEFECT_NOT_CANCELLABLE"  # §4.5 cancel
    PHASE4_NOT_ENABLED = "PHASE4_NOT_ENABLED"  # HK4-1 provider not registered on the project
    HOOK_POLICY_LOOSENING = "HOOK_POLICY_LOOSENING"  # HK4-6 / §4.8
    CRITICAL_CODE_NO_DEFERRAL = "CRITICAL_CODE_NO_DEFERRAL"  # HK4-6
    DEFERRAL_USED = "DEFERRAL_USED"  # HK4-6
    DEFERRAL_TOO_LONG = "DEFERRAL_TOO_LONG"  # HK4-6 (≤ 30 days)
    HOOK_NOT_MET_WARN = "HOOK_NOT_MET_WARN"  # HK4-4 transition-stage warning
    EXPIRING_7D = "EXPIRING_7D"  # §6.6 expiring (met, valid_until ≤ d + 7)
    UNKNOWN_CODE = "UNKNOWN_CODE"  # HK4-2 hook code not implemented (configuration error)
    # certification check (VF-8 / VF-9) result reasons (v0.5.1, additive)
    TOKEN_UNKNOWN = "TOKEN_UNKNOWN"
    CREDENTIAL_REVOKED = "CREDENTIAL_REVOKED"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    SETTING_LOOSENING = "SETTING_LOOSENING"  # §3.17 "shorten / tighten only"
    EVIDENCE_DOMAIN_MISMATCH = "EVIDENCE_DOMAIN_MISMATCH"  # IM-6
    IMPORT_SOURCE_NOT_ALLOWED = "IMPORT_SOURCE_NOT_ALLOWED"  # IM-6 tpi_register_file (403)
    TPI_BLACKLIST_SCOPE_REQUIRED = "TPI_BLACKLIST_SCOPE_REQUIRED"  # §3.1 blacklist_scope/from
    # ---- Phase 5 (5-training) ----
    INDUCTION_OWNED_BY_PHASE2 = "INDUCTION_OWNED_BY_PHASE2"  # BD5-4 / AC2
    CATALOGUE_LOOSENING = "CATALOGUE_LOOSENING"  # CC-2 / AC5
    ACCREDITED_PROVIDER_REQUIRED = "ACCREDITED_PROVIDER_REQUIRED"  # CC-4 / AC6
    PRACTICAL_REQUIRED = "PRACTICAL_REQUIRED"  # CC-5 / AC7
    PREREQUISITE_CYCLE = "PREREQUISITE_CYCLE"  # §3.1 / AC9
    COURSE_IN_USE = "COURSE_IN_USE"  # CC-1 / AC10 (409: deactivate instead)
    COURSE_INACTIVE = "COURSE_INACTIVE"  # §3.1 active = false: no new sessions / records
    PROVIDER_NOT_ACCEPTABLE = "PROVIDER_NOT_ACCEPTABLE"  # PV-3 (meta.reason = one of the next 8)
    PROVIDER_NOT_APPROVED = "PROVIDER_NOT_APPROVED"  # PV-3 (a)
    PROVIDER_SUSPENDED = "PROVIDER_SUSPENDED"  # PV-3 (a) / PV-5
    PROVIDER_BLACKLISTED = "PROVIDER_BLACKLISTED"  # PV-3 (a) / PV-6
    ACCREDITATION_INVALID = "ACCREDITATION_INVALID"  # PV-2 / PV-3 (b)
    ACCREDITATION_SCOPE = "ACCREDITATION_SCOPE"  # PV-3 (b)
    INTERNAL_NOT_ALLOWED = "INTERNAL_NOT_ALLOWED"  # PV-3 (c)
    CONTRACTOR_DELIVERY_NOT_ALLOWED = "CONTRACTOR_DELIVERY_NOT_ALLOWED"  # PV-3 (c)
    NOT_OWN_TREE = "NOT_OWN_TREE"  # PV-3 (c) independence
    PROVIDER_ACCREDITATION_REQUIRED = "PROVIDER_ACCREDITATION_REQUIRED"  # §4.1 submit external
    PROVIDER_BLACKLIST_SCOPE_REQUIRED = "PROVIDER_BLACKLIST_SCOPE_REQUIRED"  # PV-6 scope / from
    TRAINER_NOT_AUTHORISED = "TRAINER_NOT_AUTHORISED"  # TA-2 / TA-6
    TRAINER_NOT_TRAINED = "TRAINER_NOT_TRAINED"  # TA-3
    TRAINER_EVIDENCE_REQUIRED = "TRAINER_EVIDENCE_REQUIRED"  # §3.3 evidence for high-risk
    AUTHORISATION_TOO_LONG = "AUTHORISATION_TOO_LONG"  # §3.3 trainer_authorisation_max_months
    LINE_DERIVED_FROM_HOOK = "LINE_DERIVED_FROM_HOOK"  # MX-2 / AC29
    DUE_DAYS_NOT_ALLOWED = "DUE_DAYS_NOT_ALLOWED"  # §3.4 hook code / AC31
    ANY_OF_NOT_ALLOWED = "ANY_OF_NOT_ALLOWED"  # MX-3 / AC32
    MATRIX_LOOSENING = "MATRIX_LOOSENING"  # MX-8 / AC33
    EXEMPTION_NOT_ALLOWED = "EXEMPTION_NOT_ALLOWED"  # MX-10 / AC36
    ZONE_NOT_IN_DEPLOYMENT_SITES = "ZONE_NOT_IN_DEPLOYMENT_SITES"  # §3.5 / AC37
    SESSION_TOO_SHORT = "SESSION_TOO_SHORT"  # SS-2 / AC40
    SESSION_DAY_TOO_LONG = "SESSION_DAY_TOO_LONG"  # SS-2 / AC41
    SESSION_FULL = "SESSION_FULL"  # SS-3 / AC42
    SESSION_IN_PAST = "SESSION_IN_PAST"  # SS-4
    BACKDATED_SESSION = "BACKDATED_SESSION"  # SS-5 / AC43
    SCHEDULE_CLASH = "SCHEDULE_CLASH"  # SS-6 / AC45
    TRAINING_PREREQUISITE = "TRAINING_PREREQUISITE"  # SS-6 / TR-9 (meta.missing)
    TRAINING_ATTEMPTS_EXCEEDED = "TRAINING_ATTEMPTS_EXCEEDED"  # AT-5 / AC60
    NOMINATIONS_INCOMPLETE = "NOMINATIONS_INCOMPLETE"  # SS-8 / AC50 (meta.nominations)
    ATTENDANCE_SHEET_REQUIRED = "ATTENDANCE_SHEET_REQUIRED"  # SS-8 / AC51
    ATTENDANCE_INSUFFICIENT = "ATTENDANCE_INSUFFICIENT"  # AT-1 (result incomplete)
    ATTENDANCE_DAY_NOT_REACHED = "ATTENDANCE_DAY_NOT_REACHED"  # SS-7 days ≤ today only
    ASSESSOR_REQUIRED = "ASSESSOR_REQUIRED"  # AT-3 / AC59 practical by an assessor
    LANGUAGE_NOT_UNDERSTOOD = "LANGUAGE_NOT_UNDERSTOOD"  # AT-6 (result failed)
    LANGUAGE_MISMATCH = "LANGUAGE_MISMATCH"  # AT-6 warning
    RECORD_ALREADY_EXPIRED = "RECORD_ALREADY_EXPIRED"  # TR-3 / AC71
    REFRESHER_NOT_ELIGIBLE = "REFRESHER_NOT_ELIGIBLE"  # TR-11 / AC72
    RECORD_EDIT_LOCKED = "RECORD_EDIT_LOCKED"  # TR-12 accepted > 24 h (HSE Manager + reason)
    TRAINING_REGISTER_NOT_LIVE = "TRAINING_REGISTER_NOT_LIVE"  # HK5-1 / AC91
    TRAINING_REGISTER_LATER = "TRAINING_REGISTER_LATER"  # §3.16 may only move earlier / AC112
    TRAINING_HOOKS_NOT_ENABLED = "TRAINING_HOOKS_NOT_ENABLED"  # §4.7 policy action before HK5-1
    TRAINING_MISSING = "TRAINING_MISSING"  # HK5-6
    TRAINING_EXPIRED = "TRAINING_EXPIRED"  # HK5-6
    TRAINING_PENDING_REVIEW = "TRAINING_PENDING_REVIEW"  # HK5-6
    TRAINING_UNVERIFIED = "TRAINING_UNVERIFIED"  # VR-1 / HK5-6
    TRAINING_SUSPENDED = "TRAINING_SUSPENDED"  # HK5-3 hard stop
    TRAINING_REVOKED = "TRAINING_REVOKED"  # HK5-3 hard stop
    TRAINING_VERIFICATION_FAILED = "TRAINING_VERIFICATION_FAILED"  # HK5-3 hard stop
    INDUCTION_NOT_VALID = "INDUCTION_NOT_VALID"  # HK5-6 induction_link codes (CC-7)
    HOLDER_NOT_LINKED = "HOLDER_NOT_LINKED"  # HK5-7 appointment holder without a worker
    SESSION_NOT_EDITABLE = "SESSION_NOT_EDITABLE"  # §4.4 days changed after the first day
    # ---- Phase 6a (6a-occupational-health) ----
    FITNESS_CODE_IN_USE = "FITNESS_CODE_IN_USE"  # MC-1 / AC11 (409: make inactive instead)
    MEDICAL_PROVIDER_NOT_ACCEPTABLE = "MEDICAL_PROVIDER_NOT_ACCEPTABLE"  # MP-3 (meta.reason)
    PROVIDER_KIND_NOT_ALLOWED = "PROVIDER_KIND_NOT_ALLOWED"  # MP-3 (c) / MC-4
    NOT_PROJECT_CLINIC = "NOT_PROJECT_CLINIC"  # MP-3 (d)
    LICENCE_CHECK_REQUIRED = "LICENCE_CHECK_REQUIRED"  # MP-2 / EX-1 / AC14
    EXAMINER_LICENCE_INVALID = "EXAMINER_LICENCE_INVALID"  # EX-2
    EXAMINER_NOT_QUALIFIED = "EXAMINER_NOT_QUALIFIED"  # EX-2 / EX-3 / FA-3
    EXAMINER_NOT_LINKED = "EXAMINER_NOT_LINKED"  # FA-6
    PLAN_LOOSENING = "PLAN_LOOSENING"  # MR-5
    BACKDATED_ASSESSMENT = "BACKDATED_ASSESSMENT"  # FA-2
    FITNESS_ALREADY_EXPIRED = "FITNESS_ALREADY_EXPIRED"  # FA-2
    DUPLICATE_CODE_LINE = "DUPLICATE_CODE_LINE"  # FA-3
    RESTRICTIONS_NOT_ALLOWED = "RESTRICTIONS_NOT_ALLOWED"  # FA-3
    REVIEW_DATE_INVALID = "REVIEW_DATE_INVALID"  # FA-3 restriction / unfit review dates
    HOLD_REFERENCE_INVALID = "HOLD_REFERENCE_INVALID"  # FA-5
    PURPOSE_NOTICE_REQUIRED = "PURPOSE_NOTICE_REQUIRED"  # FA-7 / P6-3
    SECOND_OPINION_REQUIRED = "SECOND_OPINION_REQUIRED"  # FA-12
    ASSESSMENT_LOCKED = "ASSESSMENT_LOCKED"  # FA-14 (409: accepted > 24 h → revoke + new)
    CLINICAL_DATA_IN_SCAN = "CLINICAL_DATA_IN_SCAN"  # FA-9
    HOLD_RELEASE_REQUIRES_ASSESSMENT = "HOLD_RELEASE_REQUIRES_ASSESSMENT"  # FH-3
    MEDICAL_REGISTER_NOT_LIVE = "MEDICAL_REGISTER_NOT_LIVE"  # HK6-1
    MEDICAL_REGISTER_LATER = "MEDICAL_REGISTER_LATER"  # §3.12 may only move earlier
    NO_MEDICAL_PROVIDER = "NO_MEDICAL_PROVIDER"  # HK6-1
    MEDICAL_HOOKS_NOT_ENABLED = "MEDICAL_HOOKS_NOT_ENABLED"  # §4.6 policy action before HK6-1
    INCIDENT_RECORD_EXPECTED = "INCIDENT_RECORD_EXPECTED"  # RF-6 (warning)
    RTW_BEFORE_CLEARANCE = "RTW_BEFORE_CLEARANCE"  # RW-2 (warning, save allowed)
    PROHIBITED_DATA_HINT = "PROHIBITED_DATA_HINT"  # P6-2 / FA-4 (warning)
    MEDICAL_HOLD = "MEDICAL_HOLD"  # HK6-6 step 3
    MEDICAL_UNFIT = "MEDICAL_UNFIT"  # HK6-6 steps 4-5
    MEDICAL_PENDING_REVIEW = "MEDICAL_PENDING_REVIEW"  # HK6-6 step 5
    MEDICAL_UNVERIFIED = "MEDICAL_UNVERIFIED"  # FV-1 / HK6-6 step 5
    MEDICAL_REVOKED = "MEDICAL_REVOKED"  # HK6-3 hard stop
    MEDICAL_VERIFICATION_FAILED = "MEDICAL_VERIFICATION_FAILED"  # HK6-3 hard stop
    MEDICAL_MISSING = "MEDICAL_MISSING"  # HK6-6 step 5
    RESTRICTION_CONFLICT = "RESTRICTION_CONFLICT"  # HK6-6 step 6
    MEDICAL_REVIEW_DUE = "MEDICAL_REVIEW_DUE"  # HK6-6 step 7
    MEDICAL_EXPIRED = "MEDICAL_EXPIRED"  # HK6-6 step 7
    WORKER_UNKNOWN = "WORKER_UNKNOWN"  # HK6-6 step 1
    # ---- Phase 6b (6b-heat-stress) ----
    INSTRUMENT_NOT_COMPLIANT = "INSTRUMENT_NOT_COMPLIANT"  # HS-2
    INSTRUMENT_CALIBRATION_EXPIRED = "INSTRUMENT_CALIBRATION_EXPIRED"  # HS-2 / §3.3
    ZONE_ALREADY_COVERED = "ZONE_ALREADY_COVERED"  # HS-3
    REGIME_LOOSENING = "REGIME_LOOSENING"  # HS-5
    PERIOD_TOO_SHORT = "PERIOD_TOO_SHORT"  # HS-6
    HEAT_COVERAGE_INCOMPLETE = "HEAT_COVERAGE_INCOMPLETE"  # HS-7 (meta.zones)
    WBGT_REQUIRED = "WBGT_REQUIRED"  # WB-3
    VALUE_OUT_OF_RANGE = "VALUE_OUT_OF_RANGE"  # §3.3
    BACKDATED_READING = "BACKDATED_READING"  # WB-4
    WBGT_COMPONENT_MISMATCH = "WBGT_COMPONENT_MISMATCH"  # WB-2 (warning)
    STATION_INACTIVE = "STATION_INACTIVE"  # §3.8
    NA_NOT_ALLOWED = "NA_NOT_ALLOWED"  # RS-2
    NOT_IN_BAN_WINDOW = "NOT_IN_BAN_WINDOW"  # MB-1
    NO_ACTIVE_EXEMPTION = "NO_ACTIVE_EXEMPTION"  # MB-5
    OUTSIDE_BAN_PERIOD = "OUTSIDE_BAN_PERIOD"  # §3.10
    TOO_LATE_TO_CHANGE = "TOO_LATE_TO_CHANGE"  # AP-3
    HEAT_STOP = "HEAT_STOP"  # PH-3 (blocker)
    WBGT_READING_REQUIRED = "WBGT_READING_REQUIRED"  # PH-2 (blocker)
    HEAT_RESTRICTION = "HEAT_RESTRICTION"  # PH-6 (crew exclusion)
    HEAT_STOP_FOR_WORKER = "HEAT_STOP_FOR_WORKER"  # PH-5 (warning)
    WORKER_ACCLIMATISING = "WORKER_ACCLIMATISING"  # PH-7 (warning)
    # ---- Phase 6c (6c-emergency-drills) ----
    ERP_INCOMPLETE = "ERP_INCOMPLETE"  # ER-3 (meta.missing)
    ERP_NOT_APPROVED = "ERP_NOT_APPROVED"  # ER-2 / DR-1
    RESCUE_PLAN_REF_REQUIRED = "RESCUE_PLAN_REF_REQUIRED"  # ER-4
    DRILL_FREQUENCY_TOO_LOW = "DRILL_FREQUENCY_TOO_LOW"  # ER-5
    ASSEMBLY_POINT_IN_RESTRICTED_AREA = "ASSEMBLY_POINT_IN_RESTRICTED_AREA"  # ER-6
    ZONE_WITHOUT_ASSEMBLY_POINT = "ZONE_WITHOUT_ASSEMBLY_POINT"  # §4.3
    ALREADY_IN_TEAM = "ALREADY_IN_TEAM"  # RT-1
    CHECK_BACKDATED = "CHECK_BACKDATED"  # EA-2
    CHECK_WITHOUT_SCAN = "CHECK_WITHOUT_SCAN"  # EA-2 (warning)
    TIMELINE_ORDER = "TIMELINE_ORDER"  # DR-5
    INCIDENT_LINK_REQUIRED = "INCIDENT_LINK_REQUIRED"  # EV-4
    RESCUE_TEAM_NOT_REGISTERED = "RESCUE_TEAM_NOT_REGISTERED"  # PE-3 (blocker)
    RESCUE_DRILL_OVERDUE = "RESCUE_DRILL_OVERDUE"  # PE-3 (blocker)
    HEIGHT_RESCUE_NOT_READY = "HEIGHT_RESCUE_NOT_READY"  # PE-4 (warning)
    NO_READY_EXTINGUISHER = "NO_READY_EXTINGUISHER"  # PE-5 (warning)
    # ---- Phase 6d (6d-field-assurance §5.12) ----
    TEMPLATE_INCOMPLETE = "TEMPLATE_INCOMPLETE"  # TPL-2 (meta.missing)
    TEMPLATE_IN_USE = "TEMPLATE_IN_USE"  # TPL-5
    TEMPLATE_REQUIRED = "TEMPLATE_REQUIRED"  # ISP-1 / EXE-3
    TEMPLATE_NOT_APPLICABLE = "TEMPLATE_NOT_APPLICABLE"  # EXE-1
    TEMPLATE_IMMUTABLE = "TEMPLATE_IMMUTABLE"  # TPL-3 (409)
    SEVERITY_LOWERED = "SEVERITY_LOWERED"  # FND-1 / AUD-2
    FIX_ON_SPOT_NOT_ALLOWED = "FIX_ON_SPOT_NOT_ALLOWED"  # FND-3
    STOP_RECORD_REQUIRED = "STOP_RECORD_REQUIRED"  # FND-7
    STOP_RELEASE_CA_REQUIRED = "STOP_RELEASE_CA_REQUIRED"  # FND-8
    STOP_WORK_ACTIVE = "STOP_WORK_ACTIVE"  # FND-9 (Phase 3 resume)
    OFFLINE_SUBMIT_TOO_LATE = "OFFLINE_SUBMIT_TOO_LATE"  # EXE-6
    CLOCK_SKEW = "CLOCK_SKEW"  # EXE-6
    TOPIC_INCOMPLETE = "TOPIC_INCOMPLETE"  # TBT-1
    TOPIC_REVIEW_OVERDUE = "TOPIC_REVIEW_OVERDUE"  # TBT-2 (campaign: 422; talk: warning)
    WORKER_NOT_MOBILISED = "WORKER_NOT_MOBILISED"  # TBT-5
    DUPLICATE_ATTENDEE = "DUPLICATE_ATTENDEE"  # TBT-5
    ATTENDANCE_EVIDENCE_REQUIRED = "ATTENDANCE_EVIDENCE_REQUIRED"  # TBT-7
    TALK_LOCKED = "TALK_LOCKED"  # TBT-8 (409)
    TBT_SHORT = "TBT_SHORT"  # TBT-4 (warning)
    # ---- Phase 6e (6e-environmental §5.16) ----
    ASPECT_CONTROL_REQUIRED = "ASPECT_CONTROL_REQUIRED"  # ASP-2
    CONTROL_LEVEL_TOO_LOW = "CONTROL_LEVEL_TOO_LOW"  # ASP-2
    PRODUCER_REGISTRATION_INVALID = "PRODUCER_REGISTRATION_INVALID"  # PRM-4
    PROVIDER_LICENCE_INVALID = "PROVIDER_LICENCE_INVALID"  # CON-2
    LICENCE_SCOPE_MISMATCH = "LICENCE_SCOPE_MISMATCH"  # CON-2
    STREAM_NOT_ACCEPTED = "STREAM_NOT_ACCEPTED"  # WST-2
    CONTAINMENT_INSUFFICIENT = "CONTAINMENT_INSUFFICIENT"  # WST-2
    AIRSIDE_STORAGE_NOT_SECURED = "AIRSIDE_STORAGE_NOT_SECURED"  # AIR-2
    MANIFEST_REF_REQUIRED = "MANIFEST_REF_REQUIRED"  # CON-5
    DISCREPANCY_REASON_REQUIRED = "DISCREPANCY_REASON_REQUIRED"  # CON-7
    FIELD_CALIBRATION_REQUIRED = "FIELD_CALIBRATION_REQUIRED"  # MON-3
    LIMIT_LOOSENING = "LIMIT_LOOSENING"  # LIM-2
    ENGAGEMENT_REQUIRED = "ENGAGEMENT_REQUIRED"  # EXD-5
    INCIDENT_FIELDS_REQUIRED = "INCIDENT_FIELDS_REQUIRED"  # SPL-3
    INCIDENT_NOT_ENVIRONMENTAL = "INCIDENT_NOT_ENVIRONMENTAL"  # SPL-3
    CLEANUP_WASTE_UNTRACKED = "CLEANUP_WASTE_UNTRACKED"  # SPL-6
    DUPLICATE_WATER_ENTRY = "DUPLICATE_WATER_ENTRY"  # §3.14
    CONSIGNMENT_CLOSED = "CONSIGNMENT_CLOSED"  # §4.3 (409)
    PERMIT_NOT_VALID = "PERMIT_NOT_VALID"  # WAT-3 (warning)
    AVP_NOT_FOUND = "AVP_NOT_FOUND"  # AIR-3 (warning)
    # ---- Phase 6f (6f-incident-followup §5.12) ----
    RULE_LOOSENING = "RULE_LOOSENING"  # NR-3
    CLIENT_RECIPIENT_REQUIRED = "CLIENT_RECIPIENT_REQUIRED"  # NR-9
    WAIVER_EVIDENCE_REQUIRED = "WAIVER_EVIDENCE_REQUIRED"  # NR-8
    INVESTIGATION_NOT_APPROVED = "INVESTIGATION_NOT_APPROVED"  # PK-5
    PACK_NOT_APPROVED = "PACK_NOT_APPROVED"  # SB-2
    CHANNEL_NOT_ALLOWED = "CHANNEL_NOT_ALLOWED"  # SB-2
    SUBMITTED_AT_INVALID = "SUBMITTED_AT_INVALID"  # §3.5
    IDENTITY_IN_TEXT = "IDENTITY_IN_TEXT"  # P6f-3
    LESSON_INCOMPLETE = "LESSON_INCOMPLETE"  # LL-3
    REDACTION_NOT_CONFIRMED = "REDACTION_NOT_CONFIRMED"  # §3.6
    SELF_APPROVAL = "SELF_APPROVAL"  # LL-4
    NOT_DISTRIBUTED = "NOT_DISTRIBUTED"  # LL-4
    ON_BEHALF_NOTE_REQUIRED = "ON_BEHALF_NOTE_REQUIRED"  # DS-3
    LESSON_NOT_PUBLISHED = "LESSON_NOT_PUBLISHED"  # LK-2
    RATIONALE_REQUIRED = "RATIONALE_REQUIRED"  # EF-4
    FOLLOW_UP_REQUIRED = "FOLLOW_UP_REQUIRED"  # EF-5
    PACK_IMMUTABLE = "PACK_IMMUTABLE"  # §4.2 (409)
    SUBMISSION_LOCKED = "SUBMISSION_LOCKED"  # SB-5 (409)
    # ---- Phase 6g (6g-scorecard-reports §5.17) ----
    WEIGHTS_NOT_100 = "WEIGHTS_NOT_100"  # 6g
    LAGGING_WEIGHT_OUT_OF_RANGE = "LAGGING_WEIGHT_OUT_OF_RANGE"  # 6g
    CAP_REQUIRED = "CAP_REQUIRED"  # 6g
    PROFILE_BACKDATED = "PROFILE_BACKDATED"  # 6g
    SOURCES_NOT_CONFIRMED = "SOURCES_NOT_CONFIRMED"  # 6g
    COMMENT_WINDOW_CLOSED = "COMMENT_WINDOW_CLOSED"  # 6g
    COMMENT_WINDOW_OPEN = "COMMENT_WINDOW_OPEN"  # 6g
    DISPUTES_OPEN = "DISPUTES_OPEN"  # 6g
    CORRECTION_NOT_FOUND = "CORRECTION_NOT_FOUND"  # 6g
    CAP_NOT_EXCLUDABLE = "CAP_NOT_EXCLUDABLE"  # 6g
    WATCH_ENTRY_OPEN = "WATCH_ENTRY_OPEN"  # 6g
    PIP_INCOMPLETE = "PIP_INCOMPLETE"  # 6g
    SOURCE_REPORT_NOT_PUBLISHED = "SOURCE_REPORT_NOT_PUBLISHED"  # 6g
    SELF_REVIEW = "SELF_REVIEW"  # 6g
    RECIPIENT_SCOPE = "RECIPIENT_SCOPE"  # 6g
    EXTERNAL_NOT_ALLOWED = "EXTERNAL_NOT_ALLOWED"  # 6g
    PACK_TOO_LARGE_FOR_EMAIL = "PACK_TOO_LARGE_FOR_EMAIL"  # 6g
    COLUMN_NOT_EXPORTABLE = "COLUMN_NOT_EXPORTABLE"  # 6g
    PURPOSE_REQUIRED = "PURPOSE_REQUIRED"  # 6g
    EXPORT_TOO_LARGE = "EXPORT_TOO_LARGE"  # 6g
    SUBSCRIPTION_PERSONAL_DATA = "SUBSCRIPTION_PERSONAL_DATA"  # 6g
    SETTING_OUT_OF_RANGE = "SETTING_OUT_OF_RANGE"  # 6g
    COLUMN_NOT_PERMITTED = "COLUMN_NOT_PERMITTED"  # 6g
    PACK_ISSUED_IMMUTABLE = "PACK_ISSUED_IMMUTABLE"  # 6g
    SCORECARD_FINAL = "SCORECARD_FINAL"  # 6g
    EXPORT_RATE_LIMIT = "EXPORT_RATE_LIMIT"  # 6g
    SCORECARDS_NOT_FINAL = "SCORECARDS_NOT_FINAL"  # 6g
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class FieldError(BaseModel):
    """One field-level problem (used with VALIDATION_ERROR and DUPLICATE_VALUE)."""

    loc: list[str | int] = Field(description='Path to the field, e.g. ["body", "zone_type"].')
    msg: str = Field(description="English description of the problem.")
    msg_ar: str | None = Field(
        default=None,
        description="Arabic description of the problem (always sent by the server; a generic "
        "text per `type` when no specific translation exists).",
    )
    type: str = Field(description="Machine-readable error type, e.g. 'missing', 'value_error'.")


class ErrorDetail(BaseModel):
    code: ErrorCode = Field(description="Stable machine code; map it to EN/AR UI text.")
    message: str = Field(description="English, human-readable message.")
    message_ar: str | None = Field(default=None, description="Arabic message, when available.")
    errors: list[FieldError] | None = Field(
        default=None, description="Field-level errors (422 validation, 409 duplicates)."
    )
    meta: dict[str, Any] | None = Field(
        default=None,
        description="Machine-readable context for some codes, e.g. WORKER_EXISTS → "
        "{worker_id, worker_no}; VALIDITY_EXCEEDS_LIMIT → {limiting_factor, max_date}; "
        "WAP_BLOCKED → {blockers}; PREREQUISITES_NOT_MET → {requirements}. Phase 3: a "
        "blocked permit transition → {blockers: [{code, detail_en, detail_ar}]} with `code` = "
        "the first blocker; DURATION_EXCEEDS_LIMIT → {limiting_type, max_hours}; "
        "SIMOPS_* → {conflicts}; DEISOLATION_BLOCKED → {permits, locks}; CLOSURE_INCOMPLETE → "
        "{items}; REAUTH_REQUIRED → {reauth_minutes}.",
    )


class ErrorResponse(BaseModel):
    """Envelope for every 4xx/5xx response."""

    detail: ErrorDetail


class ApiError(Exception):
    def __init__(
        self,
        status_code: int,
        code: ErrorCode,
        message: str,
        message_ar: str | None = None,
        errors: list[FieldError] | None = None,
        headers: dict[str, str] | None = None,
        meta: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        for e in errors or []:
            if e.msg_ar is None:
                same = len(errors or []) == 1 and e.msg == message and message_ar
                e.msg_ar = message_ar if same else arabic_for(e.type)
        self.status_code = status_code
        self.code = code
        self.message = message
        self.message_ar = message_ar
        self.errors = errors
        self.headers = headers
        self.meta = meta

    def to_response(self) -> JSONResponse:
        body = ErrorResponse(
            detail=ErrorDetail(
                code=self.code,
                message=self.message,
                message_ar=self.message_ar,
                errors=self.errors,
                meta=self.meta,
            )
        )
        return JSONResponse(
            status_code=self.status_code,
            content=body.model_dump(mode="json", exclude_none=True),
            headers=self.headers,
        )


# Arabic fallbacks per error type (Pydantic types and our own codes).
AR_BY_TYPE: dict[str, str] = {
    "missing": "هذا الحقل مطلوب.",
    "string_too_short": "النص أقصر من المسموح.",
    "string_too_long": "النص أطول من المسموح.",
    "string_pattern_mismatch": "الصيغة غير صحيحة.",
    "string_type": "يجب أن تكون القيمة نصًا.",
    "int_parsing": "يجب أن تكون القيمة رقمًا صحيحًا.",
    "int_type": "يجب أن تكون القيمة رقمًا صحيحًا.",
    "decimal_parsing": "يجب أن تكون القيمة رقمًا.",
    "decimal_type": "يجب أن تكون القيمة رقمًا.",
    "decimal_max_digits": "عدد الأرقام أكبر من المسموح.",
    "decimal_max_places": "عدد المنازل العشرية أكبر من المسموح.",
    "float_parsing": "يجب أن تكون القيمة رقمًا.",
    "greater_than": "القيمة أصغر من المسموح.",
    "greater_than_equal": "القيمة أصغر من المسموح.",
    "less_than": "القيمة أكبر من المسموح.",
    "less_than_equal": "القيمة أكبر من المسموح.",
    "too_short": "عدد العناصر أقل من المسموح.",
    "too_long": "عدد العناصر أكبر من المسموح.",
    "enum": "القيمة ليست من الخيارات المسموحة.",
    "literal_error": "القيمة ليست من الخيارات المسموحة.",
    "bool_parsing": "يجب أن تكون القيمة نعم أو لا.",
    "date_parsing": "صيغة التاريخ غير صحيحة.",
    "date_from_datetime_parsing": "صيغة التاريخ غير صحيحة.",
    "datetime_parsing": "صيغة التاريخ والوقت غير صحيحة.",
    "datetime_from_date_parsing": "صيغة التاريخ والوقت غير صحيحة.",
    "time_parsing": "صيغة الوقت غير صحيحة.",
    "uuid_parsing": "المعرّف غير صالح.",
    "uuid_type": "المعرّف غير صالح.",
    "extra_forbidden": "هذا الحقل غير مسموح.",
    "list_type": "يجب أن تكون القيمة قائمة.",
    "dict_type": "يجب أن تكون القيمة كائنًا.",
    "model_type": "يجب أن تكون القيمة كائنًا.",
    "json_invalid": "صيغة JSON غير صحيحة.",
    "value_error": "القيمة غير صالحة.",
    "duplicate": "هذه القيمة مستخدمة من قبل.",
    "not_null": "لا يمكن حذف قيمة هذا الحقل.",
    "weak_password": "كلمة المرور لا تستوفي متطلبات الأمان.",
}
AR_GENERIC = "القيمة غير صالحة."


def arabic_for(type_: str) -> str:
    return AR_BY_TYPE.get(type_, AR_GENERIC)


def field_error(
    field: str, msg: str, type_: str = "value_error", msg_ar: str | None = None
) -> FieldError:
    return FieldError(loc=["body", field], msg=msg, msg_ar=msg_ar, type=type_)


def validation_error(
    field: str, msg: str, type_: str = "value_error", msg_ar: str | None = None
) -> ApiError:
    ar = msg_ar or arabic_for(type_)
    return ApiError(
        422, ErrorCode.VALIDATION_ERROR, msg, ar, errors=[field_error(field, msg, type_, ar)]
    )


def not_found(what: str = "Resource") -> ApiError:
    return ApiError(404, ErrorCode.NOT_FOUND, f"{what} not found.", "العنصر غير موجود.")


def forbidden(message: str = "You do not have permission for this action.") -> ApiError:
    return ApiError(403, ErrorCode.FORBIDDEN, message, "ليس لديك صلاحية لتنفيذ هذا الإجراء.")


def not_implemented() -> ApiError:
    return ApiError(501, ErrorCode.NOT_IMPLEMENTED, "Not implemented yet.")


async def api_error_handler(_: Request, exc: Exception) -> JSONResponse:
    if not isinstance(exc, ApiError):  # pragma: no cover
        raise exc
    return exc.to_response()


async def validation_exception_handler(_: Request, exc: Exception) -> JSONResponse:
    if not isinstance(exc, RequestValidationError):  # pragma: no cover
        raise exc
    errors: list[FieldError] = []
    for err in exc.errors():
        loc: list[Any] = [x if isinstance(x, str | int) else str(x) for x in err.get("loc", [])]
        t = str(err["type"])
        errors.append(
            FieldError(loc=loc, msg=str(err.get("msg", "")), msg_ar=arabic_for(t), type=t)
        )
    return ApiError(
        422,
        ErrorCode.VALIDATION_ERROR,
        "Request validation failed.",
        "فشل التحقق من صحة الطلب.",
        errors=errors,
    ).to_response()


_STATUS_CODES: dict[int, ErrorCode] = {
    401: ErrorCode.UNAUTHENTICATED,
    403: ErrorCode.FORBIDDEN,
    404: ErrorCode.NOT_FOUND,
    405: ErrorCode.NOT_FOUND,
}


async def http_exception_handler(_: Request, exc: Exception) -> JSONResponse:
    if not isinstance(exc, StarletteHTTPException):  # pragma: no cover
        raise exc
    code = _STATUS_CODES.get(exc.status_code, ErrorCode.INTERNAL_ERROR)
    return ApiError(exc.status_code, code, str(exc.detail)).to_response()


def error_responses(*codes: int) -> dict[int | str, dict[str, Any]]:
    """OpenAPI `responses=` helper: documents the error envelope for the given statuses."""
    descriptions = {
        401: "Not authenticated, session expired, or login rejected.",
        403: "Missing capability, read-only role, contractor suspended, or privacy notice not "
        "acknowledged (PRIVACY_ACK_REQUIRED).",
        404: "Not found or outside the caller's project/contractor scope.",
        409: "Invalid state transition, closed project, duplicate value or business-rule conflict.",
        410: "Token expired.",
        429: "Rate limit reached (AI_RATE_LIMITED); see Retry-After.",
        503: "Dependency unavailable (AI_UNAVAILABLE).",
        422: "Validation error (field errors in detail.errors).",
        501: "Not implemented yet.",
    }
    return {c: {"model": ErrorResponse, "description": descriptions.get(c, "Error")} for c in codes}
